### ISSUE TITLE
[Windows 10] Uninstall only visible for admin

### ISSUE THREAD

**Issue by andimik** [AlbrechtL/welle.io#100]
This seems to be the first software which does not appear in the apps menu for a user.

![deinstall_user](https://user-images.githubusercontent.com/24510556/27807806-85a40044-6043-11e7-9dea-4ac8340112ac.PNG)

--------------------

Only the admin has an entry.

![deinstall_admin](https://user-images.githubusercontent.com/24510556/27807810-91012ffc-6043-11e7-953d-afe06181eafa.PNG)

**Comment by AlbrechtL** [comment]
I don't known the reason for that. It would be nice if someone can check how to configure the [Qt Installer Framework](https://doc.qt.io/qtinstallerframework/)  to solve this issue.

**Comment by AlbrechtL** [comment]
@andimik Can you try the latest Windows installer please? Because I switched from Qt Installer Framework (QTIFW) 2.0 to QTIFW 3.0.

**Comment by andimik** [comment]
I cannot check in the next days. Let me try it in Windows in October again with multiple users. Currently I am working in Ubuntu only.

**Comment by andimik** [comment]
No, same as in July. I thought you have changed something, but the uninstall is still only visible for the admin.

I've installed the latest nightly build (2 days old), 20181229_29f4d4a_Windows_welle-io-setup.exe

for the admin
![deinstall_admin](https://user-images.githubusercontent.com/24510556/50560652-3f535680-0d03-11e9-8c00-81a6996120d8.PNG)


for the user
![deinstall_user](https://user-images.githubusercontent.com/24510556/50560654-45493780-0d03-11e9-98e1-19fd469177cc.PNG)

**Comment by AlbrechtL** [comment]
Did you install it as admin or user?

**Comment by andimik** [comment]
As user which then asked for the admin password.

**Comment by AlbrechtL** [comment]
Can you test it again with the latest nightly build (https://welle-io-nightlies.albrechtloh.de/). The background is because I changed the installer from Qt Install Framework to InnoSetup.

**Comment by AlbrechtL** [comment]
I'm closing this issue because I'm not sure if it is still relevant. If it still occurs in the latest version, we can reopen it.
