### ISSUE TITLE
[Android] Manual Channel font too large

### ISSUE THREAD

**Issue by andimik** [AlbrechtL/welle.io#104]
I cannot read the channel number as the font under Android is too large.

![screenshot_2017-07-12-22-26-21](https://user-images.githubusercontent.com/24510556/28138570-8deb4c52-6751-11e7-9f87-4d2ccfdb569f.png)

**Comment by andimik** [comment]
Or alternatively check, why the border is so thick.

**Comment by andimik** [comment]
Try (but not tested)
                        bottomPadding: x
                        topPadding: x
                        padding: x

or 

                        Layout.preferredHeight: x
                        Layout.preferredWidth: x
                        Layout.minimumHeight: x
                        Layout.minimumWidth: x

And for the touch buttons maybe add

                        antialiasing: true

as they are sometimes unsharp.

**Comment by AlbrechtL** [comment]
The best case is to add a custom ComboBox style to the file ["TouchComboBox.qml"](https://github.com/AlbrechtL/welle.io/blob/2b9766e241fa53ba754e5c49a039b0c10f8c2851/src/gui/QML/style/TouchComboBox.qml)

See also the ComboBox customizing documentation:
https://doc.qt.io/qt-5/qtquickcontrols2-customize.html#customizing-combobox

**Comment by AlbrechtL** [comment]
Fixed in 180a9457f03550881ec522cdcaa378f0eabce8d4.
