### ISSUE TITLE
[LINUX] appimage and build

### ISSUE THREAD

**Issue by justaquestion** [AlbrechtL/welle.io#106]
My experience with Arch Linux and with RTL_SDR:
**Appimage:**
Downloaded, but automatic detaching of kernel driver is not working (it works with qt-dab):
```
InputFactory: Input device: "rtl_sdr"
RTL_SDR: Open rtl-sdr
RTL_SDR: Found 1 devices. Uses the first one

Kernel driver is active, or device is claimed by second instance of librtlsdr.
In the first case, please either detach or blacklist the kernel module
(dvb_usb_rtl28xxu), or enable automatic detaching at compile time.

usb_claim_interface error -6
RTL_SDR: Opening rtl-sdr failed
InputFactory: Error while opening device " "rtl_sdr" ".
InputFactory: Error while opening device "rtl_sdr".
RadioController: AGC off
file:///tmp/.mount_welle-bpZydR/usr/qml/QtQuick/Controls/SplitView.qml:624: TypeError: Cannot call method 'updateFillIndex' of null
```
**Qtreactor build**
Make error:
```
~/welle.io/src/input/CAirspy.cpp:78: error: call of overloaded ‘abs(uint32_t)’ is ambiguous
~/welle.io/src/input/CAirspy.cpp:79: error: call of overloaded ‘abs(uint32_t)’ is ambiguous
```

**Comment by AlbrechtL** [comment]
**AppImage issue**
Please try to run `sudo modprobe -r dvb_usb_rtl28xxu` before executing the welle.io AppImage

**Qt Creator issue**
Please try to replace `abs(...)` by `std::abs(...)` in [CAirspy.cpp line 78 and 79](https://github.com/AlbrechtL/welle.io/blob/d527eb40d9ec549dded88dcba388596bf16340cc/src/input/CAirspy.cpp#L78) and report your result. Please also see issue #101 for more details.
