### ISSUE TITLE
[Windows] RTL2832u dongel not working on Windows 10.

### ISSUE THREAD

**Issue by PD1LOI** [AlbrechtL/welle.io#107]
I get welle.io not working even though I have installed the correct saddle driver See https://www.welle.io/devices/rtl_sdr

**Comment by andimik** [comment]
Please run Zadig as administrator. It seems it doesn't not apply for admin rights by itself. 

Then post what messages you get.

**Comment by PD1LOI** [comment]
I've all done, Sdrsharp does work.
![naamloos](https://user-images.githubusercontent.com/2943825/28743809-5c2f6e14-7453-11e7-9902-7809b492aa99.jpg)

**Comment by andimik** [comment]
Do you have two interfaces?

**Comment by PD1LOI** [comment]
Yes, but the dongel just works in Sdrsharp, he just does it.
![naamloo](https://user-images.githubusercontent.com/2943825/28745154-62ab640e-7472-11e7-9c20-d2edb448d959.png)
![naamlos](https://user-images.githubusercontent.com/2943825/28745155-62ade31e-7472-11e7-9021-018e70b8b294.jpg)

**Comment by AlbrechtL** [comment]
Two interfaces are not supported at the moment. See issue #95 for more details.

If you are able to recompile welle.io you can change [this line in CRTL_SDR.spp](https://github.com/AlbrechtL/welle.io/blob/7fe91a819a80f12c68b4237105422d39d1b8b269/src/input/CRTL_SDR.cpp#L107) from  
` ret = rtlsdr_open(&device, 0);` to ` ret = rtlsdr_open(&device, 1);` to use the second interface.

**Comment by PD1LOI** [comment]
Strange it has always worked, but after the last version of w10 it no
longer works.

Op 29 jul. 2017 17:00 schreef "Albrecht Lohofener" <notifications@github.com

**Comment by AlbrechtL** [comment]
Can you post the command line output please?

**Comment by PD1LOI** [comment]
![welle](https://user-images.githubusercontent.com/2943825/28908560-ac2c73f6-7824-11e7-9614-1269b9f7d253.png)

**Comment by AlbrechtL** [comment]
Yes, it is issue #95. Please follow #95 for a solution.

Now I close this issue because it is duplicated.

**Comment by PD1LOI** [comment]
I can not recompile the file. how do you do that?
