### ISSUE TITLE
Italian RAI slides not displayed - Subdirectories supported?

### ISSUE THREAD

**Issue by andimik** [AlbrechtL/welle.io#109]
Seems RAIWay defined subdirectories for their slides, for example

`Data/crit/radio1`

![grafik](https://user-images.githubusercontent.com/24510556/29167497-ef529c72-7dca-11e7-8a5c-781d159c0082.png)
which prevents welle.io from being displayed at all.

See zipped eti file below (use Rai Radio 1) which you can load in welle.io by writing the rawfile in the latest odr-dabmod

 `odr-dabmod eti2raw.ini`

whereas this `eti2raw.ini` is
```
[input]
transport=file
source=rai12d.eti
loop=0

[modulator]
gainmode =1
rate=2048000

[output]
output=file

[fileoutput]
format=u8
filename=/tmp/test.raw
```
[rai12d.eti.zip](https://github.com/AlbrechtL/welle.io/files/1214670/rai12d.eti.zip)

Syntax is `welle-io -F /tmp/test.raw -D rawfile -B u8`

Hint: qt-dab displays it: 

> going to show picture Data/crit/radio1/b0038b3e-ed9a-45b6-9a6f-69363f49b3b4.jpg

**Comment by basicmaster** [comment]
I just answered in the referenced DABlin issue.

**Comment by AlbrechtL** [comment]
Thanks for your investigation!

**Comment by AlbrechtL** [comment]
@andimik Please keep an eye on dablin. If Stefan (basicmaster) added some X-PAD related features to the dablin code then it is worth to update the welle.io X-PAD decoding code.

**Comment by andimik** [comment]
sure :-)

**Comment by andimik** [comment]
See https://github.com/Opendigitalradio/dablin/issues/28#issuecomment-322298269

**Comment by AlbrechtL** [comment]
Can you provide ready-to-go [RAW file](https://www.welle.io/devices/rawfile#record-an-raw-file) please?

**Comment by andimik** [comment]
Well, it's quite easy to get a ready raw file following my howto from the 1st posting ;-)

Anyway, it's here: https://we.tl/gz5P4TeyIx

(RAI 12D Monte Venda received on Dobratsch, Austria)

**Comment by AlbrechtL** [comment]
Thank for your very much courtesy (I don't have an ODR installation right now).

**Comment by AlbrechtL** [comment]
In ef3b61f I added the latest X-PAD decoding code from https://github.com/Opendigitalradio/dablin/tree/37065157a2b145b70fa3df8c7a1e9486ba0faa35 with enabled loose mode.
@basicmaster Thanks for adding this option!

Now you can see the "Rai Radio1" dynamic label and slide show.
![x_pad_rai](https://user-images.githubusercontent.com/11171787/29495082-d6f3661c-85b7-11e7-821e-10e5b81c6053.png)
