### ISSUE TITLE
[Windows] Version? / Font Blurry under Windows 7

### ISSUE THREAD

**Issue by nousername1** [AlbrechtL/welle.io#120]
1) I miss some Version Info.
2) On Windows 7 the Font is Blurry and show some Wobbling thing.

I believe its the Version from June?! It its still fix sry.

**Comment by andimik** [comment]
Have you clicked on ?

**Comment by AlbrechtL** [comment]
To Q1: You can find the version info if you click inside the settings view to the top right question mark.
![info](https://user-images.githubusercontent.com/11171787/29495257-d4047032-85bb-11e7-8463-5358761a4cc8.png)

To Q2: Please update your graphic card driver.

**Comment by nousername1** [comment]
So I got the current Version. The ? show just in the Settings Menu....
And I use the current Driver for my Thinkpad. In a old Version the Font was normal not blurry.

**Comment by AlbrechtL** [comment]
Please post the command line output.

**Comment by AlbrechtL** [comment]
Closed because there are no more information to analyse the issue.
