### ISSUE TITLE
Enhancement request: set program priority

### ISSUE THREAD

**Issue by theoldbloke** [AlbrechtL/welle.io#121]
Many thanks for a great program.

My weak little Windows 10 PC struggles when running welle.io and e.g. Firefox simultaneously: welle.io continually drops out and has to reconnect.

This works for me: press ctrl-shift-esc to bring up Task manager; right click welle-io.exe; select "Go to details"; right-click welle-io.exe; select "Set priority"; choose a higher priority.

Now welle.io doesn't drop out, and other apps are still responsive. 

However, you have to do this every time welle.io is started. There are various ways this could be made permanent, but it would be so very simple to just add a priority setting to the welle.io preferences. Looks like it's SetPriorityClass or SetThreadPriority under Windows, setpriority() under Linux.

Hope this is worthy of consideration.

**Comment by AlbrechtL** [comment]
Thanks for your request I added it to the [open task list](https://github.com/AlbrechtL/welle.io/wiki/Open-Tasks). 

I invite everyone to take this job and send me a pull request. This issue can be used to discuss this feature.
