### ISSUE TITLE
[Discussion] FM radio support

### ISSUE THREAD

**Issue by CodeHub00** [AlbrechtL/welle.io#122]
Rtl-Sdr supports Fm Radio signals.
So maybe welle.io can receive analog Fm radio too.

**Comment by viktorgino** [comment]
@AlbrechtL I have an FM radio GUI as part of my project ([viktorgino/headunit-desktop](https://github.com/viktorgino/headunit-desktop)) which I'd be happy to contribute to this project.

Qt has a radio module, which I think relies on V4L. Also there are some other projects focused on SDR based FM radio such as:
http://osmocom.org/projects/sdr/wiki/rtl-sdr
https://github.com/jorisvr/SoftFM


Screenshot:
![](https://raw.githubusercontent.com/viktorgino/headunit-desktop/gh-pages/screenshots/Screenshot%20from%202017-02-14%2009-18-27.png)

**Comment by CodeHub00** [comment]
I want to use DAB+ and FM radio on my Android head unit.
On my head unit, FM radio software is useless.
So maybe later welle.io support both of them.

**Comment by viktorgino** [comment]
@AlbrechtL How does rtl_fm_streamer compare (performance and quality wise) to the projects you mentioned? I'm happy to give this a shot, because its something I would really like to have as part of headunit-desktop

**Comment by AlbrechtL** [comment]
I never bench-marked rtl_fm_streamer against the other solutions.

Since all devices are SDRs it doesn't matter which sticks is used. At the moment welle.io supports rtl-sdr and airspy as well as rtl_tcp and RAW input.

**Comment by renne** [comment]
I suggest to add RDS-TP and RDS-TA support for FM-fallback with automatic frequency switching in car usage.

The current GUI elements are too small for car usage.

**Comment by AlbrechtL** [comment]
Regrading the small GUI elements: Please try to use Android Auto https://github.com/AlbrechtL/welle.io/issues/103.

**Comment by AlbrechtL** [comment]
I'm closing this issue for now. But it can be used to discuss this topic.

**Comment by alexmyczko** [comment]
Ohhhh cool! Also add Airbands?
