### ISSUE TITLE
[Android] I don't see the statusbar Android 4.4.4, 800x480

### ISSUE THREAD

**Issue by Tibor69** [AlbrechtL/welle.io#129]
I'm using 2 years old Car Android head unit with RK3066 chip and 800x480 display.
The android KitKat 4.4.4 rooted OS runs on the headunit.

Can you make that I can see the status bar on 800x480 display landscape mode?

**Comment by AlbrechtL** [comment]
What do you mean with status bar? Can you post a screen shot, please?

**Comment by Tibor69** [comment]
https://kephost.com/images/2017/09/19/Screenshot_2017-09-19-07-45-40_.jpg
https://kephost.com/images/2017/09/19/20170918_080131.jpg

**Comment by AlbrechtL** [comment]
Did you switch on the fullscreen mode?

**Comment by Tibor69** [comment]
Sorry. I'm stupid. The app is setting fullscreen mode.
When the fullscreen mode is off, I can see the status bar.
