### ISSUE TITLE
[Windows 7] install missing components?

### ISSUE THREAD

**Issue by sm3ulc** [AlbrechtL/welle.io#136]
Installed on a fresh Win7. Some graphical reqs missing?

![welle](https://user-images.githubusercontent.com/18304809/30693425-db20b5ec-9ecf-11e7-8cc1-1878fb82e664.png)

**Comment by andimik** [comment]
Have you tried the default win 7 skin?

**Comment by sm3ulc** [comment]
Yes. Same result.

**Comment by AlbrechtL** [comment]
I assume some graphic card issues because welle.io is using OpenGL for the GUI. Please try to update your graphic card driver.

**Comment by sm3ulc** [comment]
The Windows7 is running in vmware workstation. I've checked and it reports OpenGL 2.1 and documents claim 3.3.

**Comment by AlbrechtL** [comment]
Your set up is really special.

Officially we don't support Windows 7 nevertheless it is working in the most cases. We tested welle.io in a [VirtualBox](https://www.virtualbox.org/) with [this](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines) Windows 10 image.

We strongly recommend to switch to Windows 10.
