### ISSUE TITLE
DAB not working

### ISSUE THREAD

**Issue by AlbrechtL** [AlbrechtL/welle.io#14]
It seems that DAB is not working.
Tested with an odr-dabmod generated file.

**Comment by whiskerp** [comment]
DAB+ seems to be OK byt not DAB.

**Comment by AlbrechtL** [comment]
How did you try it? With real broadcasting or with [ODR](http://www.opendigitalradio.org)?
If possible can you provide a [RAW file](https://www.welle.io/devices/rawfile)?

**Comment by whiskerp** [comment]
With real DAB.

**Comment by sm0yyq** [comment]
Can say the same, DAB+ seems to work, but DAB sound's scrambled.

**Comment by whiskerp** [comment]
Exactly. It is not decoding DAB properly and it just squeaks and bubbles.
DAB+ is fine.

**Comment by AlbrechtL** [comment]
I know that DAB was working last (August 2016). But there where so much changes in the last 6 months  and this makes it hard to find the bug. And on my location I receive only DAB+.
I would be very happy if somebody provides a RAW file.

**Comment by AlbrechtL** [comment]
OK. I found out that commit 17f692d destroys the DAB support. Does somebody see the reason?

**Comment by AlbrechtL** [comment]
I found the problem. Please try again the latest version and report if the [fix](https://github.com/AlbrechtL/welle.io/commit/073840d29ef863db4c43265a3f0374229e63f8ac) works properly.

**Comment by whiskerp** [comment]
Hi

 

I’m sorry but I don’t have a Windows build environment set up so I’ll have to wait until your next release.

 

Thanks

Peter

**Comment by AlbrechtL** [comment]
The fix is included in this version: https://github.com/AlbrechtL/welle.io/releases/tag/V20170323

**Comment by tnadolecki** [comment]
I'll test now. 
In the meantime here is raw file containing DAB ,
http://matkaboska.sytes.net/s/tvascXIUIsC8UBe
Yup, finally learned how to record and play the right way :) 
Thank You 
Tom.

**Comment by tnadolecki** [comment]
I know it's bit late but I also confirm it is working now in DAB.
I apreciate all help.

**Comment by whiskerp** [comment]
Many thanks. DAB and DAB+ both working 😊
