### ISSUE TITLE
Sometimes, scanner skips channel 5C

### ISSUE THREAD

**Issue by AndrejaKo** [AlbrechtL/welle.io#16]
So I have a multiplex on channel 5C. Sometimes, during scanning, the program will try to scan channel 5B for long time and afterwards completely skip channel 5C and move on to 5D. 
![welle io](https://cloud.githubusercontent.com/assets/4117866/23989710/d7419f58-0a33-11e7-838b-0dc624e20ee3.png)

I am unable to reliably reproduce the issue, however it happens in around 30% of scans. 

P.S. Any hints on how to make this bug report more useful are welcome!

**Comment by AlbrechtL** [comment]
Thanks for reporting. Yes, the channel scan is worth to improve. I added it to the [task list}(https://github.com/AlbrechtL/welle.io/wiki/Open-Tasks)

**Comment by andimik** [comment]
I fixed the channel problem by editing the channels (= deleting those not in use) in the `DabConstants.cpp` file. But normally I use qt-dab and welle.io only offline having no DAB reception at home.

**Comment by AlbrechtL** [comment]
The channel scan is improved now. Please try it again with 0eb4a3f.
