### ISSUE TITLE
Don't display genre "none"

### ISSUE THREAD

**Issue by AlbrechtL** [AlbrechtL/welle.io#160]
It doesn't make sense to display the genre "none".
![none_sydney](https://user-images.githubusercontent.com/11171787/32728522-eec9e930-c880-11e7-92be-0de998cb89f9.png)

Full discussion: https://forum.welle.io/discussion/26/display-of-program-format-where-none-exists

**Comment by andimik** [comment]
I would say, replace it by "no PTY"

**Comment by AlbrechtL** [comment]
Fixed in 2140350.
