### ISSUE TITLE
"Found stations" changes into "Found channels"

### ISSUE THREAD

**Issue by FartherOut** [AlbrechtL/welle.io#166]
When the program is first started, going to the channel scan section, it says "Found stations:"
If I press "Clear station list", "Found stations:" changes into "Found channels:"
Is this normal procedure?
I feel it is a minor visual bug though.

**Comment by AlbrechtL** [comment]
Thanks for reporting!

**Comment by AlbrechtL** [comment]
Fixed in 9e5f98.
