### ISSUE TITLE
No program start Win7 64 bits

### ISSUE THREAD

**Issue by PA3BTS** [AlbrechtL/welle.io#18]
Software version 20170311 installed ok on a Win7 64 bits system with Airspy connected.
During startup process Airspy is seen by program, but start gets interrupted. 
Please see attached screenshot.
Any help appreciated.

Cornel
![snip_20170316121008](https://cloud.githubusercontent.com/assets/26459015/23994062/78c4cb0c-0a43-11e7-8bce-8e0f80688df7.jpg)

**Comment by sm0yyq** [comment]
Looks like u have trouble with ur graphic card drivers.

**Comment by PA3BTS** [comment]
Thank you, problem solved.
I have two graphic cards in my laptop, the switch to nVidia GT540M did the trick.
