### ISSUE TITLE
Better explaination of the display inside of the software

### ISSUE THREAD

**Issue by fvwcldgm** [AlbrechtL/welle.io#180]
I am a new user of welle.io.
After i ran the scan i expected that the left "smaller to bigger bars" is the receive quality. But that just as a technical person. I think the normal users would like to have some "signal" sign in front of that. For example: https://cdn.vectorstock.com/i/1000x1000/66/48/antenna-signal-sign-and-isolated-white-vector-18916648.jpg

Also normal user expect curved lines from bottom (low quality, small curved line) to top (good quality, all curved lines visable, longest on top).

What i as a more technical person dont understand are those 3 green dots on the right side next to the name. When i go with the mouse over this i dont get any information. When i press on it, i also dont get any information. What are those green rectangles for?

Would be nice to make those things more explainable by themself inside the software (yes, i could try to read the sourcecode but that is probably not what is expected as "usability").

**Comment by AlbrechtL** [comment]
The green rectangles are explained inside the FAQ https://www.welle.io/faq.

For the other points I added a improvement task to the [task list](https://github.com/AlbrechtL/welle.io/wiki/Open-Tasks). 

Everyone is invited to take this job!
