### ISSUE TITLE
Minimizing and maximizing welle.io stops sometimes the music for short time

### ISSUE THREAD

**Issue by fvwcldgm** [AlbrechtL/welle.io#181]
When i minimize the software and use the computer regulary and at some time maximize the software again, the music some times stops and starts. Here the log of this stop:

Using this version: welle.io_1.0-rc2_Linux_x86_64.AppImage

RTL_SDR: Decreased gain to 36.4
RTL_SDR: Increased gain to 37.2
RTL_SDR: Decreased gain to 36.4
RTL_SDR: Increased gain to 37.2
Audio: ActiveState
Audio: IdleState
Audio: StoppedState
Audio: ActiveState
RTL_SDR: Decreased gain to 36.4
RTL_SDR: Increased gain to 37.2

**Comment by AlbrechtL** [comment]
Can you redo the test with the latest next branch version, please?

**Comment by AlbrechtL** [comment]
Closed because of inactivity.
