### ISSUE TITLE
Channel-change plays short music, stops, and play normal afterwards

### ISSUE THREAD

**Issue by fvwcldgm** [AlbrechtL/welle.io#182]
The best way to reproduce this issue is when not changing the frequency-block and just jumping between channels in this block.
When i press on a second channel, it starts, then after about a half second it stops for a half second and then it play without stopping any more.

**Comment by AlbrechtL** [comment]
Can you redo the test with the latest next branch version, please?

**Comment by AlbrechtL** [comment]
Closed because of inactivity.
