### ISSUE TITLE
[Android] Please add welle.io app to F-Droid store

### ISSUE THREAD

**Issue by fvwcldgm** [AlbrechtL/welle.io#185]
Its missing recently: https://f-droid.org/packages/#q=welle

Could you please add the App to F-Droid App Store?
There are already F-Droid users that whould love to see this in the official F-Droid store. For example this user here: https://github.com/AlbrechtL/welle.io/issues/157

(not an own repository - use official F-Droid store please)

**Comment by AlbrechtL** [comment]
Great idea.
The issue is that there is nobody who is willing to maintain a F-Droid entry. Thats the reason why there isn't one.
I also assume that the most F-Droid users are fine with downloading the APK directly from the release page.

**Comment by AlbrechtL** [comment]
I added it to the [task list](https://github.com/AlbrechtL/welle.io/wiki/Open-Tasks).

**Comment by seuchato** [comment]
Hi
welle.io is again not available through fdroid. Would be nice, if you could (re)add it.
Greez
chris
