### ISSUE TITLE
[Website] Fix missing https on some links + US-surveillance

### ISSUE THREAD

**Issue by fvwcldgm** [AlbrechtL/welle.io#191]
Some of the links are missing https.
The first example is: https://github.com/AlbrechtL/welle.io
The top blue link links to the http site of welle.io

Second on welle.io site for example the phlow and github link are missing https.

The website welle.io is missing HSTS and HSTS-Preload https://hstspreload.org/

What is the reason for the website to use US-Services like cloudflare that cant do anything about the US-surveillance?

Would be great if the website could be hosted in germany or at least in the EU.

**Comment by AlbrechtL** [comment]
The reason is easy - it's simple to use such services and they do the job.

Thanks for the hint with the missing https. I fixed it.
