### ISSUE TITLE
[enhancement] Support for DVB-C & DVB-S radio

### ISSUE THREAD

**Issue by fvwcldgm** [AlbrechtL/welle.io#192]
Would be great if we could receive some other radio-"waves" then DAB+. There was already the request for FM-Radio. Analog FM-Radio would die in some near future. But support for digital radio like DVB-C and DVB-S would be nice.

**Comment by andimik** [comment]
Please use VLC

**Comment by fvwcldgm** [comment]
Then please tell AlbrechtL to stop development on welle.io . He is wasting his time because we can already listen to DAB+ with https://github.com/AlbrechtL/rtl_dab_streamer on RTL SDR devices. Also there are other solutions to listen to DAB.

If that does not confirm what you like to tell, then please confirm that when a tool is been named "wave" for radio listening, then it should support more different "waves" then just a single one.
AlbrechtL already confirmed that it would be nice to have FM-Radio - but that would die in near future. Other digital waves would make more sense.

**Comment by AlbrechtL** [comment]
I definitely agree that the name of welle.io is made for more than only DAB. It would be nice to have also DVB-S and DVB-C on board. I put it to the [task list](https://github.com/AlbrechtL/welle.io/wiki/Open-Tasks).

At the moment welle.io is a SDR with support of the cheap RTL-SDR. But the DVB-S and DVB-C bandwidth is bigger than the RTL-SDR bandwidth. For those it is impossible to implement DVB-x as an SDR. Of course somebody can add an interface like VLC is doing it. Please keep that this is not a matter how to do it. It is the matter who is doing it. Pull requests are welcome!
