### ISSUE TITLE
rtl_tcp use wrong port

### ISSUE THREAD

**Issue by betaros** [AlbrechtL/welle.io#193]
I created a shortcut to use welle.io with my SDR stick connected on my Odroid-c2 over the network. 
But welle.io always uses the wrong port 1234.

The command I use in the shortcut is:
> "C:\Program Files (x86)\welle.io\welle-io.exe" -D rtl_tcp -I 192.168.178.25 - P 1337

![issuereport](https://user-images.githubusercontent.com/9822442/35821655-05a47ccc-0aaa-11e8-8b49-889c75b344a4.png)

**Comment by gvanem** [comment]
Which version is this? The `-P` option was dropped some time ago. Try ` --rtltcp-port 1337` instead.

**Comment by betaros** [comment]
The version I use is 1.0-rc2.

When I try
> "C:\Program Files (x86)\welle.io\welle-io.exe" -D rtl_tcp -I 192.168.178.25 --rtltcp-port 1337

I get:
> Unknown option 'rtltcp-port 1337'.

Another idea was
> "C:\Program Files (x86)\welle.io\welle-io.exe" -D rtl_tcp --rtltcp-ip 192.168.178.25 --rtltcp-port 1337

The result was
> Unknown options: rtltcp-ip, rtltcp-port.

**Comment by AlbrechtL** [comment]
Please remove the white space " " between "-" and "P". It has to be "-P" not "- P".
