### ISSUE TITLE
Writing audio data to a file

### ISSUE THREAD

**Issue by MaxymValeriyovych** [AlbrechtL/welle.io#194]
Please, help me. How can I write audio DATA from this buffer to a file?

http://prntscr.com/ibb6ln

It's point in code.

qint64 CAudioIODevice::readData(char* data, qint64 len)
{
    qDebug() << "MyData   " << data;

    qint64 total = 0;
    total = Buffer->getDataFromBuffer(data, len / 2); // we have int16 samples
    if(total == 0)
    {
        memset(data, 0, len);
        total = len / 2;
    }
    return total * 2;
}

**Comment by gvanem** [comment]
Use a `f = fopen (file_name, "wb"); ` in the constructor, a `fclose(f);`  in the destructor and a
`fwrite (data, 1, (size_t)total f);` above.
But what are you trying to accomplish?

**Comment by MaxymValeriyovych** [comment]
I want to save шт file data which fed to the sound card.

**Comment by MaxymValeriyovych** [comment]
I have hieroglyphs in file instead normal symbols. How to change theirs encoding?
Hieroglyphs like on screenshot http://prntscr.com/ibb6ln

**Comment by AlbrechtL** [comment]
Please search at Google for a tutorial how to deal with binary data in C/C++.
