### ISSUE TITLE
Mac OSX support?

### ISSUE THREAD

**Issue by adamkk** [AlbrechtL/welle.io#20]
Hi,

can I install well.io by **macports like gnuradio?** Or is there a pre-compiled package that runs on a mac?

**Thanks in advance :-) Keep up good work !!!**

Best,
adamkk

**Comment by AlbrechtL** [comment]
At the moment there is no OSX build. I put it to the [task list](https://github.com/AlbrechtL/welle.io/wiki/Open-Tasks). Maybe someone takes this job.

**Comment by kgarrels** [comment]
you can help making that here: 
https://github.com/kgarrels/welle.io

**Comment by kgarrels** [comment]
it is now available here in this repo.

**Comment by AlbrechtL** [comment]
macOS support is added (https://github.com/AlbrechtL/welle.io/pull/41)

**Comment by AlbrechtL** [comment]
@kgarrels: Can you help to solve #44?
