### ISSUE TITLE
Windows command line parameters error?

### ISSUE THREAD

**Issue by lars18th** [AlbrechtL/welle.io#200]
Hi,

I'm trying to use the rawfile input source with the Windows version. However, when I execute:

`welle-io.exe -d rawfile --raw-file c:\tmp\file.raw --raw-format u8`

I receive one window error with this info:

`Unknown options: d, raw-file, raw-format`

Please, can you help me?

**Comment by lars18th** [comment]
I found the response...

`welle-io.exe -D rawfile -F c:\tmp\file.raw`

It's documented here: http://www.welle.io/devices/rawfile#odr-dabmod
So, I suggest to change the README.md of the github homepage, as the info in #USAGE is inconsistent.

Regards.

**Comment by andimik** [comment]
Please use a newer version or replace the parameters by

-F 
-D

**Comment by lars18th** [comment]
> Please use a newer version or replace the parameters by

newer than 1.0-rc2? https://github.com/AlbrechtL/welle.io/releases
I'm using this version.

**Comment by AlbrechtL** [comment]
The page https://github.com/AlbrechtL/welle.io reflects the latest development stage.
The source code of 1.0rc2 is [here](https://github.com/AlbrechtL/welle.io/tree/4bf9a9256b290cea6fdb8b2ab02ceb52dc15b451) which also included valid command line options for this version.

**Comment by AlbrechtL** [comment]
BTW. You can download latest build here: https://bintray.com/albrechtl/welle.io/welle.io_nightly#files

**Comment by lars18th** [comment]
Thank you, @AlbrechtL ,

I downloaded the nighly build for Windows, and now the command-line parameters it's working as expected.

Regards.
