### ISSUE TITLE
[Windows] No mouse pointer in full screen mode

### ISSUE THREAD

**Issue by lars18th** [AlbrechtL/welle.io#201]
Hi @AlbrechtL ,

Please, take into account that in Windows, when setting "full screen" mode, the mouse pointer is hidden. Then, without a key shortcut for restoring it, it's impossible to return. If I close the window with < ALT > + < F4 > when I restart Welle.io it allways goes full screen.

I hope you can fix this error.
Thank you!

**Comment by AlbrechtL** [comment]
Which Windows version do you use?

**Comment by lars18th** [comment]
> Which Windows version do you use?

Windows 7... of course!

**Comment by AlbrechtL** [comment]
I can't reproduce this issue on Windows 10. Unfortunately Windows 7 is not supported.

**Comment by lars18th** [comment]
> Unfortunately Windows 7 is not supported.

I'm very disappointed about this!
And I don't know why.
