### ISSUE TITLE
Suggestion: Cut single peaks in Spectrum

### ISSUE THREAD

**Issue by lars18th** [AlbrechtL/welle.io#202]
Hi @AlbrechtL ,

In some frequencies I see a large vertical continous line in the Spectrum. I feel it's some noise. So, I suggest to put some "top limiter" to cut the diagram when ane over peak appears.

See the attached capture:
![peak-spectrum](https://user-images.githubusercontent.com/9989964/36271436-ea92d0c8-127e-11e8-91a0-1b6726970648.jpg)

I hope you agree to cut these peaks.
Thank you!

**Comment by AlbrechtL** [comment]
You can analyze the peak with [QIRX](http://softsyst.com/qirx) which has this feature.

**Comment by lars18th** [comment]
> You can analyze the peak with QIRX which has this feature.

Yes, I know. But this "noise" it's permanent. So it's logical to cut-off the Spectrum.
