### ISSUE TITLE
[UI] Suggestion: Spectrum off

### ISSUE THREAD

**Issue by lars18th** [AlbrechtL/welle.io#206]
Hi,

I suggest to put a button (or other method) for stop the Spectrum (and save CPU power). I really like to see the ADVANCED info, but in some cases I don't need to have the Spectrum active (even with the adv panel open).

I hope you consider this suggestion.
Regards.

**Comment by AlbrechtL** [comment]
welle.io tries to keep the UI as simple as possible. For people that want to see a little bit more details we added the advanced mode. We don't plan to make the advanced mode more adjustable.

BTW: If you have a CPU that can't calculate the spectrum then you might use the wrong computer for SDR software.
