### ISSUE TITLE
Programs list panel more resizable 

### ISSUE THREAD

**Issue by lars18th** [AlbrechtL/welle.io#207]
Hi,

I see that the Pogram list panel is resizable **only** up to one level (around 80pixel). I found this a lot... the names never get wrapper, but when the Advanced panel is opened in several small screens the three panels are difficult to manage.

I suggest a simple change in the UI configuration for enabling the option to a more small Program list panel limit.
You agree?

**Comment by AlbrechtL** [comment]
Please give use an example why 80px is to much. Which display do you use?

**Comment by lars18th** [comment]
> Please give use an example why 80px is to much. Which display do you use?

- Android phone in portrait mode.
- Windows 10 tablet.
- Windows 7 in window mode ocuping only part of the monitor.

So, if this request it's only one line in the code, why not change it?
https://github.com/AlbrechtL/welle.io/blob/master/src/gui/QML/main.qml#L384
I suggest to use `Layout.minimumWidth: Units.dp(150)` or if you prefer replace with `Layout.preferredWidth: Units.dp(350)`.

_The problem is that the user can't adjust the size as s/he likes!_ 
I hope you hear users. :smile:

**Comment by AlbrechtL** [comment]
I don't really understand your issue. You can make welle.io really small.

![unbenannt](https://user-images.githubusercontent.com/11171787/36341279-139a3be6-13ec-11e8-86e5-2f72537a88ba.png)

**Comment by lars18th** [comment]
> I don't really understand your issue. You can make welle.io really small.

I can't do this in my Windows 7 computer. Also I can't do it in my Android phone. Too in my Windows 10 Tablet. Which version are you using? Ahh!!! I see: you're using Linux Ubuntu.

In any case, any problem to change the code to `Layout.preferredWidth` instead of `Layout.minimumWidth` ? Why **force** users?
