### ISSUE TITLE
[Windows] Window resize generates audio decoding errors

### ISSUE THREAD

**Issue by lars18th** [AlbrechtL/welle.io#208]
Hi @AlbrechtL ,

I don't know if you know or not. But in Windows when resizing the window of the Welle.io the audio suffers errors. So, if I drag the window and I move fast the mouse the audio goes very bad.

I feel this can be a problem with the priorities of the threads in the App. I suggest to assign the best priority to the decoding process and never stop it. I feel this interference can disturb other internal processes, like for example the frequency synchronization.

I hope this helps! :smile:

**Comment by AlbrechtL** [comment]
Duplicated with #181.
