### ISSUE TITLE
Suggestion: Configuration for "general" Frequency correction

### ISSUE THREAD

**Issue by lars18th** [AlbrechtL/welle.io#212]
Hi @AlbrechtL ,

I see that my RTL dongle has exactly the same "Frequency drift" everytime. So I suggest to add a config parameter for "save" or "set" a "general frequency correction". This will improve the automatic frequency correction algorithm.

I hope you like to do it!
Regards.

**Comment by AlbrechtL** [comment]
We will work on an improved synchronization algorithm (see [Open Taks](https://github.com/AlbrechtL/welle.io/wiki/Open-Tasks)). This makes on specific frequency drift option obsolete.

**Comment by lars18th** [comment]
> We will work on an improved synchronization algorithm

Great! Thank you.
