### ISSUE TITLE
[Windows]: Disable ScreenSaver when running.

### ISSUE THREAD

**Issue by lars18th** [AlbrechtL/welle.io#214]
Hi,

I feel this only has sense in Windows.

I suggest to add the option to disable the screensaver when running. But, only as an user option. By default off, but if someone needs to adjust an antenna using the Spectrum, then the screensaver will be disabled (while running).

You agree?

**Comment by AlbrechtL** [comment]
We tried to add only the necessary options to welle.io.
Please disable the screen saver via the system options.
