### ISSUE TITLE
Getting huge amount of [X-PAD len] in Terminal 

### ISSUE THREAD

**Issue by dutchievj** [AlbrechtL/welle.io#223]
Using **welle.io_1.0_Linux_x86_64.AppImage** and before that **welle.io_1.0-rc2_Linux_x86_64.AppImage** on **Ubuntu 16.04** with **RTL_TCP.**

On some dab+ channels I get a constant slow flow of [X-PAD len] and then another [X-PAD len] and another etc.

But on some other DAB+ channels I don't get them at all.

What does [X-PAD len] mean?

**Comment by basicmaster** [comment]
This means that the respective station sends its Dynamic Label and/or Slideshow violating the DAB specs (and wasting bandwidth) - which in this case actually requires to ignore that data. Here it is processed nevertheless and this message is an indicator for that.

Can you tell me on which multiplexes/stations this happens?

**Comment by mpbraendli** [comment]
I observe the same on radio TOP TWO+, in the SMC_D02 ensemble on 7D in Zürich.
MSC recording here: http://www.mpb.li/pub/toptwo.msc

**Comment by dutchievj** [comment]
@basicmaster 

It seems that all Dutch public (NPO) channels tricker this flood.

>  RadioController: Name of ensemble: "NPO             "
RadioController: Found station "NPO Radio 4     " ( 8204 )
RadioController: Found station "NPO FunX        " ( 8209 )
RadioController: Found station "NPO 3FM Alterna." ( 8210 )
RadioController: Found station "NPO Soul & Jazz " ( 8206 )
RadioController: Found station "NPO Radio 5     " ( 8205 )
RadioController: Found station "NPO SterrenNL   " ( 8212 )
RadioController: Found station "NPO 3FM         " ( 8203 )
RadioController: Found station "NPO Radio 2     " ( 8202 )
RadioController: Found station "NPO Radio 1     " ( 8201 )
RadioController: Found station "NPO 3FM KX Radio" ( 8214 )
RadioController: Found station "NPO Radio 4 Con." ( 8215 )
RadioController: Found station "NPO FunX Dance  " ( 8216 )
RadioController: Found station "NPO FunX Sl.Jamz" ( 8217 )

But the other Dutch non public (government sponsored) channels don't give [X-PAD len] at all.

**Comment by basicmaster** [comment]
OK, this is interesting. Could you provide a short (5min) ETI dump of the mux? E.g. using `dab2eti` or `eti-cmdline`.

**Comment by dutchievj** [comment]
No idea how to do that. I just have the AppImage and I am using that with an RTL dongle in another system.

**Comment by mpbraendli** [comment]
I'm afraid I also can't dump an ETI, because I only have my B200 with me.

**Comment by basicmaster** [comment]
@mpbraendli:
Your MSC dump is already enough.

@dutchievj:
I will contact a dutchman I know to hopefully get the ETI dump, to be able to contact NPO about that.

**Comment by AlbrechtL** [comment]
Are they any updates?

**Comment by basicmaster** [comment]
Just yesterday I received the dump of the NPO ensemble and was able to confirm that it is indeed affected.

To no longer "bug" normal users with the mentioned message, I disabled the message in loose mode (that is used by welle.io): https://github.com/Opendigitalradio/dablin/commit/8d50cea6e0aa7669e226ede75ba0493011d87458

@AlbrechtL:
Note that since a recent change you have to set the used MOT application type using the `SetMOTAppType()` method, after instantiation as well as after calling `Reset()`. I'm not sure whether you parse the User Application FIG: If so, you can use the parsed application type here. If not, use the hard coded default value `12`, which leads to the same behaviour as before the change.

**Comment by AlbrechtL** [comment]
Thanks! I will update the X-PAD code soon.

**Comment by AlbrechtL** [comment]
I updated the X-PAD decoder in https://github.com/AlbrechtL/welle.io/commit/86eb3509331d99d6b859a50e2385139fce4ee328.

**Comment by andimik** [comment]
Will the next branch also get this?

**Comment by AlbrechtL** [comment]
It is in the next branch only.

**Comment by andimik** [comment]
You are right, sorry.
