### ISSUE TITLE
[Raspberry Pi] You don't seem to have 'make' or 'gmake' in your PATH

### ISSUE THREAD

**Issue by MPunktBPunkt** [AlbrechtL/welle.io#229]
Hi, 

I got this message, while I tryed to compile the qt-sources for the raspberry. 
It was step 12 of the "RASPBERRY-PI.md". 

This solved my problem, if anyone has the same ...
  sudo apt-get install build-essential

**Comment by AlbrechtL** [comment]
Which message do you mean?

**Comment by FartherOut** [comment]
Interesting.
I thought build-essentials and gcc and make and cmake and all those are already included in a stock install of Ubuntu.
Is this not the case?

My guide does not have a step installing any such packages because I didn't think it was necessary.
