### ISSUE TITLE
show "ppm" in addition to frequencey correction

### ISSUE THREAD

**Issue by beta-tester** [AlbrechtL/welle.io#238]
there is frequency correction shown on the expert view of welle.io.
is it possible to show the ppm value there as well in addition?

10^6 * -freq_correction / freq_tuned = ppm

e.g.:
current channel: 5C (178.352 MHz)
freq. correction: -11879 Hz **_(66.60 ppm)_**

i think this is an easy to implement feature, but would help to calibrate the SDR device for other applications without calculating manually.

**Comment by beta-tester** [comment]
i have implemented that ppm addition...
here the patch file of the changes:
[patch-ppm.txt](https://github.com/AlbrechtL/welle.io/files/1954048/patch-ppm.txt)

**Comment by beta-tester** [comment]
in **ExpertView.qml** maybe change
`cppRadioController.FrequencyCorrectionPpm`
to
`cppRadioController.FrequencyCorrectionPpm.toFixed(2)`

to have only 2 digits after the point.

**Comment by AlbrechtL** [comment]
Thanks for the idea.

It would be nice if you could send a pull request for the [next branch](https://github.com/AlbrechtL/welle.io/tree/next).

**Comment by beta-tester** [comment]
ppm is merged to the next branch.
so, hopefully it can be seen in the next release...

**Comment by AlbrechtL** [comment]
Please review my comment: https://github.com/AlbrechtL/welle.io/pull/243#issuecomment-385421261
