### ISSUE TITLE
Provide an Audiostream/API

### ISSUE THREAD

**Issue by martenumberto** [AlbrechtL/welle.io#239]
Is it possible to provide an Audiostream and/or an API?
I'm trying to build an app for Android Auto to play music over the OpenAuto project.
The decoding should be done by an Raspberry (with attached RTL-SDR Stick) only the Playback, Control and the Information should be done by the Android app

**Comment by mpbraendli** [comment]
I'm working on an API in welle-cli, with the primary purpose to do some monitoring. See `next` branch, compile with CMake. Work in progress!

**Comment by AlbrechtL** [comment]
Are they any updates to this topic?

**Comment by mpbraendli** [comment]
I would argue that `welle-cli` now offers an HTTP API that would be usable for such an application. As before: work in progress.

**Comment by mpbraendli** [comment]
Closing the ticket because I believe the desired application is doable with welle-cli.
