### ISSUE TITLE
Garbled sound

### ISSUE THREAD

**Issue by tnadolecki** [AlbrechtL/welle.io#24]
Found 11 channels. Out of 11 only 2 sound fine. Rest is garbles like old days so called "cooked mp3".
The 2 channels that work have + at the end of channel name, I'm not sure whether that is significant to the issue.
Please see attached video demonstrating the issue.
Thank You.
Tom.

https://www.youtube.com/watch?v=x5jJujLJepA

**Comment by AlbrechtL** [comment]
Thanks for your bug report.
Unfortunately, DAB is not working, see https://github.com/AlbrechtL/welle.io/issues/14

I'm closing it because this bug is already reported.
