### ISSUE TITLE
[Linux] Project ERROR: Unknown module(s) in QT: charts

### ISSUE THREAD

**Issue by beta-tester** [AlbrechtL/welle.io#242]
i have Ubuntu 16.04.x LTS and i tried to follow the build description [Ubuntu Linux 16.04 LTS](https://github.com/AlbrechtL/welle.io#ubuntu-linux-1604-lts)

i downloaded "Open Source Usage under (L)GPL v3 license" -> "Go open source" -> `qt-unified-linux-x64-3.0.4-online.run`

i installed QT 5.9 including the QT Charts 
![screenshot from 2018-04-26 10-30-47](https://user-images.githubusercontent.com/4750719/39294857-164f7ed8-493d-11e8-987b-5fccf1733763.png)

i installed the packages as shown
`sudo apt install libfaad-dev libfftw3-dev librtlsdr-dev libusb-1.0-0-dev mesa-common-dev libglu1-mesa-dev libpulse-dev`

i cloned the project `git clone https://github.com/AlbrechtL/welle.io.git`

but when i open the file `~/welle.io/welle.io.pro`
i get the following error in Qt Creator.
```
Project MESSAGE: Current git hash = 4e13f5e
Project ERROR: Unknown module(s) in QT: charts
Warnings while parsing QML type information of /usr/lib/x86_64-linux-gnu/qt5/qml/Ubuntu/Content:
Failed to parse "/usr/lib/x86_64-linux-gnu/qt5/qml/Ubuntu/Content/plugins.qmltypes".
Error: /usr/lib/x86_64-linux-gnu/qt5/qml/Ubuntu/Content/plugins.qmltypes:276:19: Expected string literal to contain 'Package/Name major.minor' or 'Name major.minor'.
/usr/lib/x86_64-linux-gnu/qt5/qml/Ubuntu/Content/plugins.qmltypes:277:36: Expected array literal with only number literal members.
/usr/lib/x86_64-linux-gnu/qt5/qml/Ubuntu/Content/plugins.qmltypes:283:19: Expected string literal to contain 'Package/Name major.minor' or 'Name major.minor'.
/usr/lib/x86_64-linux-gnu/qt5/qml/Ubuntu/Content/plugins.qmltypes:284:36: Expected array literal with only number literal members.
/usr/lib/x86_64-linux-gnu/qt5/qml/Ubuntu/Content/plugins.qmltypes:301:19: Expected string literal to contain 'Package/Name major.minor' or 'Name major.minor'.
/usr/lib/x86_64-linux-gnu/qt5/qml/Ubuntu/Content/plugins.qmltypes:302:36: Expected array literal with only number literal members.
```
i also tried Qt 5.10 instead of Qt5.9...
i also tried to install Qt as root...
... all without any difference and no success to build/run welle.io.

EDIT: even installing all sub-items of Qt5.9.5, i don't get the project to build/run

**Comment by andimik** [comment]
Same here. It worked for me last time I built it, I guess mid of March.

**Comment by beta-tester** [comment]
i deleted the Qt folders
```
rm -rf ~/Qt/
rm -rf ~/.config/Qt/
rm -rf ~/.config/QtProject/
```

then i did really a full installation of Qt 5.9.5 with really **ALL** its sub-items (3.19 GByte).
(i think i could skip "Sources", but i wanted to be really sure)
![screenshot from 2018-04-27 06-25-42](https://user-images.githubusercontent.com/4750719/39344753-a3a169a2-49e4-11e8-9955-25925755c7d0.png)
now it works... i can build and debug/run the welle.io application.
(last time where i said, that i marked all sub-items, i skipped Sources and Android items - oops)

thank you for your help and the really nice piece of software "welle.io"

**Comment by beta-tester** [comment]
ok, this works as well...
takes less disk space
```
rm -rf ~/Qt/
rm -rf ~/.config/Qt/
rm -rf ~/.config/QtProject/
rm ~/.config/QtProject.conf
```
and
![screenshot from 2018-04-27 10-12-54](https://user-images.githubusercontent.com/4750719/39352533-51cb1a3a-4a05-11e8-9b36-56e55b256aa6.png)

**Comment by andimik** [comment]
BTW: Is it really necessary to install the complete Qt?

On a fresh Kubuntu I get with `cmake`

>   Could not find a package configuration file provided by "Qt5Quick" with any
>   of the following names:
> 
>     Qt5QuickConfig.cmake
>     qt5quick-config.cmake

But with `qmake` I get some more missing packages

> Project MESSAGE: Current git hash = da73c76
> Project ERROR: Unknown module(s) in QT: qml quick charts multimedia

**Comment by AlbrechtL** [comment]
At the moment cmake is not supported with a stock Ubuntu and it derivatives.

It close it because this issue is solved.

**Comment by AlbrechtL** [comment]
I just tried Ubuntu 18.04 LTS with cmake successfully.

Please install the following packages
```
qtbase5-dev
qtdeclarative5-dev
qtmultimedia5-dev
libqt5charts5-dev
qml-module-qtcharts
qml-module-qtquick-controls2
qml-module-qtquick-controls
qml-module-qt-labs-settings
```

**Comment by andimik** [comment]
No, there is an error:
> qrc:/src/gui/QML/MainView.qml:43 module "QtQuick.Controls" version 2.3 is not installed

(I'm trying to build the next branch)

**Comment by AlbrechtL** [comment]
The next branch requires QT 5.10 which is not shipped with Ubuntu 18.04. Ubuntu 18.04 only includes QT 5.9.
To build the next branch you have to use the QT Online Installer to install QT 5.10.

**Comment by dirkhohmann** [comment]
O.k. folks, I tried to build on Ubuntu 18.04 in May 2019. There's no QT 10 5.10 available. I tried QT 9.13, 9.5 always missing "QT charts" - I don't wanna waste my time on this broken stuff - good bye

**Comment by AlbrechtL** [comment]
Please follow the https://github.com/AlbrechtL/welle.io/blob/next/README.md and install Qt 5.10 or above. Then you will be able to build welle.io.

**Comment by dirkhohmann** [comment]
I follwed the instructions in the readme, simple straight forward but reality was different.  After several attempts with different Qt configurations I could successfuly build welle.io.
It seems that the dependencies are not really clean.

**Comment by AlbrechtL** [comment]
Which dependencies do you mean?
