### ISSUE TITLE
[next] Use tabs instead of buttons to select plots

### ISSUE THREAD

**Issue by AlbrechtL** [AlbrechtL/welle.io#249]
Use tabs instead of buttons to select plots, to waste less horizontal space

**Comment by AlbrechtL** [comment]
I plan to make the expert view modular. Each module can be enabled/disabled.

At he moment I have the following modules in mind.
 * TII information
 * Channel information
 * Spectrum
 * CIR
 * Null symbol
 * QPSK
 * Receiver hardware

**Comment by mpbraendli** [comment]
Excellent! I plan to add more channel information details to the backend-frontend interface, I will try to integrate those into the channel information view, if appropriate.

**Comment by AlbrechtL** [comment]
Done. Now it is possible to watch Spectrum, CIR, Null symbol, QPSK in the same time. See the next branch.
