### ISSUE TITLE
RTL-SDR offset tuning & DC correction

### ISSUE THREAD

**Issue by beta-tester** [AlbrechtL/welle.io#252]
is there a way for "offset tuning" and DC correction?
 i have an old RTL-SDR dongle (with a E4000 tuner) that has a horrible big peak on the tuning frequency.
on other software i enable "offset tuning" for that dongle to don't have that big peak + DC correction, but welle.io don't have such an option (yet?).
i can not use automatic (software) gain, because i takes the big peak into account to adjust the gain.
i have to turn off that automatic gain option and have to manually control the gain.
![screenshot from 2018-05-01 12-21-30](https://user-images.githubusercontent.com/4750719/39469789-45f26e92-4d3a-11e8-8492-117a2bc1cc25.png)

**Comment by Waitsnake** [comment]
It is the same problem with my rad1o (uses HackRF driver over soapysdr). It has this horrible peak in the middle too (with all programs not only with welle.io). I think this could be one reason why auto gain is not working at my device too. So I can only use manual gain at the moment.
Second reason for problems with AGC in my case is that m_device->getGainRange() gives a too large maximum that is not accepted by m_device->setGain() later. But I think the second problem looks like an issue in the pothosware/SoapyHackRF and not of welle.io. I need to dig into this later.
Anyway I only want to say there are more than one SDR device out there with the same peak.

**Comment by AlbrechtL** [comment]
Those features could be interesting for the next branch.

Which software provides these features? If one of these software is open source you can check how it is implemented and describe it here, please.

**Comment by beta-tester** [comment]
i know those options from sdr-sharp, but it is not open source.
[sdr-angle](https://github.com/f4exb/sdrangel) has those options as well but offset tuning is called a bit different there. (relative position of device center frequency).
but there it seems not to work as well as on sdr-sharp.
[librtlsdr](https://github.com/steve-m/librtlsdr)
[offset tuning](https://github.com/steve-m/librtlsdr/) 
rtl_fm has dc blocking filter and offset tuning, but the source Code i found is many years old.
[a pdf how to dc Blocking in Gnu radio](https://www.rtl-sdr.com/wp-content/uploads/2017/02/Getting-rid-of-that-center-frequency-spike-in-gnuradio_07.pdf)
![sdr angel](https://user-images.githubusercontent.com/4750719/39486281-dbbd3736-4d7b-11e8-9d38-9952e6506f7c.JPG)
but not all RTL-SDR tuner do support offset tuning the E4000 does, but R820T don't as far as i know.

**Comment by mpbraendli** [comment]
The first two references point to functionality in librtlsdr, which are not applicable to the SoapySDR input. I don't know if they are implemented in software or in the rtlsdr dongle itself.

However, gr-correctiq is a software DC offset compensation that we could take into welle-io. It measures I and Q DC offset separately and substracts it. The two offsets are averaged over time using an [exponential moving average](https://en.wikipedia.org/wiki/EWMA) here:
https://github.com/ghostop14/gr-correctiq/blob/master/lib/correctiq_impl.cc#L121

**Comment by AlbrechtL** [comment]
To use the gr-correctiq sounds the best way to do the correction. I will put this ticket to the [next version](https://github.com/AlbrechtL/welle.io/projects/1) project page.

**Comment by beta-tester** [comment]
> The first two references point to functionality in librtlsdr, which are not applicable to the SoapySDR input. I don't know if they are implemented in software or in the rtlsdr dongle itself.


yes and no.

yes, i have seen the offset tuning option on RTL drivers only, and i mean the E4000 tuner can do so and the R820T don't. so they do it in hardware on the dongle itself.
but in general, offset tuning is possible on all sdr devices, if you have enough "spare" bandwidth available.
lets say you want to tune to a DAB channel, but the sdr device has a big spike on its center frequency, then an option is to set the sdr to a center frequency left or right beside the DAB channel of interes and the bandwidth to twice of the required channel bandwidth. then in software you ignore the center frequency part and lower left part that contains the bandwitch out of interest. that would be kind of a lower/upper side band filter. but to do this kind of "software driven offset tuning" for DAB you need a bandwidth of 4MHz. to have the 1536kHz of interest in the upper/lower side out of the sdr spike on center frequency.

that's how i understood "offset tuning" in theory. if they can not do it in Hardware on the device itself, this is not practicable for RTL dongles, because of their limited bandwidth of only 2.4MHz, but HackRF and PlutoSDR can have easily have more than 4MHz bandwidth.

**Comment by mpbraendli** [comment]
Yes, you are right: while the linked references themselves don't apply, the principle still does.

SoapySDR offers the ability to set such an LO offset [here](https://github.com/pothosware/SoapySDR/blob/master/include/SoapySDR/Device.hpp#L726). It would be possible to add the LO offset setting to the SoapySDR settings dialog. The good thing is that this does the LO offset in the device, and therefore doesn't increase the sample rate we get from the device.

**Comment by beta-tester** [comment]
by reading something about DAB signals realized, that the bandwidth od a channel is 1537kHz and in that signal there are 1536 subcarriers of 1kHz each. and a Special feature of DAB is, that the carrier in the middle is obmitted. if this is correct, then maybe it is possible to competely ignore and blank out the spike at the center frequency 
so maybe in the special case of DAB no offsettuning or dc correctrion is necessary to get rid of the spike.

**Comment by mpbraendli** [comment]
That's correct, there's no data in the carrier k=0. But moving this spike outside of passband will allow us to use the software AGC, and make better use of the dynamic range.

**Comment by beta-tester** [comment]
sorry, i am a "noob"
ok, i am quiet now.

**Comment by mpbraendli** [comment]
No you're not, your suggestion was good!

**Comment by andimik** [comment]
Same here. Your idea was good. I had the same wish some time ago, but then I bought an Airspy, which does not have this spike.

**Comment by mpbraendli** [comment]
Summary of the ticket:

* [ ] add an option that calls `rtlsdr_set_offset_tuning()`
* [ ] add an option that controls LO offset for SoapySDR

**Comment by mpbraendli** [comment]
Commit 9ca2fa2 adds this setting, but I'm not currently in a situation where I can properly test.

For the RTLSDR, the offset_tuning is set to `true` if the LO offset is different from 0, i.e. the slider not in the centre position. @beta-tester could you build latest `next` and compare with your first test?

**Comment by beta-tester** [comment]
@mpbraendli
i just cloned and build the latest `next` and tried to turn  LO offset up/down to +/-4000.
but i still can see the very big peak always in the center of the frequency spectrum.
compared to the current `master` i don't see any differences in the spectrum behavior.

**Comment by mpbraendli** [comment]
Ok, I wasn't sure if this was the right approach, maybe it using manual gain for such devices is necessary.

I now have access to a rad1o badge, I will quickly try with that.

**Comment by mpbraendli** [comment]
Well, it seems this LO offset makes no difference :-( On some channels I have a huge centre spike with the rad1o, and LO offset has no influence.

I propose to remove it from the GUI, we cannot compensate for all device limitations.

**Comment by mpbraendli** [comment]
It seems to have negative effects: also https://github.com/AlbrechtL/welle.io/commit/9ca2fa2bdf2cace339ca9d870ce709bb412e90cc#r30384093

**Comment by mpbraendli** [comment]
I've reverted the commit adding the LO offset setting as it creates more trouble than it solves.
