### ISSUE TITLE
[Linux] Add support for MPRIS

### ISSUE THREAD

**Issue by minecraft2048** [AlbrechtL/welle.io#265]
On Android, welle.io have those prev/next/play buttons to go to previous station/next station/stop and play, and on the notification display it shows the radio station name and whatever other radio information. On desktop Linux, [MPRIS](https://specifications.freedesktop.org/mpris-spec/latest/) does the same thing, like this 
![mpris](https://user-images.githubusercontent.com/2445636/40751430-717c90d4-64ae-11e8-9bef-45e5b75033cc.png)

**Comment by AlbrechtL** [comment]
Thanks for the idea! I added it to the [open task list](https://github.com/AlbrechtL/welle.io/wiki/Open-Tasks).

**Comment by tenzap** [comment]
see PR #543 
Until it is merged, you can test it through my [fork](https://github.com/tenzap/welle.io/tree/next)
