### ISSUE TITLE
Slide disappears when switching from/to Expertmode

### ISSUE THREAD

**Issue by andimik** [AlbrechtL/welle.io#267]
When you switch between the expert mode the current slide disappears and only the next one is shown. Well, not really an issue, but I just discovered it.

**Comment by AlbrechtL** [comment]
In which version do you discovered this issue?

**Comment by andimik** [comment]
With e74a22e

**Comment by andimik** [comment]
Have not tested others

**Comment by AlbrechtL** [comment]
Please try it with next version.

**Comment by andimik** [comment]
Seems this works now :-)
