### ISSUE TITLE
[rtl-sdr] AGC problems

### ISSUE THREAD

**Issue by Wikinaut** [AlbrechtL/welle.io#27]
I can only get welle.io working here with manual gain (12,50 or so), which results in SNR 14dB.
AGC results in unreliable rx quality, and SNR decreases !

When increasing the manual gain, I can get a better SNR. When further increasing the gain, the SNR decreases. So there appears to be a problem with AGC.

**Comment by AlbrechtL** [comment]
This problem appears of the signal strength is to strong at your location. Does this also happens with qt-dab?

**Comment by Wikinaut** [comment]
No. qt-dab works very well, this is why I suppose it may be a software problem. On some stations, I see a very strong pilot at the mid frequency (Träger), on others not.

By the way, why don't you use "dB" at the vertical axis ?

**Comment by Wikinaut** [comment]
Pls. let me know, if you need more details, or if I can help with further tests.

**Comment by Wikinaut** [comment]
@AlbrechtL what are reasonable good SNR values ?

**Comment by andimik** [comment]
There is no general rule for that. You have to try it. Furthermore, every stick supports different gain values.

The biterror rate is a factor, too.

But as this is obviously a mirror of 12C (you receive no other transmission) it really makes no sense to continue on 44 MHz.

**Comment by Wikinaut** [comment]
As already mentioned, qt-dab works. Perhaps you have an idea, where I can start investigating, I still suppose it's a code problem with your code.

**Comment by AlbrechtL** [comment]
Do you mean that AGC is working well with qt-dab?

**Comment by Wikinaut** [comment]
Yes. I am just checking that. DRadio signal is a strong one (I will check another soon):

* autogain is on

![20170323-22 24 01_auswahl](https://cloud.githubusercontent.com/assets/1151915/24270962/890f1056-1017-11e7-81e4-2fc261cb9de6.png)

**Comment by Wikinaut** [comment]
Here's another one ("RBB Antenne" on channel 7D)

![20170323-22 32 09_auswahl](https://cloud.githubusercontent.com/assets/1151915/24271206/9627f914-1018-11e7-8aef-2355703a5921.png)

**Comment by andimik** [comment]
Interesting for me: Different Muxes need different CPU power.

**Comment by Wikinaut** [comment]
Wait: I just toggled qt-dab setting for autogain. It *might* be that the displayed setting is *not* the correct one!!!

**Comment by Wikinaut** [comment]
Ah interesting! I have to report this to qt-dab as well: when I play with the agc setting, the reception gets worse. Only when I rescan the band (here: 7D) it works again good. 

May this be the reason ? Is there a difference when toggling agc ?
* on a station
* per band (pilot) ?

**Comment by Wikinaut** [comment]
(afk for 45 minutes)

**Comment by Wikinaut** [comment]
@andimik the two have different protection levels.

**Comment by AlbrechtL** [comment]
I added an experimental new AGC for rtl-sdr. This AGC is implemented in welle.io instead of using the original rtl-sdr AGC.

Please try it again with the version https://github.com/AlbrechtL/welle.io/commit/01c2f7662f855c9aa8117d8daf16b7c2be83f93e and report your results.

**Comment by Wikinaut** [comment]
:1 :1 Perfect!

**Comment by Wikinaut** [comment]
SNR values here around 19 dB. Quicker feedback was not possible :-)

**Comment by Wikinaut** [comment]
How can I send you a donation ?

**Comment by Wikinaut** [comment]
It looks as if stronger stations (when using AGC) are still causing problems. I cannot see frame sync, RS, or frame errors in the expert window, but the spectrum looks different than others, and audio signal is muted now and then (drop out?  muted ?)

When not using AGC and using manual gain, these stations can be played without drop outs. (Example: manual gain 14, SNR 7..9 dB works; switching to AGC: drop outs)

**Comment by AlbrechtL** [comment]
I did some improvements. Please try it again and report your results.

**Comment by Wikinaut** [comment]
:+1: quick feedback: no drop-outs any more. Also the spectrum view appears to look better.

**Comment by Wikinaut** [comment]
Correction: now the reception has many drop outs. So I now suppose it may be a temperature problem with the stick. Will try to reproduce the issue (switching off, cooling, retrying), perhaps returning the stick.

**Comment by Wikinaut** [comment]
Again: qt-dab works well. Strange.....

**Comment by Wikinaut** [comment]
In welle.io, what does frequency correction mean ? After a restart of it, welle.io works.

**Comment by AlbrechtL** [comment]
The frequency correction is part of the synchronization to the channel. If you use a cheap stick without temperature compensation the frequency is shifting permanently. So it needs to corrected. This part of the code is buggy.  Sometimes welle.io is running out of sync and needs a resynchronization. But qt-dab should have the same problem because welle.io uses qt-dab code.
For a short workaround it also helps just to switch to another frequency.

**Comment by Wikinaut** [comment]
@AlbrechtL I tested qt-dab with Radio GOLD more than 3 hours: no drop-outs.

But with welle.io, unfortunately, there are still issues (drop-outs). Also the spectrum looks strange. Let me know, if you want me to post some screen shots.

**Comment by AlbrechtL** [comment]
Do you have the sound issues also with disabled expert view?

**Comment by AlbrechtL** [comment]
I opened a new issue https://github.com/AlbrechtL/welle.io/issues/35 for the expert view sound problem.

**Comment by Wikinaut** [comment]
@AlbrechtL 
> Do you have the sound issues also with disabled expert view?
Tests started. Quick response: you seem to be right, may be now an expert-view-causes-sound-drops problem. 

I will report in #35, if I notice further drops. I am just enjoying the Sonntagskonzert on RBB kulturradio. Shown gains (in the terminal window) are currently between 19,7 and 22,9 and once I see 25,4 dB.

**Comment by Wikinaut** [comment]
BTW: I always started welle.io from within the QTCreator on a 8GB Linux Mint 18.1 (=Ubuntu 16.04).

**Comment by Wikinaut** [comment]
I think, this can be closed. I leave it up to you.

**Comment by AlbrechtL** [comment]
I think so too.
