### ISSUE TITLE
[Windows, next-nightly] builds

### ISSUE THREAD

**Issue by beta-tester** [AlbrechtL/welle.io#272]
you are publishing (kind of) nightly builds of the master branch [here](https://bintray.com/albrechtl/welle.io/welle.io_nightly)

would it be possible to do it as well for the next-nightly [here](https://bintray.com/albrechtl/welle.io/welle.io_next_nightly)?
i am only able to compile welle from source code for linux sucessfully. on the other laptop i use Windows, and there i don't have the abillity to compile it by my self. so it would be usefull to have a **next**-nightly build

**Comment by AlbrechtL** [comment]
We had some issues with BinTray because we used to much space there. I had to delete all next builds to make new uploads possible. Please check it out again (https://bintray.com/albrechtl/welle.io/welle.io_next_nightly#files).

**Comment by andimik** [comment]
Is this the next? Because the filenames don't mention it.

**Comment by beta-tester** [comment]
yes, thank you there is a file now.

@andimik , yes it is the build of the branch **next**.
the name next can be seen in the link path welle.io_**_next_**_nightly.

**Comment by andimik** [comment]
Ok thanks, I didn't double check with the commit version
