### ISSUE TITLE
[next] Mono stations are shown as stereo

### ISSUE THREAD

**Issue by andimik** [AlbrechtL/welle.io#277]
In Slovenija, some stations use 32 kHz 24 kBit mono, but it is shown as stereo.

![grafik](https://user-images.githubusercontent.com/24510556/42845915-aa349ca8-8a17-11e8-9fb0-1026cd1a3371.png)

Tested with b68d488 . 

[slo_10d_2018-07-08_1146.eti.zip](https://github.com/AlbrechtL/welle.io/files/2203424/slo_10d_2018-07-08_1146.eti.zip)

`cat slo_10d_2018-07-08_1146.eti | odr-dabmod eti2raw.ini | ./20180717_b68d488_Linux_welle-io-x86_64.AppImage --raw-file /dev/stdin  -d rawfile`

and eti2raw.ini is

```
[input]
transport=file
source=/dev/stdin

[modulator]
gainmode =1
rate=2048000

[output]
output=file

[fileoutput]
format=u8
filename=/dev/stdout

```

Dablin shows mono (and I know it as well)

![grafik](https://user-images.githubusercontent.com/24510556/42846051-1027ce0e-8a18-11e8-822f-46055bfecdb9.png)

**Comment by AlbrechtL** [comment]
Can it be that this station uses parametric stereo?

**Comment by basicmaster** [comment]
No, as in such a case DABlin indicates "HE-AAC v2" and "Stereo".

**Comment by andimik** [comment]
No, this is mono.

**Comment by AlbrechtL** [comment]
OK then, it seems to be a bug.

**Comment by mpbraendli** [comment]
Wow, your ETI file has a lot of frame count discontinuities! I think I'll generate an ETI with all combinations to test.

**Comment by andimik** [comment]
I see, I will check with another one

**Comment by mpbraendli** [comment]
Fixed in 0cac18f

And I discovered that `welle-cli` cannot handle mono streams at all :-/ Another thing to debug...

@andimik please open the issue again if you still have a problem with the signalling of mono/stereo with your programme!

**Comment by andimik** [comment]
Merci :-)

**Comment by mpbraendli** [comment]
welle-cli mono decoding is now also fixed.

**Comment by AlbrechtL** [comment]
Makes it sense to print the AAC mode in welle-io in expert mode as well?

**Comment by mpbraendli** [comment]
I believe it is. This idea is tracked in https://github.com/AlbrechtL/welle.io/projects/1#card-9663493 already.
