### ISSUE TITLE
[next] Centre frequency 130 MHz at rawfile 

### ISSUE THREAD

**Issue by andimik** [AlbrechtL/welle.io#278]
![grafik](https://user-images.githubusercontent.com/24510556/42846867-74634838-8a1a-11e8-9339-2109cd1628ce.png)

When I play a file the centre frequency is 130 MHz (why not 0 MHz?).

BTW: The text in the station info section is shown as

> Current channel: File (N/A MHz)

**Comment by AlbrechtL** [comment]
Good question. Seems to be a bug.

**Comment by AlbrechtL** [comment]
Fixed in 344b0f57a152c3094155b5bc8fdf245f64d9c946
