### ISSUE TITLE
CRTL_SDR destructor is no called on linux, device is not closed on exit

### ISSUE THREAD

**Issue by klumw** [AlbrechtL/welle.io#279]
The destructor of CRTL_SDR class on linux is not called on exit, 
therefore rtlsdr_close is not called. 
If the program is shut down the device is still open and consumes a lot of energy.
Making an explicit destructor call on exit solves the problem on linux. 
Tested on Raspberry 3 with Debin Stretch.

**Comment by mpbraendli** [comment]
Thanks for the notice. This should be fixed in commit 1c51818
