### ISSUE TITLE
[Suggestion] Expert mode: add an IQ constellation chart

### ISSUE THREAD

**Issue by Wikinaut** [AlbrechtL/welle.io#28]
I suggest to show the QPSK IQ constellation (the qt-dab program shows it):

Example from https://github.com/JvanKatwijk/qt-dab#features :

![serveimage](https://github.com/JvanKatwijk/qt-dab/blob/master/screenshot_qt-dab.png?raw=true)

[UPDATED]
image from qt-dab program

**Comment by Wikinaut** [comment]
(I updated the image)

**Comment by andimik** [comment]
I agree, but first the existing diagram hast to be readable.

**Comment by AlbrechtL** [comment]
I added your wish to see the IQ constellation to the task list. But please keep in mind that it is actually not planned to add this into welle.io. If more people needs this feature they can write it into this issue.

**Comment by lars18th** [comment]
:+1:
