### ISSUE TITLE
recording broken

### ISSUE THREAD

**Issue by beta-tester** [AlbrechtL/welle.io#285]
in version 4.0.6 seems the recording is broken.
i just redorded a huge file with sdrangel 4.0.6 and tried to play back,
but the shown frequency "1,000,000kHz",
the shown bandwidth "0.058k",
the shown time "1970-03-15"
and the shown length are wrong
and nothing is happen on the waterfall nor the spectrum view.

i tried an older similar huge recoding made with 4.0.4 and there i can playback the recording correctly.

damn stupid me, i updated sdrangel without testing if the recording will succeed, just before i recorrded an importand one-time-ever-event... (installing and setting up the wireless consumption meter of my  radiator)
now i guess i lost everything i wanted to record/playback/analyse... :((

i used the windows version 4.0.6 of sdrangel.
with my PlutoSDR.

![recording broken](https://user-images.githubusercontent.com/4750719/44255735-491e6680-a207-11e8-8684-95df8675cc45.PNG)

**Comment by AlbrechtL** [comment]
:grinning:
