### ISSUE TITLE
Request to add recording functionality

### ISSUE THREAD

**Issue by diddy12345** [AlbrechtL/welle.io#286]
Could I request to add a recording feature to Welle.io ?

This could be a simple record button or maybe even a timed recording feature where the user can set a recording time and the station to record from.

If there are legal issue, I suspect this can be worked around. Other software like SDR Touch allows recording

**Comment by AlbrechtL** [comment]
What do you mean with recording? IQ RAW recordings or audio recordings?

**Comment by diddy12345** [comment]
audio recordings. I couldn't see much use recording the iq raw unless a user would want to record the whole mux but i dont think there is enough bandwidth to do that (6mhz)

**Comment by AlbrechtL** [comment]
Please see #239. You may can use welle-cli.

**Comment by AlbrechtL** [comment]
The general discussion about recording can he found here: #36
