### ISSUE TITLE
[Android] Building problem with QT 5.9

### ISSUE THREAD

**Issue by augustopicciani** [AlbrechtL/welle.io#288]
Hi, I'm trying to build Welle project using QT 5.9 and r17b as NDK but compiler give to me error like : 
C:\Users\Augusto\Documents\Projects\Android projects\Dab_Radio\welle.io\src\main.cpp:52: error: 'rep_CRadioController_replica.h' file not found

I followed usage here:
https://github.com/albrechtl/welle.io

Am I doing something wrong or do I need to know some other trick? 

Thanks in advance

**Comment by AlbrechtL** [comment]
Did you install the Qt package remote objects?

**Comment by AlbrechtL** [comment]
@augustopicciani Any updates?

**Comment by AlbrechtL** [comment]
Closed due inactivity.
