### ISSUE TITLE
"auto" language setting selects wrong language

### ISSUE THREAD

**Issue by snowflakeas** [AlbrechtL/welle.io#289]
Hi - first time user. My Win10 install is English (Norwegian keyboard). 
Welle autoinstalls as Norwegian (whereas having an English Version of Windows, I obviously want English as my language).

I cannot find the setting in the windows Registry either.

Possible to add query during install, or find another way to get language setting? 

I ended up changing the shortcut as follows:
"C:\Program Files (x86)\welle.io\welle-io.exe" --language en_EN

Edit: Nevermind - I see that SoapySDR is not supported under Windows, so I wouldn't be able to get my HW (LimeSDR) working anyway. Thanks for the nice looking app though!

**Comment by AlbrechtL** [comment]
How your other programs behaves?

Regarding LimeSDR: Your only option is to use Linux and to compile welle.io from source.

**Comment by mpbraendli** [comment]
Other topic: if you manage to get SoapySDR running on windows, please tell us how it's done in the wiki! But you will need to compile everything yourself with CMake. https://github.com/pothosware/SoapySDR/wiki/BuildGuide#windows

**Comment by snowflakeas** [comment]
I just ran the executable install from LimeSDR mini (myriad)
