### ISSUE TITLE
[Linux] Stream Name changes, unable to save settings (for example standard sink) in pulse audio

### ISSUE THREAD

**Issue by TinoLange** [AlbrechtL/welle.io#301]
Hi AlbrechtL,

Thanks so much for welle.io, I use it daily! It is a wonderful player.

One thing is annoying, though. As I want to hear music most of the time via my headset (and not via the standard speakers) I change the sink in pulse to that device.

Normally pulse is quite good in saving such personal preferences. For example the dedicated skype headset is saved permanently.

But for welle.io this does not get saved, as the stream name changes frequently - it seems to get every time a new name and that name even changes throughout the day suddenly, sometimes.

Attached a picture.

Could you please change welle.io so that its stream name is more stable?

Thanks

Tino
![randomname](https://user-images.githubusercontent.com/12817073/45472188-bc969380-b733-11e8-9fa6-7034eeef83d9.png)

**Comment by AlbrechtL** [comment]
Please see issue https://github.com/AlbrechtL/welle.io/issues/116.
