### ISSUE TITLE
Plots (Tiles) legend suggestions

### ISSUE THREAD

**Issue by stanroehrich** [AlbrechtL/welle.io#309]
Constellation Diagram:
Horizontal legend 'Subcarrier' is good but the scale number from 0 to 1200 is not corresponding to the real sub-carrier numbers. 

Impulse response Diagram:
Horizontal legend 'Frequency' is wrong. It can be  'samples /us/km'  (the ability to display microseconds or km is useful for such view)

notes: very nice tool ;)  /Best

**Comment by AlbrechtL** [comment]
Please post updated figures how it should be.

**Comment by mpbraendli** [comment]
CIR axis changed to "Samples" in c31208d

**Comment by mpbraendli** [comment]
It should be from -768 to 768 (that's the parameter `k` you also find in the spec)

But I've noticed that the x-values of the plot points do not correspond to `k` in any meaningful way. I will debug this.

**Comment by mpbraendli** [comment]
Constellation plot is improved a bit in 672abe6 but I have the impression there's still something wrong about the index calculation.

**Comment by mpbraendli** [comment]
@AlbrechtL is it easy to do a tooltip on the CIR plot that shows microseconds and km-equivalent of the x value (now `samples`), one that follows the mouse cursor and gets updated as you move the mouse? Is it possible to do that entirely in the QML?

Conversion is:
* `microseconds` = `samples` / 2.048
* `km` = `microseconds` × 3e5

**Comment by AlbrechtL** [comment]
I added a something in dc888e2f7daa6c7ea512de818cb7e2fe5198f166.

Dou you mean this?
![arbeitsflache 1_001](https://user-images.githubusercontent.com/11171787/47865140-b8195d80-ddfb-11e8-87c8-be631597ba00.png)

**Comment by mpbraendli** [comment]
Oh! Exactly! Awesome! Thanks a lot!

I will probably modify it s.t. 512 becomes zero, because that's where we actually place the FFT window.

**Comment by AlbrechtL** [comment]
I reintroduced this feature in https://github.com/AlbrechtL/welle.io/commit/f42c18c63ecb9291b2dd4f0ac8c3b8851037d6b2.
