### ISSUE TITLE
[Linux] No sound on  20181031_0321398_Linux_welle-io-x86_64.AppImage

### ISSUE THREAD

**Issue by erikdsgh** [AlbrechtL/welle.io#313]
Running on Ubuntu 16.04 LTS.
No sound.
Graphics show signal as usual but in Service Overview the message is:

0kbps, Stereo, DAB

No stations seem to be found; see screenshot  in appendix.
Previous version 20181031_672abe6_Linux_welle-io-x86_64.AppImage does not have that problem.
If more info is needed please send me instructions on how to obtain it.

**Comment by AlbrechtL** [comment]
That's interesting because we didn't change the sound interface.

**Comment by erikdsgh** [comment]
If more info can help you, please tell
      me what i should provide and how to obtain it.
      
      Best regards.
      
      Erik.
      ------------------------------------------
      
      Albrecht Lohofener wrote:
    
    
      That's interesting because we didn't change the sound
        interface.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/AlbrechtL/welle.io","title":"AlbrechtL/welle.io","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/AlbrechtL/welle.io"}},"updates":{"snippets":[{"icon":"PERSON","message":"@AlbrechtL in #313: That's interesting because we didn't change the sound interface."}],"action":{"name":"View Issue","url":"https://github.com/AlbrechtL/welle.io/issues/313#issuecomment-435101102"}}}
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/AlbrechtL/welle.io/issues/313#issuecomment-435101102",
"url": "https://github.com/AlbrechtL/welle.io/issues/313#issuecomment-435101102",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [AlbrechtL/welle.io] [Linux] No sound on  20181031_0321398_Linux_welle-io-x86_64.AppImage (#313)",
"sections": [
{
"text": "",
"activityTitle": "**Albrecht Lohofener**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@AlbrechtL",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"AlbrechtL/welle.io\",\n\"issueId\": 313,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"AlbrechtL/welle.io\",\n\"issueId\": 313\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/AlbrechtL/welle.io/issues/313#issuecomment-435101102"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 404281096\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by erikdsgh** [comment]
![screenshot from 2018-11-01 17-40-46](https://user-images.githubusercontent.com/43439613/47865895-b9e42080-ddfd-11e8-9faa-e589d87c86dd.png)

**Comment by erikdsgh** [comment]
Same problem with  20181101_dc888e2_Linux_welle-io-x86_64.AppImage

**Comment by erikdsgh** [comment]
Found the issue!
In the last 2 versions the backend section now has 'out of the box' the parameter coarse corrector disabled. This parameter is now called "Enable coarse corrector"

In the versions before the last 2 the parameter was "Disable coarse corrector" and was 'out of the box' not set.

Sorry for all the trouble.

**Comment by AlbrechtL** [comment]
Yes, I enabled the coarse corrector by default. Great that welle.io is working again for you!
