### ISSUE TITLE
[Linux] Fails to use RTL-SDR device

### ISSUE THREAD

**Issue by TheAssassin** [AlbrechtL/welle.io#320]
welle.io is unable to use my RTL-SDR receiver.

![screenshot_2018-11-11_19-31-00](https://user-images.githubusercontent.com/4503202/48316787-58d00000-e5e8-11e8-9ec1-b9498ba69078.png)

```
RTL_SDR: Open rtl-sdr
RTL_SDR: Found 1 devices. Uses the first working one

Kernel driver is active, or device is claimed by second instance of librtlsdr.
In the first case, please either detach or blacklist the kernel module
(dvb_usb_rtl28xxu), or enable automatic detaching at compile time.

usb_claim_interface error -6
RTL_SDR: Opening rtl-sdr failed
```

The device works fine with other applications like gqrx.

I'm using the AppImage.

**Comment by AlbrechtL** [comment]
Please try the latest [nightly build](https://bintray.com/albrechtl/welle.io/welle.io_nightly#files) please.

**Comment by AlbrechtL** [comment]
Duplicated, see here https://github.com/AlbrechtL/welle.io/issues/178

**Comment by TheAssassin** [comment]
With the nightly, I get the same error message as in #319. The device seems to work. When restoring the application from tray, the app crashed, though, and I had to plug the SDR device out and in again in order to make it work again.

**Comment by probonopd** [comment]
Try to run the AppImage as root, then search for stations. Worked for me indeed! (Despite the red error.)

**Comment by AlbrechtL** [comment]
The error message is a bug. It will be fixed in the near future.
