### ISSUE TITLE
[macOS] Program icon not linked into build?

### ISSUE THREAD

**Issue by schofiel** [AlbrechtL/welle.io#321]
Doing a first-time, clean build of welle from sources, QT5.9.7, on Mac OS X 10.11.6 (El Capitain).

Although I'm able to build with warnings, and the executable runs, the built binary does not show the  defined program icon in the Finder. Otherwise, the prog starts OK, shows the splash screen, shows the main screen, etc.

The icon is defined in welle.io.pro as:

RC_ICONS   =    icon.ico

- which corresponds to an apparently valid ICO file in the source tree.

However, unless there is some powerful magic going on that this noob is unaware of, this def is not referenced in any other rule in the makefile, and the compiled result just uses the default Mac OS program icon.

While I am going to do a bit of basic digging, anyone got any quick/simple insights?

**Comment by AlbrechtL** [comment]
Did you use the next branch?

**Comment by AlbrechtL** [comment]
Any progress here?

**Comment by mattes-bru** [comment]
I see the welle.io icon with macOS Mojave and Qt 5.12.0. I tried both, master and next branch

**Comment by AlbrechtL** [comment]
Thanks for testing. I think we can close it.
