### ISSUE TITLE
2.0 beta1 missing rtl_tcp connection options

### ISSUE THREAD

**Issue by dterweij** [AlbrechtL/welle.io#323]
Hello, the 2.0 beta 1 is missing rtl_tcp connection info. Also -h --help dont show rtl_tcp options anymore.

No support for it anymore? or is it just because its a beta?

**Comment by AlbrechtL** [comment]
You find these settings inside the GUI now.
![bildschirmfoto vom 2018-12-10 21-13-07](https://user-images.githubusercontent.com/11171787/49758913-73b59300-fcc0-11e8-9f1c-ca7d49492678.png)
