### ISSUE TITLE
[next] "Open RAW file" button has variable width

### ISSUE THREAD

**Issue by andimik** [AlbrechtL/welle.io#324]
When the filename is too long, there is no chance to set the format (auto/s8/u8 etc.) as there is no scroll bar.

But anyway it would be better, if the "Open RAW file" button had a fixed width.

![image](https://user-images.githubusercontent.com/24510556/49760510-f4768e00-fcc4-11e8-97e1-1a1177d788d8.png)

compared to

![image](https://user-images.githubusercontent.com/24510556/49760567-0fe19900-fcc5-11e8-9e4d-ad13fc4f7e66.png)

**Comment by AlbrechtL** [comment]
Thanks for reporting. Will be fixed soon.

**Comment by AlbrechtL** [comment]
Same for the expert settings (https://github.com/AlbrechtL/welle.io/pull/332).

**Comment by AlbrechtL** [comment]
Fixed in dc4d00801f8e467143064c0d473ba7d2774d76bd.
