### ISSUE TITLE
[next] Wrong icon after removing Service Overview

### ISSUE THREAD

**Issue by andimik** [AlbrechtL/welle.io#325]
When you remove the "Service Overview" and add it again, then the icon with the red, struck through transmitter says "no audio", although it's playing normally.

![image](https://user-images.githubusercontent.com/24510556/49762131-373a6500-fcc9-11e8-8afd-7bd8f6c699dc.png)

**Comment by AlbrechtL** [comment]
Thanks for reporting. Will be fixed soon.

**Comment by AlbrechtL** [comment]
Fixed in https://github.com/AlbrechtL/welle.io/commit/30c322221e91e8ed03c7c76ddc4c5bb0c996a893.
