### ISSUE TITLE
[macOS] Files from a macOS build

### ISSUE THREAD

**Issue by Observerist** [AlbrechtL/welle.io#327]
Once with a build macOS in my hands ( I'm still on v.1.0 rc1 ), is welle "movable ? I wanted to copy the elements to another, newer Macbook Pro without having to go through the pain of rebuilding the whole app. What do I have to "take with me" and where should the elements/dependencies reside ?

Since I just saw that v.2.0 beta 1 is out, I might go for another couple of hours of (painful for me) build time ro see the changed GUI, but before that, I would like to do this transfer. 
( will there be another welle.io page with screenshots of the new GUI ? )

Has the idea of an macOS installer been abandoned by the person who last year offered to do it ?

**Comment by Observerist** [comment]
To upgrade from rc1 to final v.1, do I have on macOS to rebuild everything from scratch ?

**Comment by Observerist** [comment]
Went through the whole Qt Creator routine, everything went green-lighted up until the end where I got one red alarm :
![screen shot 2018-12-21 at 21 11 49](https://user-images.githubusercontent.com/45834366/50362711-0976db00-0569-11e9-8cac-a558508fc88b.jpeg)

Any idea where to go from here ?

welle was correctly cloned from github via the terminal.

**Comment by gvanem** [comment]
It's in `src/libs/mpg123/mpg123.h`.  Maybe `-I./src/libs/mpg123` is not in your `CFLAGS`?

**Comment by Observerist** [comment]
Have been looking into the folders of my actual working build.
Don't see any of these files. 
Sorry, I'm not used to "build" anything, neither through MacPorts nor Homebrew. 
My actual build was retrieved last year through MacPorts and build with QT creator 5.10.
Works fine, but I wanted to update from this old rc1 to the final release version.

![screen shot 2018-12-21 at 23 29 55](https://user-images.githubusercontent.com/45834366/50366173-7b0a5580-0578-11e9-9684-9888393210d3.jpeg)

**Comment by Observerist** [comment]
Where does CFLAGS reside ??

**Comment by gvanem** [comment]
Depends on how you're compiling. Normally `CFLAGS` refers to the arguments passed to the C/C++ compiler. Your mileage may vary.

**Comment by Observerist** [comment]
Ok, now you lost me. 

Thank you so much for trying to send me into the right direction, but I feel like a first grade student listening to a language that's not mine. Sorry sorry sorry.
I'm a professional in the Film & Video Production business, not a programmer.

Just trying to enjoy a great DAB+ app on my MacbookPro.
Did follow the instructions from the main page   https://github.com/AlbrechtL/welle.io  
Went through MacPorts since I already used it when GQRX had still no DMG installer.
Everything related to compiling or C/C++ languages is another universe out of my reach.

I will patiently wait then, until perhaps, possibly, anyone creates an installer for welle. For now, I'll keep this old rc1 version alive and do my other DAB listening with my little Sonys.

Thank you Gisle for at least trying to help me out here. 
Since the demise of the forum, it has become very difficult to get any assistance. Especially for people like me who have no programming, compiling, building skills.

Merry Xmas, Happy Holidays

**Comment by AlbrechtL** [comment]
> Has the idea of an macOS installer been abandoned by the person who last year offered to do it ?

Unfortunately I didn't receive any installer.

@Observerist How did you get 1.0 rc1?

**Comment by Observerist** [comment]
Hallo Albrecht, 
    
    Hatte die rc1 mit Hilfe der Anleitungen die ich auf dieser Seite
    fand zusammengebastelt. https://github.com/AlbrechtL/welle.io
    Da gab es nichts anderes als diese version, eine Wahl hatte ich
    dabei nicht.
    
    Hab die Macports Methode ausgewählt, weil ich damit schon mal GQRX
    ins Leben brachte, als es dafür noch keinen .dmg Installer gab.
    
    Weil ich so ein unbegabter "builder" bin, werde ich mal brav
    abwarten bis die v2.0 offiziell die v1.0 ablöst.
    Die rc1 läuft eigentlich ganz gut auf meinem Macbook Pro, auch wenn
    ich jetzt nicht weiß, was ich verpasse.
    Gibt es denn irgendwo schon ein Screenshot der neuen v.2.0 GUI ?
    
    
    Allerbeste Grüße aus Paris, ein frohes Neues Jahr und viel Erfolg, 
    
    alex
    
    
    
    On 27/12/2018 09:20, Albrecht Lohofener
      wrote:
    
    
      
      
        Has the idea of an macOS installer been abandoned by the
          person who last year offered to do it ?
      
      Unfortunately I didn't receive any installer.
      @Observerist
        How did you get 1.0 rc1?
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or mute the thread.
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/AlbrechtL/welle.io","title":"AlbrechtL/welle.io","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/AlbrechtL/welle.io"}},"updates":{"snippets":[{"icon":"PERSON","message":"@AlbrechtL in #327: \u003e Has the idea of an macOS installer been abandoned by the person who last year offered to do it ?\r\n\r\nUnfortunately I didn't receive any installer.\r\n\r\n@Observerist How did you get 1.0 rc1? "}],"action":{"name":"View Issue","url":"https://github.com/AlbrechtL/welle.io/issues/327#issuecomment-450101530"}}}
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/AlbrechtL/welle.io/issues/327#issuecomment-450101530",
"url": "https://github.com/AlbrechtL/welle.io/issues/327#issuecomment-450101530",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by AlbrechtL** [comment]
Thanks for pointing this out! The description needs to be updated by someone with a Mac. I opened a new issue for that (see https://github.com/AlbrechtL/welle.io/issues/333).

For now I'm closing this issue.
