### ISSUE TITLE
[rtl-tcp] 2.0 Beta 1: Message "ADB overload. Maybe you are using a to high gain" troubles

### ISSUE THREAD

**Issue by lars18th** [AlbrechtL/welle.io#328]
Hi,

I tested new Beta 1 in Windows. With RTL_SDR *and* RTL_TCP.
With the last (rtl_tcp) I found a lot of problems:

1. The message "ADB overload. Maybe you are using a to high gain." when poor signal, is showing _million_ of times! Please, only write 1 message every 5 or 10 seconds, no more!
2. This message appears with RTL_TCP and not with RTL_SDR, using the same tuner. It's this a bug?
3. I can't see in the GUI any indication about the TCP connection status. Please, add some feedback about the connection (for example: green connected; yellow: connecting; red: disconnected).

In any case, the new UI is great.
Thank you!

**Comment by AlbrechtL** [comment]
I'm closing this issue because I'm not sure if it is still relevant. If it still occurs in the latest version, we can reopen it.
