### ISSUE TITLE
[airspy] AGC failed for strong signals

### ISSUE THREAD

**Issue by AlbrechtL** [AlbrechtL/welle.io#33]
The implemented AGC failed for strong field signals.

**Comment by AlbrechtL** [comment]
I asked the airspy developer how to implement an AGC. 
Answer:
> It's not as simple as it seems. The optimal gain depends on the nature of the signal, its bandwidth and the ratio between its bandwidth and the sample rate.
> I would increase the gain in Airspy until the BER no longer improves. That's more reliable in your case.
>

**Comment by mpbraendli** [comment]
Commit 7812607 adds an AGC that is better than nothing. As for Soapy and RTLSDR, the AGC only considers sample amplitude.
