### ISSUE TITLE
[Linux, i3] welle.io_2.0-Beta1_Linux_x86_64.AppImage won't exit correctly

### ISSUE THREAD

**Issue by flux242** [AlbrechtL/welle.io#334]
when gui is closed apprun would continue to work

**Comment by AlbrechtL** [comment]
Thanks for reporting!

What do you mean with "apprun"?

**Comment by flux242** [comment]
when the main window is closed the application keeps running. To close it one would need to interact with a small icon. Why is that? Why can't one just close it by closing the main window? AppRun is the main process that is started in an appimage container. Check AppImage for details

**Comment by AlbrechtL** [comment]
What do you mean with "small icon"?
Please try it again with the latest nightly (I fixed a crash bug while closing).

**Comment by flux242** [comment]
"small icon" is an image with limited pixel resolution along both axis. "Small" in this context means that it covers very small portion of the whole visible display area. Please make it possible to terminate the process without the need to interact with a small systray icon

**Comment by AlbrechtL** [comment]
I don't quite understand the issue. If you close the application by the X then it stops running. If you minimize the the program then you have to deal with the icon.

**Comment by flux242** [comment]
well if started under xfce de then it works as you describe above. But I'm using i3 window manager and it doesn't work as described. If I close the window then it minimizes itself instead of terminating the process. It worked correctly before 2.0 (where I believe the systray icon was added)

**Comment by AlbrechtL** [comment]
It sounds like an issue with i3. I suggest to ask the i3 developers what's going wrong. Under KDE and GNOME it is working correctly.
