### ISSUE TITLE
Welle V2 beta does not start with options -d rtl_tcp --rtl_tcp-address YourIP --rtl_tcp-port YourPort

### ISSUE THREAD

**Issue by hubertmeier** [AlbrechtL/welle.io#339]
It's perhaps not an error because Welle 2 is in beta status and not ready. I wanted to test Welle 2 on a Windows PC with a raspberry and an RTL-SDR running rtl_tcp.

In the documentation i found: Welle.exe -d rtl_tcp --rtl_tcp-address YourIP --rtl_tcp-port YourPort

but this does not work. Welle V1 is not installed anymore because the beta runs fine !

Thank you

**Comment by AlbrechtL** [comment]
The docs is outdated. Now you find these settings inside the GUI, see here https://github.com/AlbrechtL/welle.io/issues/323.
