### ISSUE TITLE
Support for HD Radio

### ISSUE THREAD

**Issue by andybochmann** [AlbrechtL/welle.io#340]
Theori recently developed a HD Radio decoder for rtl-sdr, see https://github.com/theori-io/nrsc5
It would be great, if support for this could be added to welle.io, for people living in the U.S.

**Comment by AlbrechtL** [comment]
Thanks for the hint. You your welcome to add HD radio support to welle.io.

**Comment by andimik** [comment]
I would suggest to close this feature request as there is no progress.

**Comment by AlbrechtL** [comment]
Agreed!

If somebody from the US needs HD Radio support we can reopen this issue.
