### ISSUE TITLE
NooElec R820T SDR & DVB-T no channels found

### ISSUE THREAD

**Issue by Nullstr1ng** [AlbrechtL/welle.io#344]
I have NooElect R820T SDR & DVB-T NESDR Mini USB kit and welle.io did not find any channel. It was scanning alright even if the driver auto detect is enabled or disabled by using RTL-SDR option, but still, no channels found.

I tried using SDR# and set the frequency  to our Digital TV freq signal and the signal was there 

here's the sample.
![image](https://user-images.githubusercontent.com/260633/52171636-50c4ce00-279b-11e9-892f-d9145a05ad40.png)

Here's the exact model of what I'm using
https://www.youtube.com/watch?v=9lZLKa7QWKY
(video not mine)

**Comment by andimik** [comment]
If this is channel 43 (650 MHz) then I wonder why your screenshot starts at 644 MHz and not at 646 MHz as the DVB-T or T2 is 8 MHz, not 10 MHz.

Can you post a screenshot from you VHF DAB Signal.

I fear your dongle has a big offset.

**Comment by andimik** [comment]
🇵🇭?

There are no DAB transmissions there. So you seem not to have understood the purpose of welle.io.

https://www.worlddab.org/country-information

**Comment by Nullstr1ng** [comment]
Yes, Philippines.

Sorry, I am very new to this one. Do you have any suggestions what software I can use to play Digital TV channels from my device?

**Comment by andimik** [comment]
You need to install the original driver as you use the dongle as SDR.

But please ask someone from your country. All countries in Europe use DVB-T or DVB-T2.

The Philippines use the Japanese standard. So we cannot help you at all.

https://en.m.wikipedia.org/wiki/ISDB#ISDB-T
