### ISSUE TITLE
[next] Rawfile: stations not found

### ISSUE THREAD

**Issue by andimik** [AlbrechtL/welle.io#348]
I'm using latest nightly build under Windows 10 (as I cannot start it under Kubuntu, see other issue).

But it seems the programm does not correctly detect services from RAW file (I cannot test it with a DAB signal on VHF here).

![screenshot 30](https://user-images.githubusercontent.com/24510556/52748261-5960a400-2fe6-11e9-9867-40e229c91bcd.png)

![screenshot 31](https://user-images.githubusercontent.com/24510556/52748386-af354c00-2fe6-11e9-98cb-6e7fe968a1d8.png)

![screenshot 32](https://user-images.githubusercontent.com/24510556/52748551-19e68780-2fe7-11e9-94b4-0571056478f0.png)

![screenshot 33](https://user-images.githubusercontent.com/24510556/52748682-7053c600-2fe7-11e9-96c5-23000205b49d.png)

![screenshot 34](https://user-images.githubusercontent.com/24510556/52748864-efe19500-2fe7-11e9-962a-e7ff60149fea.png)

Tried lots of files from all over Europe, 
both u8 and s16be file formats, 
both DAB and DAB+, 
both containing Data streams and not.

Remark: The last one is the file `sample_sync_lost.iq` from https://github.com/AlbrechtL/welle.io/issues/247

I only can tune to a station having detected its label.

**Comment by AlbrechtL** [comment]
Thanks for reporting.
The issue came in between 60626a86a8eabe799755554f387b0922f05ea6e5 and ac629326c6fe5bcfb9f0464dd34eafb71f8451b6.

We are working on a fix.

**Comment by mpbraendli** [comment]
Should be fixed in 9fe93d1.

**Comment by AlbrechtL** [comment]
One more fix in 1fa670a04e2c8628e8770cca246df02a9e82905e.
