### ISSUE TITLE
[welle-cli] channel switching bug

### ISSUE THREAD

**Issue by AurelienPicart** [AlbrechtL/welle.io#351]
Sometimes appear reception beug when i change channel. Look like no acces to RTLSDR dongle (0 db ). So i have to shutdown and restart welle.io server. I use welle.io with supervisor.

**Comment by mpbraendli** [comment]
Thanks for reporting the issue, you were not the first to complain about such behaviour, but I wasn't able to reproduce it until today. It occurs when the channel is switched several times rapidly.

Commit 17bbdc8 fixes this problem. Please update and let me know if it works.

If the issue persists, please open this ticket again. Thanks!
