### ISSUE TITLE
[Linux, VirtualBox] No text in GUI when video memory is to low

### ISSUE THREAD

**Issue by deltafox1002** [AlbrechtL/welle.io#353]
When I start the App (appimage File) it show the frame but no text. System is Linux Mint 19.1 Cinnamon.

**Comment by AlbrechtL** [comment]
Please post a screen shot and the console output.

**Comment by AlbrechtL** [comment]
Any news here?

**Comment by cryptik** [comment]
I have a similar issue.  The application finds the RTL_SDR and it appears to be working correctly, but the GUI is blank (for the most part).  Here is a screenshot of the GUI as well as the console window.  I get the same results running the appimage as well as building it with QtCreator.

When building the app, I could not find Qt5.10 so I built it with Qt5.11... Qt5.12 also produces the same results.

![gui](https://user-images.githubusercontent.com/1165640/63560323-8e185f80-c523-11e9-8c49-8c45e9c368ae.png)
![console](https://user-images.githubusercontent.com/1165640/63560326-91abe680-c523-11e9-9a6c-88411fb9faaa.png)

**Comment by cryptik** [comment]
I see the warnings regarding visibility and the createObject issue.  I don't know Qt very well...but I will try and look into it more.  It must be some issue between Qt and Ubuntu 18.04 or maybe Qt 5.11.  It does not appear to be a common issue.

**Comment by cryptik** [comment]
Just for completeness, this is what the display looks like now...after increasing the amount of video memory assigned:

![app](https://user-images.githubusercontent.com/1165640/63594328-28a88b00-c584-11e9-8d9c-a5b03d9c6807.png)

The console is reporting an "Info: ofdm-processor: SyncOnNull failed" when running a station scan, but I imagine this is what it says, and info message.

![console](https://user-images.githubusercontent.com/1165640/63594370-47a71d00-c584-11e9-882f-5996bfcf8cad.png)

**Comment by AlbrechtL** [comment]
Thanks for the update and the analysis!
