### ISSUE TITLE
[Windows] terrible gui Windows 7

### ISSUE THREAD

**Issue by sstvmaster** [AlbrechtL/welle.io#354]
see attachment, win7 32bit, Intel GM45 graphics.
![welle io2](https://user-images.githubusercontent.com/19416108/53698876-b62fcd00-3de2-11e9-8410-193e9ec34a80.jpg)

**Comment by AlbrechtL** [comment]
It seems that there is an issue with the graphic driver. But we don't support Windows 7 anymore so we can't help you. Sorry!
