### ISSUE TITLE
Welle-cli stream - embed metadata

### ISSUE THREAD

**Issue by LeoSchleicher** [AlbrechtL/welle.io#357]
By other streaming services images and texts can be placed in streams metadata (mp3-metatags?) is it by welle-cli streams also possible? this can help by using welle with different clients.

**Comment by mpbraendli** [comment]
I don't know mp3 metadata support well, but since we use `lame` for encoding, we could use its metadata features. Currently we don't insert any metadata into the mp3 streams.
