### ISSUE TITLE
[welle-cli] 'sig_caught' was not declared in this scope if HAVE_SIGACTION is not defined

### ISSUE THREAD

**Issue by AlbrechtL** [AlbrechtL/welle.io#358]
If HAVE_SIGACTION is not defined then the the variable `sig_caught` is not declared which results in a compiler error.

https://github.com/AlbrechtL/welle.io/blob/4061aa14937bfcdbc4b62b48c492733dabd90fd7/src/welle-cli/webradiointerface.cpp#L1333

`sig_caught` is declared in L1313
https://github.com/AlbrechtL/welle.io/blob/4061aa14937bfcdbc4b62b48c492733dabd90fd7/src/welle-cli/webradiointerface.cpp#L1312-L1318

**Comment by mpbraendli** [comment]
Ah, yes... :-/

Fixed in cbb68f2

**Comment by AlbrechtL** [comment]
Thanks!
