### ISSUE TITLE
[Suggestion] add a simple "recording" function

### ISSUE THREAD

**Issue by Wikinaut** [AlbrechtL/welle.io#36]
Perhaps this can be useful, now and then, to start and stop audio recording.

**Comment by Wikinaut** [comment]
I "want" to have a record button in "welle.io", and transcoding to mp3 (in reasonable user-definable quality) would be fine, and I want to record *as* I listen.

**Comment by AlbrechtL** [comment]
I don't see a real improvement to add this feature. You can do the same with a virtual sound card and some specific transcode applications.
It adds just a little bit more usability for this use case but creates a lot of work to develop and maintain it. I also think that regular users don't need this feature.

**Comment by lars18th** [comment]
Hi,

Only as a _reference_: If you need to **RECORD the IQ samples**, you can use another tool: "QIRX SDR" or the good known "qtdab". See more at: http://www.welle.io/devices/rawfile#odr-dabmod

Regards!
