### ISSUE TITLE
[rtl-sdr] Multiple receivers

### ISSUE THREAD

**Issue by EPO35F** [AlbrechtL/welle.io#360]
Hello, I have installed to receivers, start 2 welle-io.exe, and only the first one works.
Any hints how to have several ones working ?
I am mainly interested by the data within DAB
I have Nooelec receiver and RTLSDR RTL2832U V3 ones

**Comment by AlbrechtL** [comment]
Welle.io uses automatically the first device. Which is the use cases use two devices at the same time?

**Comment by ariendj** [comment]
> Welle.io uses automatically the first device. Which is the use cases use two devices at the same time?

I'd like to run one Welle.io web interface for every mux that I can receive. This way I'd be able to stream any number of DAB channels I receive to any number of network devices.

Also I want to try and pass complete DAB muxes to TVHeadend. This would allow listening, recording and timeshifting any number of DAB channels on my multiple Kodi frontends.

**Comment by AlbrechtL** [comment]
If you like you can start implementing these features. We are always open for pull request.

**Comment by AlbrechtL** [comment]
Closed because it is duplicated. See issue https://github.com/AlbrechtL/welle.io/issues/95 please.
