### ISSUE TITLE
Removal of QT HMI

### ISSUE THREAD

**Issue by EPO35F** [AlbrechtL/welle.io#361]
By what do you want to replace it ?

**Comment by AlbrechtL** [comment]
I don't understand the question. Do you ask that we remove the Qt GUI?

**Comment by EPO35F** [comment]
_Currently ongoing
    All the tasks in the next project
    Better separation between GUI and backend. Removal of QT from the backend. **Write a frontend without QT** that permit writing automated tests. See https://github.com/mpbraendli/welle.io/tree/removeQtFromBackend and the corresponding TODO list_

**Comment by mpbraendli** [comment]
I added a frontend without QT (welle-cli), but I didn't remove the welle.io QT frontend.

I believe this was just a misunderstanding.
