### ISSUE TITLE
[Linux] Remove hide() when running on Gnome Desktop

### ISSUE THREAD

**Issue by meeuw** [AlbrechtL/welle.io#367]
Hi, I actually don't know how to fix this properly but Gnome Desktop doesn't have a "System Tray" and when welle.io's main window is minimized it's impossible to open the window again (because it's hidden from the "taskbar").

This can be disabled by removing `onMinimizeWindow: hide()` from `src/welle-gui/QML/MainView.qml` but that would kill the user experience for users with a System Tray.

The best suggestion I can think of is to only hide the main window when the welle.io icon is clicked in the system tray.

**Comment by AlbrechtL** [comment]
Good point.

The best would be if Qt can detect during run time if there is a sys tray. Can you check if Qt provides a API for this?

**Comment by meeuw** [comment]
Hmm not so sure if there is an Qt API. I would settle for checking the environment variable `DESKTOP_SESSION` and if it's set to `"gnome"` don't hide the window.

**Comment by AlbrechtL** [comment]
Good idea with the environment variables.

The things are a little bit more complicated. I'm using Ubuntu with it's Gnome variant and a system tray.

**Comment by meeuw** [comment]
Hmm, seems there's a Qt API after all...

I've created the following test:
```c++
#include <QtWidgets/QSystemTrayIcon>
#include <QtWidgets/QApplication>

int main(int argc, char **argv) {
    QApplication a(argc, argv);
    printf("QSystemTrayIcon::isSystemTrayAvailable: %i\n", QSystemTrayIcon::isSystemTrayAvailable());
}
```

```bash
g++ main.cpp -I/usr/include/qt5/ -fPIC -lQt5Core -lQt5Widgets ; ./a.out
```

outputs:
```
$ g++ main.cpp -I/usr/include/qt5/ -fPIC -lQt5Core -lQt5Widgets ; ./a.out 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSystemTrayIcon::isSystemTrayAvailable: 0
```

Could you test this on your system?

**Comment by AlbrechtL** [comment]
Thanks for figuring this out.

I added this into https://github.com/AlbrechtL/welle.io/commit/426331163e4509302203495aebfe07eb1fb07acd.
https://github.com/AlbrechtL/welle.io/blob/426331163e4509302203495aebfe07eb1fb07acd/src/welle-gui/gui_helper.cpp#L246-L253

Please test the latest nightly build or build it from the next branch.

**Comment by meeuw** [comment]
:+1: works for me!
