### ISSUE TITLE
Hot key support

### ISSUE THREAD

**Issue by joural** [AlbrechtL/welle.io#368]
I'd like to change between stations/ channels with rotary encoder, is there some way I could implement this in welle?

**Comment by AlbrechtL** [comment]
Can you describe your project more in detail please?

**Comment by joural** [comment]
Yeah replace car radio with rpi running open auto where welle.io is included, have one rotary encoder for volume control and other to simulate tunning

**Comment by joural** [comment]
If there would be keys to play next/ previous station I think I could simulate keypresses with python script

**Comment by jay-to-the-dee** [comment]
Tbf, up/down or left/right arrow key channel navigation would be pretty intuitive and useful in the Qt GUI. Maybe PgUp/PageDown could change mux? That's a similar principle to how my car DAB radio does it.

**Comment by AlbrechtL** [comment]
I think @joural and @jay-to-the-dee you are mentioned two different things.
1. The question is how to implemented an interface to control welle.io remotely
2. Hot keys

I think the hot keys could be interesting feature for a future version. The remote interface is a little bit to specialized.

**Comment by joural** [comment]
Hot keys is fine, I'm looking forward to future version. Shall I close the issue, or leave it open? Thank you

**Comment by jay-to-the-dee** [comment]
@AlbrechtL hot keys sounds like it would be useful for us both then :)

**Comment by AlbrechtL** [comment]
To implement hot key makes sense. For that reason I leave this ticket open. Please keep in mind that the priority is low for the feature request. But we are open for pull requests!

**Comment by AlbrechtL** [comment]
To remote control welle.io I'm thinking of implementing a JSON API (https://doc.qt.io/qt-5/json.html) via TCP.
What do you think?

**Comment by joural** [comment]
That would work for me 👍

**Comment by tenzap** [comment]
For now you have some hotkey support in next (see #628 for details). Shortcuts are also in the README of next

**Comment by AlbrechtL** [comment]
I'm closing this issue because https://github.com/AlbrechtL/welle.io/pull/628 is merged.
