### ISSUE TITLE
[Suggestion] add a command line start parameter to start playing a certain station

### ISSUE THREAD

**Issue by Wikinaut** [AlbrechtL/welle.io#37]
[Suggestion] add a command line start parameter to start playing a certain station.

**Comment by AlbrechtL** [comment]
Can you explain a little bit more why you need this feature?

**Comment by Wikinaut** [comment]
I want to have a shortcut on my Linux desktop which when clicked starts playing "DeutschlandradioKultur".

**Comment by AlbrechtL** [comment]
I agree that a feature is needed that starts the playing automatically. But I'm not sure if a command line option is a perfect approach.

**Comment by Wikinaut** [comment]
Several shortcuts: a use of an ini file, for example, would not allow to have several shortcuts with different stations.

**Comment by AlbrechtL** [comment]
I added your request to the [task list](https://github.com/AlbrechtL/welle.io/wiki/Open-Tasks).
If more people needs this feature they can write it here.
