### ISSUE TITLE
[rtl-sdr] Recommended antenna 

### ISSUE THREAD

**Issue by Thore-Krug** [AlbrechtL/welle.io#376]
Hi, 

i have a setup with a rtl sdr and working RTL SDR it works with gqrx but not with welle.io i assume the antenna causes the trouble. Is a Special antenna recommended ?

**Comment by AlbrechtL** [comment]
Which SNR do you have? Inside the expert mode you will find the value. There can also check the spectrum.

**Comment by AlbrechtL** [comment]
Closed because of inactivity.
