### ISSUE TITLE
[Linux] Compiling Problems  lame/lame.h and other libraries not found error

### ISSUE THREAD

**Issue by Saadi2015** [AlbrechtL/welle.io#379]
In file included from ../../../welle.io/src/welle-cli/webprogrammehandler.cpp:25:0:

../../../welle.io/src/welle-cli/webprogrammehandler.h:29:23: fatal error: lame/lame.h: No such file or directory

compilation terminated.

/home/saadi/raspi/gcc-linaro-5.5.0-2017.10-x86_64_arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/5.5.0/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lfftw3f

/home/saadi/raspi/gcc-linaro-5.5.0-2017.10-x86_64_arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/5.5.0/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lfaad

/home/saadi/raspi/gcc-linaro-5.5.0-2017.10-x86_64_arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/5.5.0/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lmp3lame

/home/saadi/raspi/gcc-linaro-5.5.0-2017.10-x86_64_arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/5.5.0/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lmpg123

/home/saadi/raspi/gcc-linaro-5.5.0-2017.10-x86_64_arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/5.5.0/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lairspy

/home/saadi/raspi/gcc-linaro-5.5.0-2017.10-x86_64_arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/5.5.0/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lrtlsdr

/home/saadi/raspi/gcc-linaro-5.5.0-2017.10-x86_64_arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/5.5.0/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lSoapySDR

collect2: error: ld returned 1 exit status
![unnamed2](https://user-images.githubusercontent.com/10408714/61474106-29983c80-a988-11e9-87d4-dda3d08aa3bd.png)
![unnamed](https://user-images.githubusercontent.com/10408714/61474107-2a30d300-a988-11e9-9772-5bd54bcc7189.png)

**Comment by AlbrechtL** [comment]
Did you follow the instructions on https://github.com/AlbrechtL/welle.io#ubuntu-linux-1804-lts?

**Comment by Saadi2015** [comment]
Hello Albrecht,

yes I did follow the description you linked on ubuntu-16.04.4 and Raspbian Buster..
Can I compile it on Raspbian directly without cross-compilation?
How do I do that ?


Thanks for the fast reply!

**Comment by AlbrechtL** [comment]
Any updates here?

**Comment by Saadi2015** [comment]
I still did not have any time to try it out, but I will post updates, when I'll come to it.
