### ISSUE TITLE
[macOS] Missing station info / radiotext etc

### ISSUE THREAD

**Issue by marrem** [AlbrechtL/welle.io#381]
I'm on MacOS 10.14.6.
I managed to build the project. It scans and tunes perfectly.
But the window is rather empty. I doesn't show all the station information I see here:

https://www.welle.io/

Mine looks like:
[
<img width="877" alt="welle" src="https://user-images.githubusercontent.com/2941173/62012084-d8efc300-b181-11e9-8dda-f05ae77e3f3b.png">
](url)

**Comment by AlbrechtL** [comment]
Can you post the command line output, please?

**Comment by AlbrechtL** [comment]
Can you try the latest version from the next branch please?

I fixed a bug in https://github.com/AlbrechtL/welle.io/commit/3e74e70c0c73713de29f6de39dcc9bd0b1f041d6 and I would like to know if this was your issue.

**Comment by marrem** [comment]
I have just built the 'next' branch which contains the mentioned commit. I has built correctly. I am currently on holiday in France. I'm in a small village 'in the middle of nowhere'. No DAB stations here... The screen looks more promising. I can enable 'expert settings' and add a few windows, like 'spectrum', etc.

<img width="906" alt="screenshot welle build 7fc94a20" src="https://user-images.githubusercontent.com/2941173/62863640-ab6e5200-bd09-11e9-9527-86a946fb230b.png">

When I'm back home in the Netherlands next week I'll give it a try and keep you posted.

**Comment by AlbrechtL** [comment]
Great!
I'm closing this issue for now.

**Comment by marrem** [comment]
At home now. In Den Haag, Netherlands. Everything works fine now!

Marc

**Comment by AlbrechtL** [comment]
Thanks for the feedback!
