### ISSUE TITLE
When setting a station as favorite (same name on 2 channels) the first is selected even if I click the 2nd

### ISSUE THREAD

**Issue by tenzap** [AlbrechtL/welle.io#386]
In my setup, I have some stations that have the same name although they are each in a different channel. For example :

SWR2 on 8D and SWR2 on 9D
When I click on the "favorite" icon of the 2nd in the list, it is the first one that actually gets selected (ie the star becomes yellow). I expected the station I clicked to become yellow, not the 1st having the exact same name (but on another channel)

This is on linux with v2.0 Beta 2 (appimage)

**Comment by AlbrechtL** [comment]
Thanks for reporting.

**Comment by tenzap** [comment]
Fixed by PR #417

**Comment by AlbrechtL** [comment]
Thanks!
