### ISSUE TITLE
New french translation

### ISSUE THREAD

**Issue by tenzap** [AlbrechtL/welle.io#388]
Hello,

Please fin attached a new french translation for 2.0-beta2

[fr_FR.tar.gz](https://github.com/AlbrechtL/welle.io/files/3505208/fr_FR.tar.gz)

Could you also update the GUI to add that translation in the dropdown list of the settings ?

Thanks

**Comment by tenzap** [comment]
Please consider this new version which carries the standardized french translations of the programme type codes according to the "ETSI TS 101 756 V2.2.1 (2017-08) (page 23)"

[fr_FR-v2.tar.gz](https://github.com/AlbrechtL/welle.io/files/3505387/fr_FR-v2.tar.gz)

**Comment by AlbrechtL** [comment]
Thanks for the translation. Please open a pull request for it.

**Comment by tenzap** [comment]
I can provide a patch if you prefer, but no pull request sorry.

**Comment by AlbrechtL** [comment]
I really would like to add your translation into welle.io.

The process to do it is via pull requests. They are easy to create and easy to handle. For more information about pull request read the [guide](https://help.github.com/en/articles/about-pull-requests), please.

**Comment by tenzap** [comment]
It seems one needs both .ts & .qm
[fr_FRwithQm.tar.gz](https://github.com/AlbrechtL/welle.io/files/3583930/fr_FRwithQm.tar.gz)

**Comment by AlbrechtL** [comment]
Please use a pull request to send your patch.

**Comment by tenzap** [comment]
here you have. I'm happy it was possible to do this only with the browser
https://github.com/tenzap/welle.io/pull/1

**Comment by AlbrechtL** [comment]
Great thanks!
You have to make the pull request on this repository not your fork. Please try it again :-)

**Comment by tenzap** [comment]
New try here: https://github.com/AlbrechtL/welle.io/pull/400

**Comment by AlbrechtL** [comment]
Thanks!
