### ISSUE TITLE
dabdate command line tool

### ISSUE THREAD

**Issue by alexmyczko** [AlbrechtL/welle.io#393]
Hi

There's a tool dvbdate from dvb-apps (Switzerland stopped DVB-T and does not provide DVB-T2), how hard would it be to create dabdate printing date+time gotten via rtlsdr device?

There are a few people that'd like to get the time from the air, without internet. I'm one of them.

Best,

**Comment by AlbrechtL** [comment]
Interesting idea to use DAB to get a date and time. What is the use case to use DAB or DVB rather than DCF77?

**Comment by andimik** [comment]
Indeed, it's an interesting idea.

But you get the exact time when you plug in a GPS mouse (some models are even supported by the kernel).

**Comment by alexmyczko** [comment]
77.5 khz is not the cheap rtlsdr range...

**Comment by mpbraendli** [comment]
When you use welle-cli in webserver-mode, you can retrieve the JSON data, which includes UTC time.

**Comment by alexmyczko** [comment]
> When you use welle-cli in webserver-mode, you can retrieve the JSON data, which includes UTC time.

@mpbraendli any chance of creating a simple shell script example for inclusion and usage?

**Comment by mpbraendli** [comment]
Very low chance, as I don't need this myself. Try combining wget or curl to fetch the `mux.json` with [jq](https://stedolan.github.io/jq/) to filter out the UTC time.

**Comment by alexmyczko** [comment]
Okay this is what I came up with: 

`printf "%02d %02d %04d %02d:%02d:$(date +%S) UTC\n" $(curl -s http://localhost:7979/mux.json |gron |grep utctime |gron -u | python3 -c "import json,sys;obj=json.load(sys.stdin);print (obj['utctime']['day'], obj['utctime']['month'], obj['utctime']['year'], str(obj['utctime']['hour'])+' '+str(obj['utctime']['minutes']));")`

**Comment by gvanem** [comment]
What does `gron` do?
