### ISSUE TITLE
RTL_SDR:Setting gain failed

### ISSUE THREAD

**Issue by tenzap** [AlbrechtL/welle.io#402]
In the log I often have these errors:
```

rtlsdr_demod_write_reg failed with -9
r82xx_write: i2c wr failed=-9 reg=05 len=1
2019-09-15T21:46:09.766 Info: RTL_SDR:Setting gain failed
```

By looking around, if try to modify the code so that it calls the faulty "rtlsdr_set_tuner_gain" (from rtl-sdr.cpp) a second time, it seems to work.
Could this be related to the fact that this is called while we are in a rtlsdr_read_async
(like the same error in the case we call rtlsdr_set_center_freq while not having cancelled the rtlsdr_read_async)

This message sometimes appears many times in the log, even when only playing a station.
It also appears when scanning

**Comment by tenzap** [comment]
This seems to happen only if the active antenna is on and amplifies the signal

**Comment by AlbrechtL** [comment]
I also saw it sometimes at the logs from other users. In my case I never experienced it.

What you can do is just looking to the source code of other rtl-sdr open source programs. Maybe they did something different than we do.

**Comment by AlbrechtL** [comment]
The messages `r82xx_write: i2c wr failed=-9 reg=05 len=1` are looking to me for a hardware issue.
