### ISSUE TITLE
"Ensemble" of the station is not shown in the service overview

### ISSUE THREAD

**Issue by tenzap** [AlbrechtL/welle.io#410]
The "ensemble name" of the station should normally be shown in the "service overview" panel between the two signal & loudspeaker icons.
But for me this is almost never the case.
This is on linux debian with RTL-SDR, welle-io 2.0 beta3

**Comment by tenzap** [comment]
Proposal of fix in PR #413

**Comment by AlbrechtL** [comment]
Thanks for adding. Will be merged after the version 2.0 release.

**Comment by AlbrechtL** [comment]
https://github.com/AlbrechtL/welle.io/pull/413 is merged.
