### ISSUE TITLE
Warning: Icon theme "welle_io_icons" not found.

### ISSUE THREAD

**Issue by tenzap** [AlbrechtL/welle.io#416]
When on KDE with "org.kde.desktop" style there is this message in the console and icons are not displayed;
`Warning: Icon theme "welle_io_icons" not found.`

There are 2 ways to have this fixed:
- Either copy the icons theme (`welle_io_icons` directory) to a valid system icon directory on linux like "`/usr/share/icons`"
- or rename the base folder of the icons to "icons" instead of "icon" ?

I found this bug in KDE : https://bugs.kde.org/show_bug.cgi?id=405522. Probably this is related.

According to https://sources.debian.org/src/kiconthemes/5.62.0-1/src/kicontheme.cpp/#L289 I understand that in KDE, the system loads preferably the icons in the embedded "/icons" folder. But this directory doesn't exist in welle-io, instead it is called "icon". Hence the 2nd way to fix it.

**Comment by AlbrechtL** [comment]
Thanks for figuring this out!

I agree that the situation is not nice at the moment. But all style related changes I will merge after the version 2.0 release.

**Comment by AlbrechtL** [comment]
> or rename the base folder of the icons to "icons" instead of "icon" ?

Which base folder do you mean? This one `/src/welle-gui/icon/welle_io_icons`?

**Comment by tenzap** [comment]
the `icon` folder in `/src/welle-gui/`

**Comment by AlbrechtL** [comment]
In this case I would prefer to rename the folder to `icons`.

**Comment by tenzap** [comment]
Ok, please do :)

**Comment by AlbrechtL** [comment]
You are welcome to send a pull request.

**Comment by tenzap** [comment]
fixed by #449
