### ISSUE TITLE
Add possibility to group the stations by Channel

### ISSUE THREAD

**Issue by tenzap** [AlbrechtL/welle.io#419]
On my place there are >80 stations on 7 channels
Depending on the way my antenna is placed I receive some channels or not.
Thus it would be nice to have the ability to group the stations by channel to know immediately the stations I can choose depending on the channels I receive at that time

Display of the station list could be as such:
```
Channel 5A:
   STATION 1
   STATION 2
   STATION 3
Channel 7D:
   STATION A
   STATION B
   STATION C
 ...
```

**Comment by AlbrechtL** [comment]
Great idea! Are are welcome to post a GUI mockup how it should look like.

**Comment by tenzap** [comment]
related to #487 and #669

**Comment by AlbrechtL** [comment]
FYI: I'm proposing a possible solution here: https://github.com/AlbrechtL/welle.io/issues/487#issuecomment-2563988969
