### ISSUE TITLE
In config file, gain value is stored with the label

### ISSUE THREAD

**Issue by tenzap** [AlbrechtL/welle.io#424]
The value is :
manualGainValue=Value: 0.00
While it should probably be
manualGainValue=0.00

**Comment by AlbrechtL** [comment]
Yes, you are right. So I suppose storing the manual gain is not working at the moment. Can you test it please?

**Comment by tenzap** [comment]
Seems manual gain is correctly stored & restored.
So this is just a cosmetic issue -> fixed by PR #471

**Comment by AlbrechtL** [comment]
https://github.com/AlbrechtL/welle.io/pull/471 is merged.
