### ISSUE TITLE
NewFeature: Add ability to set the qtquick style in the gui

### ISSUE THREAD

**Issue by tenzap** [AlbrechtL/welle.io#429]
I made a few changes to be able to select QtQuick Style at startup.
ComboBox displays all styles available on the system with 
- Default as 1st item, and
- System Auto as 2nd item. System Auto works as if the Style was not hardcoded.

Welle.io restart is needed so that the change is effective

![select style](https://user-images.githubusercontent.com/46226844/65908979-d13ddc00-e3c7-11e9-8628-4594d14135af.png)

I can make a PR if you would like to add that feature

**Comment by AlbrechtL** [comment]
Wow! That is really great. Some people already requested it!
I can add it in version 2.1 if you send a pull request.

**Comment by tenzap** [comment]
In PR #435

**Comment by AlbrechtL** [comment]
#435 is merged!
