### ISSUE TITLE
[welle-cli] song saving of mp3 with title/interpreter

### ISSUE THREAD

**Issue by alexmyczko** [AlbrechtL/welle.io#433]
I know there has been closed issues already, but streamripper would just not get the song titles, and having the mp3 streams is great via https://github.com/AlbrechtL/welle.io/wiki/Using-the-welle-cli-Web-Interface

What would I do to get a ton of mp3 with the right start/stop and songname/interpreter (DLS) from the welle-cli web interface?

the web interface is jumpy (horiziontally as well as vertically), can that be improved?

**Comment by andimik** [comment]
I already have improved the horizontal jumping by setting a fixed width for the Dynamic Label column. So you could edit the file yourself as well.

**Comment by alexmyczko** [comment]
How did you? I did like this:

```
 table, th, td {
     border: 1px solid black;
     border-collapse: collapse;
+    width: 100%;
 }
 th, td {
     padding: 5px;
     text-align: left;
+    width: auto;
 }
 th#dls {
      width: 300px;
```

**Comment by AlbrechtL** [comment]
What is your use case? I mean I totally understand it but do you do it for personal use or some professional projects?

**Comment by alexmyczko** [comment]
have some music replayable, while offline, personal only

**Comment by mpbraendli** [comment]
Don't use the web page for such tasks, get the `mux.json` directly and parse it externally with a script.

**Comment by AlbrechtL** [comment]
@alexmyczko Is your question answered?

**Comment by mpbraendli** [comment]
(I interpreted @alexmyczko's thumbs-up as "yes")
