### ISSUE TITLE
[macos macports] - rtl-sdr issues

### ISSUE THREAD

**Issue by tenzap** [AlbrechtL/welle.io#436]
This is on macos El Capitan 10.11.6

I installed the various libraries and also the qt libraries with macports.
Then I compiled welle.io with cmake (with both rtlsdr & soapysdr)

At startup, as soon as I start playing a station, or start a scan, welle.io blocks with a "occupied" mouse cursor.
This is when launching welle this way (almost every time)
`./welle-io`

The log is as bellow
[log.txt](https://github.com/AlbrechtL/welle.io/files/3720972/log.txt)

However, I noticed that if I run it with this command, most time the issue doesn't appear...
`./welle-io 2> /dev/null > /dev/null`

On another hand, when using the rtl-sdr plugin, when browsing in firefox while welle.io is playing in the background it seems synchronisation is lost at every action I do in firefox. The thing is that at every click in firefox, playing is interrupted for a short time until it somehow synchronises again.

When choosing soapysdr (with SoapyRtlSdr module) whatever the command above:
- welle.io doesn't block.
- synchronisation is hardly lost compared to rtl-sdr. Playback quirks happen only when the system/firefox is under heavy load

**Comment by AlbrechtL** [comment]
I don't own a Mac so I don't have any experience with it.

For the mouse behavior I don't have a explanation. Did you enable the console view inside the expert mode?

The behavior for sync lost during web browsing I know from low powered CPU like Intel Atom (2015) and Raspberry Pi 2/3.

**Comment by tenzap** [comment]
expert view was not enabled.
Well, the mouse icon means busy, and welle-io  has to be killed manually. That's the only way to get out of it

**Comment by AlbrechtL** [comment]
Which CPU has your Mac?

**Comment by tenzap** [comment]
I don't own a mac, but that mac is 
Processor Speed: | 2.66 GHz | Processor Type: | Core 2 Duo (E8135)

But I don't think the freeze is CPU linked since 
- there is no freeze with Soapy + soapyrtlsdr 
- but it freezes with only rtl-sdr

**Comment by AlbrechtL** [comment]
According to https://www.cpubenchmark.net/cpu.php?cpu=Intel+Core2+Duo+E8135+%40+2.66GHz&id=949 the Intel E8135 CPU is 10 years old and has only two cores. Even the CPU mark of 1761 shows that this is the absolutely minimum to run welle.io. I don't know how macOS renders the graphics but if the rendering is done with the CPU then the CPU power is ways to low.

I'm pretty sure that issues comes with the low CPU power.

**Comment by AlbrechtL** [comment]
Can you try the 2.0 beta 3 (https://github.com/AlbrechtL/welle.io/tree/v2.0-beta3)?

**Comment by tenzap** [comment]
This was with 2.0beta3 until commit 801e483

**Comment by tenzap** [comment]
Hmm... interesting... 
"pure" 2.0beta3 -> Works (both with & without autoplay)
"pure" 2.0beta3 + #431 + 'no autoplay' -> Works
"pure" 2.0beta3 + #431 + 'autoplay' -> Freezes at startup

So it seems #431 is in cause.

**Comment by AlbrechtL** [comment]
Any news here?
@tenzap Do you have a fix?

**Comment by tenzap** [comment]
should be fixed by #460 I guess

**Comment by AlbrechtL** [comment]
>concerning the freeze should be fixed by #460

Great! Then I can close this issue again ;-)

> But concerning the sync loss, I have no clue

The sync lost is coming from the weak CPU power.
