### ISSUE TITLE
[welle-cli] Can’t change frequency

### ISSUE THREAD

**Issue by AurelienPicart** [AlbrechtL/welle.io#439]
Can’t change frequency and check coarse correction on welle.io CLI. Bug reporting on ARM and X64 processor.

**Comment by AlbrechtL** [comment]
Why did you close this issue? Is it solved?

**Comment by mpbraendli** [comment]
@AurelienPicart told me it is fixed now

**Comment by AlbrechtL** [comment]
Great!
