### ISSUE TITLE
[welle-cli] Cannot stop with ctrl+c after playing an mp3

### ISSUE THREAD

**Issue by andimik** [AlbrechtL/welle.io#444]
As soon as a mp3-stream has started by pressing the red "Play" button on the right 
![image](https://user-images.githubusercontent.com/24510556/67325038-c5e85700-f514-11e9-9816-aeb507320dd1.png)
the welle-cli cannot be stopped by pressing ctrl+c. The only way to stop it is to terminate the terminal.

A normal interupt would be

```
^Caccept failed: Interrupted system call
socket in dispatcher not valid!
OFDM-processor: closing down

```

But in this case the console just says either

```
^Caccept failed: Interrupted system call
socket in dispatcher not valid!

```
or even

```
Failed to send audio for 44370
Failed to send audio for 44370

```
all the time.

No matter if I stop the stream by pressing the red "Stop" button or not.

**Comment by mpbraendli** [comment]
The program now closes on Ctrl-C since commit `81f757c`, but there seems to be an issue with teardown, because it more often than not crashes.

**Comment by andimik** [comment]
Yes, you are right, sometimes I can stop it, but sometimes I still need to terminate the console. And sometimes I have a seg fault.

Should I post bt?

**Comment by mpbraendli** [comment]
As I still have an open change I need to test and push, it's not necessary to do a backtrace on the latest commit.

Sorry for the slow progress on this.

**Comment by mpbraendli** [comment]
It's worth trying again now, I hope it's fixed now. Please open the issue again if you encounter issues at tear-down.
