### ISSUE TITLE
[macos] : freeze at startup with rtlsdr (but not soapy)

### ISSUE THREAD

**Issue by tenzap** [AlbrechtL/welle.io#451]
Continuation of #436 which I cannot reopen

Well to sum things up :

- welle.io + rtlsdr : freeze at startup (every now & then) needing to kill because welle.io doesn't respond at all.
- welle.io + soapysdr with soapyrtlsdr : never freezes at startup

I don't see how the CPU can be a reason here if it does work with soapy and not rtlsdr. My interpretation is the problem is more due to rtlsdr input implementation than the cpu.

**Comment by AlbrechtL** [comment]
Please don't open new issues. Even if an issue is closed we can discuss it.

I put my comment in https://github.com/AlbrechtL/welle.io/issues/436.
