### ISSUE TITLE
are multimedia & network QT modules still needed ?

### ISSUE THREAD

**Issue by tenzap** [AlbrechtL/welle.io#456]
It seems they aren't used anywhere in the code.
Can I remove them from `welle-gui.pro` & `.travis.yml` ?

Could this also reduce the size of built binaries as a side effect ?

**Comment by AlbrechtL** [comment]
I think multimedia is used for the sound output. Most likely network is not necessary any more. In the past it was used for rtl_tcp input but this part is replace by the native OS functions.

Please verify it.

**Comment by tenzap** [comment]
Verify what and how ?

**Comment by AlbrechtL** [comment]
I merged https://github.com/AlbrechtL/welle.io/pull/473. Lets see what happens ;-)
