### ISSUE TITLE
Software freezes on "Start station scan"

### ISSUE THREAD

**Issue by m0ukd** [AlbrechtL/welle.io#457]
I have an issue with version 2.0 where the software freezes when I click "Start station scan". It is only with version 2.0.

Version 2.0-Beta 3 was working fine. I've tried a few re-installs but no luck. I can only use 2.0-Beta 3.

Any ideas what this could be? I'm using standard RTL-SDR on Windows 10.

Thanks, John.

**Comment by tenzap** [comment]
Likely same a #436, can you try by reverting commit e334317 on 2.0 release ?

**Comment by tenzap** [comment]
Can you retry with latest nightly build ? It should be fixed since #460 has been merged

**Comment by m0ukd** [comment]
Hi tenzap. Thanks for your help. I installed
20191113_ef3417d_Windows_welle-io-setup.exe
But I get an error when launching app of: Entry Point Not Found.
![error](https://user-images.githubusercontent.com/11397568/68899424-88e53e00-0729-11ea-84f3-5171cc7b1209.png)

**Comment by tenzap** [comment]
It seems to be a windows specific issue could you please file a new bug report with it ?

**Comment by LA5HJA** [comment]
I did also try the Welle.io 2.0 and it did also freeze up on my win 10 pro N, when installing the Wello.io beta3 did it work wery well.

**Comment by AlbrechtL** [comment]
>  But I get an error when launching app of: Entry Point Not Found.

I fixed the Windows issue in https://github.com/AlbrechtL/welle.io/commit/fd4e94885622708051af0d4ad8d990b69e3736cc. 

Please try again the latest nightly build.
