### ISSUE TITLE
AppImage 2.0 not working on Debian, same hardware on Windows/Android working :(

### ISSUE THREAD

**Issue by retrorich75** [AlbrechtL/welle.io#459]
Trying to use welle.io ver 2.0 with the following hardware : NooElec, NESDR Nano 3 under Debian 10 64 Bit and rtl_tcp results in no lock on signal.

Same Hardware under Windows 10 64 Bit and Android 9.0 phone or tablet works!

Not an expert the only thing different I see is the rtl_tcp programme under Linux is always changing the "gain".

rtl_tcp has this error in the output

"r82xx_write: i2c wr failed=-7 reg=05 len=1"

![well io android9](https://user-images.githubusercontent.com/6966118/67689873-46d3a280-f99c-11e9-81d0-ef367e2c5c40.png)

![welle io debian10](https://user-images.githubusercontent.com/6966118/67689724-08d67e80-f99c-11e9-821e-17284b3d7d64.png)

![welle io win10](https://user-images.githubusercontent.com/6966118/67688465-29053e00-f99a-11e9-95db-386c7068c7a2.png)

**Comment by AlbrechtL** [comment]
Please post your expert settings.

**Comment by AlbrechtL** [comment]
Please test it with version 2.1 again.

**Comment by alexmyczko** [comment]
Here's a buster simple sid backport `http://phd-sid.ethz.ch/debian/welle.io/buster/` maybe you want to try that?

**Comment by AlbrechtL** [comment]
Closed because of inactivity.
