### ISSUE TITLE
Windows: update fails, uninstall old version necessary

### ISSUE THREAD

**Issue by andimik** [AlbrechtL/welle.io#46]
I wanted to install the new version, but then I had to uninstall the old version as the path already existed.
![welle_io_installproblem](https://cloud.githubusercontent.com/assets/24510556/24585956/f949a256-1796-11e7-8fba-3732445227e0.PNG)

**Comment by AlbrechtL** [comment]
You can install the new version in another path.
The QT Install Framework (QTIFW) doesn't support deinstallation before a new installation at the moment.
