### ISSUE TITLE
[web page] macOS install options: mention MacPorts on Download page

### ISSUE THREAD

**Issue by lhaeger** [AlbrechtL/welle.io#462]
welle.io is available via MacPorts but this is not mentioned on https://www.welle.io/#download. Please add those options and possibly a link to the MacPorts homepage.

**Comment by AlbrechtL** [comment]
Great idea!

Your can find the website source code at the branch [gh-pages](https://github.com/AlbrechtL/welle.io/tree/gh-pages).
The index site is here https://github.com/AlbrechtL/welle.io/blob/gh-pages/pages/pages-root-folder/index.md

Please feel free to add your idea by creating a pull request.

**Comment by tenzap** [comment]
see PR #486

**Comment by AlbrechtL** [comment]
@tenzap Thanks for the PR!
