### ISSUE TITLE
[welle-cli] Remove play button for Datastreams

### ISSUE THREAD

**Issue by andimik** [AlbrechtL/welle.io#465]
I've recognized that the red button "Play" also appears when the service is a packetdata (DSCTy=null like EPG, Journaline) or streamdata (DSCTy=5)

The problem is that after pressing the Play button for such a data stream playing won't work for audio services any more as long as you restart welle-cli.

**Comment by mpbraendli** [comment]
Hello, this should be fixed in the latest `next`, both the play button and the lockup.

**Comment by andimik** [comment]
You were 5 seconds faster than me
