### ISSUE TITLE
[windows] Allow update version overwriting files

### ISSUE THREAD

**Issue by jpuigs** [AlbrechtL/welle.io#467]
In windows version, if we want to update, we have to first uninstall it, because if we try to update on same folder, install program says there exists another version ans doesn't let us update it.

**Comment by AlbrechtL** [comment]
Great idea!

welle.io uses the [Qt Installer Framework Manual](https://doc.qt.io/qtinstallerframework/index.html). 

Everyone is invited to send a pull request which implements this feature.

**Comment by AlbrechtL** [comment]
At the moment this is a limitation of the Qt Installer Framework. See here: https://bugreports.qt.io/browse/QTIFW-573.

**Comment by AlbrechtL** [comment]
Done in version 2.5!
