### ISSUE TITLE
[Majnaro Linux] Unknown module(s) in QT: charts multimedia

### ISSUE THREAD

**Issue by zygmund2000** [AlbrechtL/welle.io#47]
Hi,

I have to machines with identical system Majnaro 64 bit, all packages are identical but on one of them I get this error: Project ERROR: Unknown module(s) in QT: charts multimedia
I don't know how to fix that, looks like something missing but I checked everything, all dependecies.
Maybe somebody know how...

Regards

**Comment by AlbrechtL** [comment]
QT charts and QT multimedia are missing on your system. Please install it.

**Comment by zygmund2000** [comment]
I wrote earlier that I have everything installed, so all means all - also QT charts and QT multimedia.

**Comment by AlbrechtL** [comment]
I suppose your QT installation is broken. Please use the QT installer from https://www.qt.io/download-open-source and install it again.
