### ISSUE TITLE
Add a Pause/Stop button

### ISSUE THREAD

**Issue by jpuigs** [AlbrechtL/welle.io#482]
It would be good to have a stop button, in order to stop playing instead of need to close program or app..

**Comment by AlbrechtL** [comment]
Thanks for your idea!

**Comment by tenzap** [comment]
see PR #532

**Comment by Jasoroony** [comment]
I see all of this went no-where... but I'd like to see a stop button (detuned, like when you start the app) too.

**Comment by andimik** [comment]
You could use his PR and build welle.io. For that you even need not fork it.

**Comment by Jasoroony** [comment]
Thanks, yes I will try that.  However, I'm not at all experienced with GitHub and how all this stuff works.  I've saved the html files here that show the differences - so I can apply them by hand.  It seems his repository is outdated, so I don't want to lose the latest updates in this one.

**Comment by andimik** [comment]
Then fork welle.io and make a PR of #532 to your fork.

**Comment by Jasoroony** [comment]
@tenzap - thank-you!  I didn't copy over your start/stop mod, but I did implement the previous/next channel shortcuts (and using your awesome example code, a couple of my own shortcuts that I needed).  It's a shame you're so busy, but I understand, I'm pretty busy too with my own things ;)

**Comment by Jasoroony** [comment]
Oh, and my "top bar" now says "DAB+ Radio" instead of "welle-io" - since I've had to make my own changes, I might as well "make it my own". :)

**Comment by tenzap** [comment]
play/stop has been merged in next. This issue can be closed I guess
