### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by iMhack** [AlbrechtL/welle.io#498]
Hello,

Installed welle.io on MacOS 10.13.6 via Homebrew.
I had to add "brew install soapysdr" manually.

**Comment by AlbrechtL** [comment]
Do you mean that we have to clarify it at the documentation?

**Comment by orryverducci** [comment]
This shouldn't be required as SoapySDR is listed as a dependency in the Homebrew formula.

In addition `brew install soapysdr` won't work out of the box, it requires the homebrew-pothos tap to be added, so shouldn't be documented as this.

**Comment by AlbrechtL** [comment]
If we need more clarification we send a pull request.
