### ISSUE TITLE
Suggestion: With "dark mode" font of the channel list difficult to read

### ISSUE THREAD

**Issue by Rootinator** [AlbrechtL/welle.io#499]
Hi there,

unfortunately the channel list (left) is very difficult to read in dark mode.
It would be good if the background was designed as the right side or the color of the font changed.

**Comment by AlbrechtL** [comment]
@tenzap Can you have a look into it?

**Comment by tenzap** [comment]
Which color would you suggest ? Ideally the color should be automatically set, but on this widget, the back/foreground color for text doesn't seem automatic, so that would require a special definition of font color in that case.

**Comment by Rootinator** [comment]
Possibility 1:
Leave the background as it is and change the font color from black to white or light gray

Possibility 2:
The same color as in the station name field

Option 3:
Something so that the stations (left) are legible :P

**Comment by tenzap** [comment]
Would this be ok ?

* Material Dark
![Screenshot_20200126_103059](https://user-images.githubusercontent.com/46226844/73133302-0df0ab80-4027-11ea-8fda-7c76f8e0a617.png)

* Universal Dark
![Screenshot_20200126_103037](https://user-images.githubusercontent.com/46226844/73133304-10530580-4027-11ea-9147-7928275501e7.png)

BTW: I also changed the font color for the switch labels & the combobox values

**Comment by Rootinator** [comment]
That looks great! :)

-----

(Because of the SoapySDR error in the lower part of the screenshots: I can still use the SoapySDR in a next version?)

**Comment by tenzap** [comment]
> When can I compile a new version with the new font color?

As soon as you apply the [patch of the #503 PR](https://patch-diff.githubusercontent.com/raw/AlbrechtL/welle.io/pull/503.patch ) locally

> (Because of the SoapySDR error in the lower part of the screenshots: I can still use the SoapySDR in a next version?)

No worry, my device wasn't connected, hence the message ;)

**Comment by Rootinator** [comment]
What exactly do I have to do to apply the patch? 

Do I have to compile welle.io 2.1 again (without changes) or how do I apply it? :)

**Comment by tenzap** [comment]
apply the patch either on the source of 2.1 release (it's unsure whether there will be errors while patching, but I don't think there will be any) or on the source of the next branch.
then, compile it

**Comment by Rootinator** [comment]
Sorry, but I do not know which file from welle.io (source code) I have to insert it into.  Can you explain that to me step by step?

**Comment by tenzap** [comment]
From within the root of the source folder of welle.io (`welle.io-2.1` for example) run this command
```
patch -p1 < "the_patch_file_you_downloaded.patch"
```
Then compile as usual

**Comment by Rootinator** [comment]
Thank you for the patch!
Now I can read everything well.

**Comment by AlbrechtL** [comment]
Thanks @tenzap for fixing!
