### ISSUE TITLE
unable to find anything in poland/.pl with station scan

### ISSUE THREAD

**Issue by alexmyczko** [AlbrechtL/welle.io#511]
what could i be doing wrong?

**Comment by andimik** [comment]
Do you have any DAB radio? Is the reception good enough? You could check availability on fmscan.org

**Comment by alexmyczko** [comment]
same hw works in switzerland, tried two locations but you link tells me 12A so i will try again

**Comment by AlbrechtL** [comment]
You can switch welle.io into expert mode and then check the spectrum. Feel free to post it here.

**Comment by andimik** [comment]
@alexmyczko Did our hints help you?

**Comment by alexmyczko** [comment]
i wasn't able to get any DAB in .pl, but it's fine
