### ISSUE TITLE
Update website and README.md for Debian packages

### ISSUE THREAD

**Issue by AlbrechtL** [AlbrechtL/welle.io#512]
Thanks to Alex (@alexmyczko) Debian packages are existing!
See: https://github.com/AlbrechtL/welle.io/issues/506#issuecomment-594061643

We need somebody that is updating the [Website](https://github.com/AlbrechtL/welle.io/blob/gh-pages/pages/pages-root-folder/index.md) and the [README.md](https://github.com/AlbrechtL/welle.io/blob/next/README.md) for an installation procedure.

**Comment by alexmyczko** [comment]
https://github.com/AlbrechtL/welle.io/pull/533

**Comment by AlbrechtL** [comment]
Thanks!
