### ISSUE TITLE
Please add compatibility with Navit.

### ISSUE THREAD

**Issue by Supermagnum** [AlbrechtL/welle.io#514]
I believe that Navit uses the TRAFF format for traffic information. TraFF is an XML-based format. 
Links:
https://traffxml.gitlab.io/
https://www.navit-project.org/
https://wiki.navit-project.org/index.php/Traffic_in_Navit

**Comment by andimik** [comment]
Pull Requests are welcome of course.

If you have documents about TPEG, please share them with us.

I don't any free or open source software which can extract TPEG data from the DAB stream.

**Comment by Supermagnum** [comment]
https://www.worlddab.org/dab/technical-specifications

**Comment by AlbrechtL** [comment]
From what I understood is that traffxml is a format to exchange traffic information. It can be used to transfer this information to other apps like Navit.

But to use that we need a TPEG decoder that we don't have. Do I'm right?

**Comment by Supermagnum** [comment]
> From what I understood is that traffxml is a format to exchange traffic information. It can be used to transfer this information to other apps like Navit.
> 
> But to use that we need a TPEG decoder that we don't have. Do I'm right?

Yes, a TPEG decoder is needed. 
Slightly off topic: There are two different TPEG services in Norway, one unencrypted by NRK and one encrypted by v-traffic.

**Comment by AlbrechtL** [comment]
If anyone knows a TPEG decoder please let us know it.

**Comment by Supermagnum** [comment]
> If anyone knows a TPEG decoder please let us know it.

They are working on it, but they need open unencrypted TPEG raw data:
https://github.com/JvanKatwijk/qt-dab/issues/156

**Comment by AlbrechtL** [comment]
Lets see how Jan (@JvanKatwijk) proceeds with his activities.

**Comment by AlbrechtL** [comment]
I'm closing this issue because the DAB data services are not in the focus right now.

If somebody provides a PR, that would be fantastic!
