### ISSUE TITLE
Support for 2nd PTy (static and dynamic)

### ISSUE THREAD

**Issue by andimik** [AlbrechtL/welle.io#519]
Today I found out that the German Ensemble **SWR BW N** (Südwestrundfunk Baden-Württemberg Nord) has an interesting feature: There are two different PTy for the same service.

[swr_n.eti.zip](https://github.com/AlbrechtL/welle.io/files/4383395/swr_n.eti.zip)

If you play that eti-file (using odr-dabmod) in `welle-cli` the PTy of **SWR4 S** (Stuttgart) seems to "blink" between nothing and Talk (= Varied), all other SWR4 services blink between Talk and News during the world news.

![grafik](https://user-images.githubusercontent.com/24510556/77584047-6be42700-6ee2-11ea-99e5-09ca1abe15bc.png)

According to dablin_gtk there are two PTy: one is static, one is dynamic.

![grafik](https://user-images.githubusercontent.com/24510556/77583124-d09e8200-6ee0-11ea-96ec-45b013d4b4ab.png)

So, in general, welle-cli reads out both PTy fields, but I would suggest to write them in two lines.

For welle-io it seems only the dynamic PTy is displayed (= SWR4 S shows no PTy)

**Comment by basicmaster** [comment]
So far I have seen this situation (both dynamic and static programme type for a service) only in the SWR ensembles.

Note that in EN 300 401 v1 this was kind of allowed (i.e. not exactly defined; at least not explicitely forbidden), but in v2 it is now clearly forbidden to have both kind of types for a particular service.

**Comment by AlbrechtL** [comment]
Since this behavior is forbidden now I can close this issue.
