### ISSUE TITLE
SNR calculation not working if strong neighbour channels available 

### ISSUE THREAD

**Issue by AlbrechtL** [AlbrechtL/welle.io#52]
The SNR calculation is not working if strong neighbour channels are available.
![nh_radio_good_screen](https://cloud.githubusercontent.com/assets/11890145/25073486/37fdc6f6-22e8-11e7-8bed-b801f6c91fd5.png)

**Comment by mpbraendli** [comment]
SNR could be calculated by comparing energy of the PRS and data symbols against energy of the NULL symbol, instead of looking at out-of-band power.

**Comment by AlbrechtL** [comment]
Good idea.
But from my understanding we have to be synchronized to calculate the SNR. So we can use the current SNR calculation while there is no sync and use the new one if we are in sync.

**Comment by AlbrechtL** [comment]
Fixed in https://github.com/AlbrechtL/welle.io/commit/96208fce17dabcadc200df2c97d455717d97db98.
![2020-09-30_22-04](https://user-images.githubusercontent.com/11171787/94734059-ef3a7580-0368-11eb-8dcf-c2a139d78ae5.png)
