### ISSUE TITLE
[Android] Parsing error on 2.1 apk

### ISSUE THREAD

**Issue by stopherm** [AlbrechtL/welle.io#542]
When trying to install the 2.1 Android version, there comes an error message:  "Parse Error: There was a problem parsing the package"
Tried on different devices running Android 7 & 8 (non x86 versions).

Maybe the file is corrupt?

**Comment by AlbrechtL** [comment]
Which APK did you use?

**Comment by stopherm** [comment]
I'd tried it with the welle.io_2.1_Android_ARM64-v8a.apk and the welle.io_2.1_Android_ARMv7.apk. 
I'm running Android 8 64bit on the Galaxy S7

**Comment by AlbrechtL** [comment]
At the moment the Android version is not really maintained. You can try to build it from the sources.

For now I close this issue.
