### ISSUE TITLE
[welle-cli] Allow streaming wav to stdout using

### ISSUE THREAD

**Issue by athoik** [AlbrechtL/welle.io#560]
Hi,

Is there a possible way to stream only one channel on stdout using welle-cli?

Something like `welle-cli -c 12C -p 0x1001 -stdout` ?

Thanks

**Comment by andimik** [comment]
Why don't you use https://github.com/JvanKatwijk/dab-cmdline for that?

**Comment by athoik** [comment]
Because it seems welle-cli can write files in wav (RIFF) format.

The dab-cmdline produces raw PCM and that doesn't work if you like to stream it on enigma2 or to vlc.

**Comment by AlbrechtL** [comment]
What is your use case?

**Comment by athoik** [comment]
Create a pipeline and feed a player from a specific channel from command line.

As @andimik  said, dab-cmdline offer this already, but with RAW PCM samples.

**Comment by AlbrechtL** [comment]
Yeah that's clear. But what is the use case to do such an complicated setup? You can either use welle.io GUI or the MP3 feature of welle-cli.
