### ISSUE TITLE
Ensemble ID

### ISSUE THREAD

**Issue by G4JFS** [AlbrechtL/welle.io#566]
How can I view the Ensemble Id? I can't find it in any of the windows. Service Ids are all there but I can't see the EId anywhere.

**Comment by andimik** [comment]
Why do you need that?

You find it in the console.

> Debug: RadioController: ID of ensemble

Please note it's in decimal, not in hex.

**Comment by G4JFS** [comment]
I can't see it, even in decimal. Here is a screenshot. Where should I look?

**Comment by andimik** [comment]
You forgot to send the screenshot.

Set to expert mode and add the console window check there.

But why do you need it?

**Comment by AlbrechtL** [comment]
@G4JFS Is the questions answered?

**Comment by G4JFS** [comment]
I have the console window open but don't see the EId there.
![Welle](https://user-images.githubusercontent.com/66311860/85337442-65148280-b4d8-11ea-8ffe-0079b39f9d31.jpg)

**Comment by andimik** [comment]
Check again and look for the text I gave you. It can be found right after a lock.

**Comment by G4JFS** [comment]
Found it! Not particularly easy to spot as the console output window displays so much information. Is that information written out to a log file somewhere? I haven't found one yet. 

EId an important element for confirming the identification of a multiplex. I had assumed it would be displayed  in a more prominent place. Could it be?

**Comment by andimik** [comment]
Although the Ensemble (long Label (in your case 'BBC National DAB') is a text field, it is a better indicator than the Ensemble ID.

Because in Europe different muxes are using same IDs.

I know it from Austria, within 1 hours drive I can receive Italian and Slovak ensemble, but both have the same ID causing mismatch in my car radio.

**Comment by basicmaster** [comment]
One purpose of the EId is to be unique in a certain area (at least combined with the ECC), so there shouldn't be any ID used more than once. I can't find two similar EIds listed on the ukwtv.de....can you post an example?

**Comment by andimik** [comment]
RAI and Slovak ensemble

**Comment by basicmaster** [comment]
They have indeed the same EId. However, this is allowed - in combination with the ECC, the ensemble is unique, as Italy uses `0xE0` and Slovakia `0xE2` (as DAB defines). It is just a bit an unfortunate choice.

**Comment by andimik** [comment]
The Czech CRo DAB use ID 0x2005 in the same country, but with different content.

And TELEKO has 0x2001 for both (different) multiplexes.

**Comment by AlbrechtL** [comment]
Does it make sense to put the ensemble ID into the "Service Details" view?

**Comment by G4JFS** [comment]
Would it not be better in Service Overview?

**Comment by andimik** [comment]
As long it is only visible in the expert view.

**Comment by G4JFS** [comment]
Expert view is certainly the place to put it.

**Comment by AlbrechtL** [comment]
OK. This feature could be something for the version 2.3.
Pull request are welcome!

**Comment by G4JFS** [comment]
Thanks. I look forward to it (in hex please!). I'm new here; where is the best place to put suggestions for the next version?

**Comment by AlbrechtL** [comment]
Postponed to a later version. Pull request are still welcome.

**Comment by AlbrechtL** [comment]
Added in https://github.com/AlbrechtL/welle.io/commit/6a1adf03c2acc66d7347ad18f43974b3bc075e70.

![grafik](https://github.com/user-attachments/assets/0f954042-1a0b-4f06-a452-c3ec121128bc)
