### ISSUE TITLE
MOT slideshow shows image path

### ISSUE THREAD

**Issue by FartherOut** [AlbrechtL/welle.io#569]
![2020-07-09-024849_800x480_scrot](https://user-images.githubusercontent.com/33982853/86985301-3f9e9e80-c191-11ea-9289-1f3b4de75867.png)

As you can see, the image path for images is visible in the slideshow section.
Perhaps it is a debug option/error?

BTW, also visible in the macOS version.

**Comment by AlbrechtL** [comment]
This is because you enabled the expert view. If you disable it is gone.

**Comment by FartherOut** [comment]
Indeed it is.
I always use expert mode so I didn't think to check normal mode.
Thanks for explaining.
