### ISSUE TITLE
[nb-NO] Incomplete translations

### ISSUE THREAD

**Issue by FartherOut** [AlbrechtL/welle.io#571]
![2020-07-09-025106_800x480_scrot](https://user-images.githubusercontent.com/33982853/86985899-9ce71f80-c192-11ea-945f-de32917dcca6.png)
The "style settings" section is not translated and I don't believe it is located in the qt translation tool for people to translate.

**Comment by andimik** [comment]
Can you please check the same window in other languages, for instance German?

**Comment by tenzap** [comment]
In french it is translated.

**Comment by FartherOut** [comment]
I see it.
I'll translate it myself one of these days.

**Comment by AlbrechtL** [comment]
Please send a pull request.

**Comment by FartherOut** [comment]
Sent pull request #584 

Also went over everything and updated some old translations.

**Comment by AlbrechtL** [comment]
Thanks! PR is merged.
