### ISSUE TITLE
[Raspberry Pi] Material theme menu is transparent.

### ISSUE THREAD

**Issue by FartherOut** [AlbrechtL/welle.io#572]
![2020-07-09-025159_800x480_scrot](https://user-images.githubusercontent.com/33982853/86986102-1f6fdf00-c193-11ea-96d1-4491b9296b9b.png)
Material theme showing the GUI.

![2020-07-09-025237_800x480_scrot](https://user-images.githubusercontent.com/33982853/86986125-2dbdfb00-c193-11ea-9935-a8746b3ab019.png)
Material theme showing the settings menu.
Transparency issue makes it almost impossible to read the text and push the buttons.

Material theme works normally in the macOS version.

**Comment by AlbrechtL** [comment]
Thanks for reporting!

**Comment by AlbrechtL** [comment]
I'm closing this issue because I'm not sure if it is still relevant. If it still occurs in the latest version, we can reopen it.
