### ISSUE TITLE
Window resizes when changing the language

### ISSUE THREAD

**Issue by andimik** [AlbrechtL/welle.io#575]
when changing the language the window resizes (is fixed in tenzap's fork as far as I know)

**Comment by tenzap** [comment]
Cannot reproduce on linux with "20200711_9f4342b_Linux_welle-io-x86_64.AppImage"

**Comment by andimik** [comment]
Which Linux is it?

Seems the issue doesn't show up on Ubuntu MATE 20.04 whereas Ubuntu 20.04 is affected.

**Comment by tenzap** [comment]
debian buster

**Comment by AlbrechtL** [comment]
I can't reproduce it with c39d3420cc30281e03835b3182f34d8617eb7ebf.
