### ISSUE TITLE
rawfile autodetection does not work properly

### ISSUE THREAD

**Issue by andimik** [AlbrechtL/welle.io#576]
Autodetection of rawfile format does not work properly (sdr 16bit are displayed as 8bit)
![87242364-3846f180-c42c-11ea-807d-c82ba573a538](https://user-images.githubusercontent.com/24510556/87460512-47d16080-c60d-11ea-948a-355b1d2c4aac.png)

**Comment by AlbrechtL** [comment]
Thanks for reporting.

**Comment by AlbrechtL** [comment]
Actually, the behavior is correct. It depends on the file ending. If no data type file ending is used, it falls back to unsigned int 8 bit.

See code:
https://github.com/AlbrechtL/welle.io/blob/a910d9d2f8116aa84d476eb39efa1c24ccb4b429/src/input/raw_file.cpp#L370-L399
