### ISSUE TITLE
Waterfall diagram for 16bit files broken

### ISSUE THREAD

**Issue by andimik** [AlbrechtL/welle.io#577]
Waterfall diagram for 16bit files seems not to work properly (= I just saw it once)

![87242406-aee3ef00-c42c-11ea-9135-d714165bafc6](https://user-images.githubusercontent.com/24510556/87460637-73544b00-c60d-11ea-92af-001682eb2763.png)
![87242412-be633800-c42c-11ea-856f-665814f64e32](https://user-images.githubusercontent.com/24510556/87460647-764f3b80-c60d-11ea-9d9b-1bb6ca3a40fb.png)

**Comment by AlbrechtL** [comment]
Thanks for reporting.

**Comment by AlbrechtL** [comment]
Can you provide a 16-bit IQ file please?

**Comment by andimik** [comment]
Sure, please find it under

https://we.tl/t-5I2Ng26iks

It's Mux I Austria from Dobratsch on 6A.
Recorded with Qt-DAB, so it should be 16le

Download accessible within 7 days

**Comment by AlbrechtL** [comment]
Thanks!
Fixed in https://github.com/AlbrechtL/welle.io/commit/6315838855c4f8abac4523737a79fa991561b829.

**Comment by andimik** [comment]
Confirmed, now it works
