### ISSUE TITLE
Hide "manual channel" when input is a file

### ISSUE THREAD

**Issue by andimik** [AlbrechtL/welle.io#578]
When playing a raw file, it makes sense to hide the "manual channel".

![77820258-3b1e1080-70e1-11ea-8974-48c46657f77a](https://user-images.githubusercontent.com/24510556/87460704-8cf59280-c60d-11ea-89ef-4928bfe698a3.png)

**Comment by AlbrechtL** [comment]
Agreed! Pull request are welcome!

**Comment by AlbrechtL** [comment]
Added in https://github.com/AlbrechtL/welle.io/commit/de9e70aeda938828e1e1d287cfc879b64e8de7fb.
