### ISSUE TITLE
audio stops wile brouwsing internet

### ISSUE THREAD

**Issue by glis011** [AlbrechtL/welle.io#58]
de audio drops sound if i listen to a station and brouwsing the web with firefox

**Comment by AlbrechtL** [comment]
welle.io needs a lot of CPU power.
Which CPU do you are using?
Can you report your CPU load please?

**Comment by glis011** [comment]
AMD dual core 5000+ 4gb ram

**Comment by AlbrechtL** [comment]
Your processor is 9 years old and has only two cores. Welle.io is optimized for 4 cores. That the sound stops while surfing is simply because your CPU is not powerful enough.

**Comment by glis011** [comment]
Ok THX for the information but it works also on PC if i dont do someting else

**Comment by tnadolecki** [comment]
I have Core i5 520M - 2.4 Ghz  with 4Gb RAM which I though was decent but I also need to shutdown all other programs while running welle.
Few seconds and cooling fan kicks in. It's not suitable for long listening unless you like overheating your gear and listening to screaming fan.

**Comment by AlbrechtL** [comment]
@tnadolecki: Even your processor is 7 years old. For using welle.io without a fan please use a device with a modern CPU like Intel Atom Z8300 or Intel Atom Z3736F . Those CPUs can handle welle.io and are working with passive cooling.
