### ISSUE TITLE
Fix amplitude (y-axis) for TII

### ISSUE THREAD

**Issue by andimik** [AlbrechtL/welle.io#580]
If there is no TII, please use a threshold or even fix the y-axis (amplitude)

![87242264-52340480-c42b-11ea-86a6-3b0ffb29ea19](https://user-images.githubusercontent.com/24510556/87460862-d34af180-c60d-11ea-87f0-3ac88876a107.png)

**Comment by AlbrechtL** [comment]
Thanks for reporting!

**Comment by AlbrechtL** [comment]
I'm closing this issue because I'm not sure if it is still relevant. If it still occurs in the latest version, we can reopen it.
