### ISSUE TITLE
SLS shown for previous service

### ISSUE THREAD

**Issue by andimik** [AlbrechtL/welle.io#581]
When I chose another service the slideshow still is shown for the previous service (I guess this only works correctly when the new service has SLS as well)

![87242288-958e7300-c42b-11ea-984b-67fcfff5cd25](https://user-images.githubusercontent.com/24510556/87460943-f1b0ed00-c60d-11ea-81d3-13fdd2396162.png)

**Comment by tenzap** [comment]
duplicate of #547 ?

**Comment by andimik** [comment]
No, in my opinion not exactly the same, but similar.

I've to investigate more, but in my case the 2nd station has no SLS at all.

**Comment by AlbrechtL** [comment]
Thanks for reporting. I keep both issues open until we analyzed the problem.

**Comment by AlbrechtL** [comment]
I have issues to reproduce this issue. If a new service is selected, the MOT picture buffer will be cleared. Maybe it is fixed by accident in the last 4 years, or I didn't find it.

For now, I'm closing it.
