### ISSUE TITLE
Add option to define target folder for saved MOT pictures

### ISSUE THREAD

**Issue by andimik** [AlbrechtL/welle.io#582]
there is no information where MOT Slideshows are stored after "save all images" dialogue.
I only see it in the console

> 2020-07-12T10:58:23.074 Info: SLS: Saving picture "/home/andreas/MOT_0__0_Soundset37537.jpg"

**Comment by AlbrechtL** [comment]
You are correct! We should add an option to define the target folder for these pictures.

**Comment by Observerist** [comment]
Thx Andimik & Albrecht.

**Comment by AlbrechtL** [comment]
Fixed in https://github.com/AlbrechtL/welle.io/commit/8180a453f4ebe526afebdb0640448c0ac37d05c4.

![2020-09-30_22-00](https://user-images.githubusercontent.com/11171787/94733773-86eb9400-0368-11eb-9c1d-e9a2da67dba2.png)
