### ISSUE TITLE
Image path in MOT slide show not readable in dark style

### ISSUE THREAD

**Issue by Observerist** [AlbrechtL/welle.io#585]
Tried the **20200707_e6bd2f5_MacOS_welle-io** version, I don't usually go to seek nightlies, but there is one visible enhancement I like : in the Material/Dark style, station list is now white, way more readable.

Besides the white on white path of the SLS visible in expert mode, didn't discover anything else done to the GUI since v2.1. 

But just this white on grey lettering is already nice to have. ( still "praying" for a station list grouped by Muxes )

Thank you

![Screen Shot 2020-07-17 at 16 52 37](https://user-images.githubusercontent.com/45834366/87802286-3bd5e080-c851-11ea-8b1a-459bed62d9e7.jpeg)

**Comment by AlbrechtL** [comment]
Thanks for reporting!

**Comment by AlbrechtL** [comment]
The path was removed in https://github.com/AlbrechtL/welle.io/commit/6170d464c4affa2086bea41a4d6395651cff932e.
