### ISSUE TITLE
[SoapySDR] How to connect hackrf one

### ISSUE THREAD

**Issue by langxj** [AlbrechtL/welle.io#589]
First of all, thank you for writing some outstanding software! I have a hackrf one board that I can operate with SDR#. How to use it welle.io Operation hackrf one

**Comment by gvanem** [comment]
HackRF is supported by the [SoapySDR API](https://github.com/pothosware/SoapySDR/wiki). 
Welle-IO can be built with support for SoapySDR. It depends on which Welle-IO you have and how it was built. 

Then select SoapySDR as the source in the settings-box:
![Welle-Soapy](https://user-images.githubusercontent.com/945271/89705434-b3cd8d00-d95d-11ea-8d45-980cefa15045.png)

You could build it yourself to ensure it uses the SoapySDR API.

**Comment by AlbrechtL** [comment]
@langxj Which OS you are using?
