### ISSUE TITLE
[Windows 7] Error "shader program not linked"

### ISSUE THREAD

**Issue by Apklink** [AlbrechtL/welle.io#59]
I am using Windows 7.  I get a message "shader program not linked"  What should I do?

Apklinl

**Comment by AlbrechtL** [comment]
Please post a screenshot of the command line window.
Which graphic card do you have?

**Comment by Apklink** [comment]
Thank you for your quick response.
I am not very computer literate and some messages which may appear logical to many, do not make sense to me.  I hope that the attached screen shots give you all the information you need.
Feel free to reply in German  I speak and read German perfectly, but I cannot write.
Regards,
Chris
![screenhunter_13 may 18 00 21](https://cloud.githubusercontent.com/assets/28750384/26187012/6a861ee8-3bd9-11e7-9924-39fb5d1c4c40.jpg)
![screenhunter_14 may 18 00 23](https://cloud.githubusercontent.com/assets/28750384/26187010/6a811498-3bd9-11e7-82ed-dc8373ded6d1.jpg)
![screenhunter_15 may 18 00 26](https://cloud.githubusercontent.com/assets/28750384/26187011/6a828616-3bd9-11e7-8331-026ae761f181.jpg)
![screenhunter_16 may 18 00 27](https://cloud.githubusercontent.com/assets/28750384/26187013/6a89c5b6-3bd9-11e7-858c-0156332ad2d2.jpg)
![screenhunter_17 may 18 00 27](https://cloud.githubusercontent.com/assets/28750384/26187014/6a8a56f2-3bd9-11e7-9507-f2ae3ad793dc.jpg)

**Comment by AlbrechtL** [comment]
Did you use the latest nvidia driver?
It is more likely a QT and OpenGL problem. You can also try to compile welle.io direct from the source https://github.com/AlbrechtL/welle.io#windows-10 and try it again.

**Comment by Apklink** [comment]
Thank you Albrecht.
I will check for for the latest nividia driver.  I am afraid that with my knowledge of computer software "QT' and OpenGL" mean nothing.  Compiling welle,io is well beyond my capabilities and as I am getting close to 80 it is a bit late to start learning new things,
Thanks again for your help

**Comment by AlbrechtL** [comment]
If the latest nvidia driver doesn't help please use Windows 10 (Windows 7 is officially not supported).

**Comment by Apklink** [comment]
Thank you again Albrecht.  
I am sorry that I have not commented earlier, I think that since you have taken the trouble to provide suggestions, common courtesy demans that I at least keep you updated on developments.  However it took me some time to install the latest driver for the Nividia Quadro FX1500 graphics card.  Windows could not manage the automatic update and only last night I managed to update the old driver (2009!) to the most recent one.
It now works like a charm!!
Hence I can confirm that the program works with Windows7 Home Premium and the Nividia Quadro FX1500 graphics card.  I am using the RTL-SDR2832 dongle.

Regards and thanks again, Chris
