### ISSUE TITLE
Add option to define MOT image folder

### ISSUE THREAD

**Issue by Observerist** [AlbrechtL/welle.io#592]
From the changelog list of v2.2, which items are actually available on macOS ?

The option to save the slides appears in the mini-menu of that MOT window, but seems non-functional.
Getting the Station name in the Window Title ?

A little bit of explaining ( doesn't have to be a full fledged user guide ) would be appreciated.

Besides that, it's still my go to app for anything DAB. Thank you.

**Comment by mpbraendli** [comment]
Sorry that wasn't my intention!

**Comment by AlbrechtL** [comment]
Thanks for reporting!

It is duplicated see: https://github.com/AlbrechtL/welle.io/issues/582
