### ISSUE TITLE
folder depth for MOT image saving

### ISSUE THREAD

**Issue by Observerist** [AlbrechtL/welle.io#595]
Great to to be able now do target a folder.

But besides the default Home folder as used before, I can only go one level further, e.g. my Desktop can be used, but not one level deeper where a specified folder is not being validated. 

Am I correct in believing that images cannot be saved continuously as they are, one after the other, pushed on air ?
While only pictures that are already in the cache can be retrieved, as a batch if necessary ?

**Comment by andimik** [comment]
It's depending if the service you are listening to uses different file names or not.

**Comment by AlbrechtL** [comment]
> But besides the default Home folder as used before, I can only go one level further, e.g. my Desktop can be used, but not one level deeper where a specified folder is not being validated.

Which OS you are running?

>Am I correct in believing that images cannot be saved continuously as they are, one after the other, pushed on air ?

Correct

>  While only pictures that are already in the cache can be retrieved, as a batch if necessary ?

Yes

**Comment by AlbrechtL** [comment]
Closed because of inactivity.
