### ISSUE TITLE
Get the Car Information/ EPG out of the Stream?

### ISSUE THREAD

**Issue by nousername1** [AlbrechtL/welle.io#597]
Hi
Attlest in Austria 2x interesting stuff get transmit with the Audio Channel:
https://www.rtr.at/de/m/MUXI

Electronic Program Guide | ORS comm GmbH & Co KG | ZD | 12 |   |   |   |   | **0xE0A0AD50**
Verkehrsinformationen (TPEG) | ORS comm GmbH & Co KG | ZD | 6 |   |   |   |   | **0xE0A0AD51**

on the other MUX:

Electronic Program Guide (EPG) | RTG Radio Technikum GmbH | ZD | 12 |   |   |   | X | **0xE0A0AD20**
Emergency Warning Function (EWF) | RTG Radio Technikum GmbH | ZD | 24(**) |   |   |   | X | **0xE0A0AD21**

Thanks

**Comment by andimik** [comment]
This page only shows what is allowed. TPEG is not used in Austria and not supported by Welle.io.

A complete overview is on http://www.fmlist.org/tpeg.php

**Comment by AlbrechtL** [comment]
About SPI see here, please: https://github.com/AlbrechtL/welle.io/issues/558
About TPEG see here, please https://github.com/AlbrechtL/welle.io/issues/501

In short: Both are no possible at the moment.
