### ISSUE TITLE
Recently committed port for FreeBSD

### ISSUE THREAD

**Issue by herrhotzenplotz** [AlbrechtL/welle.io#601]
I just submitted a port that was accepted after some debugging with a committer.
See: https://www.freshports.org/audio/welle.io/

The port can be installed by either:
+ `# pkg install welle.io`
or
+ `# cd /usr/ports/audio/welle.io/ && make install clean`
which builds it from the ports tree.

If you want me to submit a patch for the Readme that adds a note about the availability of welle.io on FreeBSD, please tell me.

Furthermore:
RTL-SDR support works just fine. I cannot test the other backends because I don't own any hardware in order to do so. Those are left as options when building the port and are not included when installing the binary package.

**Comment by AlbrechtL** [comment]
Thank you very much!

An update of the README would be helpful.
