### ISSUE TITLE
QtQuickControls and QtQuickControls2 both required?

### ISSUE THREAD

**Issue by russel** [AlbrechtL/welle.io#62]
At least on Fedora Rawhide, it seems both QtQuick.Controls and QtQuick.Controls2 are required for the UI to run. Is this correct?

**Comment by AlbrechtL** [comment]
Honestly I don't know it. I didn't spent time to check which module is required and which isn't. Is there is a issue with these modules?

**Comment by russel** [comment]
Best leave this until it crops up again I think; it's not a big issue.
