### ISSUE TITLE
SoapySDR arguments ignored when using SoapyRemote

### ISSUE THREAD

**Issue by varette** [AlbrechtL/welle.io#634]
Arguments like `remote:window` are not having any effect. Welle.io passes the arguments to `SoapySDR::Device::make()`, however these are only used for finding the device and then discarded, they are not passed on to the stream. Soapy seems to expect them to be passed to `device->setupStream()`

**Comment by varette** [comment]
The above PR fixes the issue for me.

**Comment by mpbraendli** [comment]
Hi, thanks for the contribution. I'm closing the issue, and we can continue the discussion in the pull request.
