### ISSUE TITLE
homebrew formula broken due to qt 6.x upgrade

### ISSUE THREAD

**Issue by mitchblank** [AlbrechtL/welle.io#643]
Today homebrew updated the default `qt` component to be qt 6.x: https://github.com/Homebrew/homebrew-core/commit/ab9d906d072fb2c5ba6ca30b23cb3136e42de6c1#diff-b2ec9c6219affd12bbe8251dcee4a10c9b2f0eceed6ff7bae4b391616d1f610a

This seems to have broken the official welle.io homebrew formula:
```
==> Downloading https://github.com/AlbrechtL/welle.io/archive/v2.0.tar.gz
==> Downloading from https://codeload.github.com/AlbrechtL/welle.io/tar.gz/v2.0
##=O#- #
==> Reinstalling albrechtl/welle_io/welle.io
==> cmake . -DRTLSDR=TRUE -DSOAPYSDR=TRUE -DBUILD_WELLE_CLI=OFF
Last 15 lines from .../Library/Logs/Homebrew/welle.io/01.cmake:
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/tmp/welle.io-20210302-86156-1sfohdl/welle.io-2.0/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so to (not Homebrew/brew or Homebrew/core):
  albrechtl/welle_io

Error: Validation Failed: [{"message"=>"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.", "resource"=>"Search", "field"=>"q", "code"=>"invalid"}]
```

There is a `qt@5` formula that the package could point to as a dependency instead if it isn't 6.x ready: https://github.com/Homebrew/homebrew-core/commit/67e7aa02813056543f2d31dcd643e7418eb329cb#diff-bba851c8a71e26f2969ad46028a9abcd0b1dd552f18c42ccb922c112bf065099

However I also noticed that the homebrew formula installs welle.io 2.0 instead of the current 2.2 so is it even still maintained?

**Comment by mitchblank** [comment]
OK, opened a PR.  I would have started with that but since the formula was also out-of-date wrt the version it installs I wanted to make sure that it isn't abandoned or something.

I don't have my rtl_tcp setup running at the moment so I can't really test the results, but the UI opens so it's probably OK

**Comment by AlbrechtL** [comment]
Thanks!
