### ISSUE TITLE
Request: Use annotated tag for next release

### ISSUE THREAD

**Issue by marcusmueller** [AlbrechtL/welle.io#644]
A lot of things, especially `git describe`, but also integrations in automatic packagers etc, rely on "annotated" tags.

So, if you happen to want to release 2.3, for example, you'd run

`git tag -a v2.3`

and then get the chance to give that release a title (I always just use a simple "Release 2.3") and description (where I often just paste the changelog since the last release, but nobody's forcing you to put anything). 

The big bonus is that `git describe` then would inform you that e.g. the current commit on `master` is `v2.2-2-gd34b3fc`.
Guess what you then can use in CMake so that you don't need any `githash` env variable or `cmake -D` or such!

`git show v2.3` would then tell the interested party what the changelog says. And, admittedly, my shell's prompt line would also look mighty fancy with that!

**Comment by AlbrechtL** [comment]
Thanks for the hint!

I'm using the GitHub release management to tag it. I agree that the usage of `git describe` would nice. But my days has only 24 h and this project is just a hobby project and thus I cannot spend too much time to it.
