### ISSUE TITLE
AUDIO OUTPUT ISSUE

### ISSUE THREAD

**Issue by aidandorc** [AlbrechtL/welle.io#647]
Hi guys
I've successfully compiled and setup welle-cli on a raspberry pi 2.
The pi is connected via audio port (jack 3,5) to an external amplifier.
If I use an ssh session to input welle-cli command to tune a station, the audio is correctly redirected to the audio port and so to the ext amp.
But if I input the command to start the web server only (e.g. welle-cli -w 80) so to manage the radio stations from my pc in a more comfortable way, when I select a station to play from the list the audio is redirected to my pc using I presume the http session and no to ext amp.
Is not possible to say to welle to use always by default the Pi audio port?
Thanks in advance for your help..
Bye

**Comment by mpbraendli** [comment]
Hello,
This was never the purpose of the web server. Interesting scenario though!
You might instead run welle.io on the raspberry and connect to it using VNC.
Cheers
