### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by z8rsvenbergner** [AlbrechtL/welle.io#649]
`brew install AlbrechtL/welle_io/welle.io`

says after a while:
```
remote: Repository not found.
fatal: repository 'https://github.com/albrechtl/homebrew-welle_io/' not found
```

**Comment by AlbrechtL** [comment]
Is this issue still existing?

**Comment by z8rsvenbergner** [comment]
Issue solved.

`==> Tapping albrechtl/welle_io
Cloning into '/usr/local/Homebrew/Library/Taps/albrechtl/homebrew-welle_io'...`
