### ISSUE TITLE
[welle-cli] Feature request: get time from DAB

### ISSUE THREAD

**Issue by nanderer** [AlbrechtL/welle.io#654]
it would be nice if there would be some way to get the world clock time from DAB+ so i can adjust my computers rtc without internet or manual input...

sth like
```
sudo date --set=`welle-cli -time-output`
```

Thanks a a lot and keep up the good work

**Comment by AlbrechtL** [comment]
Indeed this could be a feature for welle-cli. But our interest it not to use DAB as an clock provider. In Europe I recommend DCF77 for it or globally GNSS.

But pull request are welcome!

For now I'm closing it.
