### ISSUE TITLE
Feature request: option to disable overlay on MOT sliedeshow

### ISSUE THREAD

**Issue by nanderer** [AlbrechtL/welle.io#655]
hi,

![image](https://user-images.githubusercontent.com/45161625/118372846-d4dda100-b5b3-11eb-81ce-d33607ef9b67.png)

pro features are nice but i would like to have an option to remove the 3 lines at the bottom right without disabling the export mode completely, maybe add an option to the three dot menu just below the save all images option like "disable details overlay" or "enable details overlay" depending on its current state.

thanks a lot in advance and keep up the good work

**Comment by AlbrechtL** [comment]
It was already removed in https://github.com/AlbrechtL/welle.io/commit/6170d464c4affa2086bea41a4d6395651cff932e.

Please try again the latest nightly version or build it from the next branch.
