### ISSUE TITLE
nightlies

### ISSUE THREAD

**Issue by Observerist** [AlbrechtL/welle.io#658]
Where are the nightlies gone, now that the present site indicates the end of the bintray presence for welle.io ?.

**Comment by andimik** [comment]
The (new) link is - of course - mentioned in the Readme. Albrecht had to move it recently.

https://welle-io-nightlies.albrechtloh.de/

**Comment by Observerist** [comment]
Happy with the new location of the nightlies. 
Latest build 2021-05-22 21:32:34 is a great version, with a volume slider that makes welle usable without insertion of the "Audio Hijack" app (Rogue Amoeba). No more audio overload. Thanks for upping the ante each time..
