### ISSUE TITLE
[welle-cli] Scan all muxes and create playlist for media players

### ISSUE THREAD

**Issue by renne** [AlbrechtL/welle.io#659]
Scanning all muxes and creating a real-time M3U8-playlist on the the web-server would allow to use any HTTP/MP3 capable media-player or media streamer to work with welle-cli.

**Comment by mpbraendli** [comment]
Cool idea, I implemented that quickly, and it works with VLC.
Only one caveat: welle-cli doesn't know how it is reachable, so it cannot prefix the entries' URLs with "http://XYZ/" and the m3u contains only "/mp3/SID". Maybe that won't work everywhere.
