### ISSUE TITLE
Welle.io uses English in Austria under Windows

### ISSUE THREAD

**Issue by andimik** [AlbrechtL/welle.io#66]
Users in Austria (like me) get an English Welle.io as the language code for (Austrian) German is not found. I suggest to let the program look for de_??, not de_DE.

> main: Detected system language "de_AT"
> main: Set language "de_AT"
> main: Error while loading language "de_AT" use English "en_GB" instead

As soon as I change the main language to Deutsch (Deutschland) in the system panel, then I get it in German, indeed.

I fear this might also be the case for Switzerland (German, Italian and French) and Belgium.

**Comment by AlbrechtL** [comment]
Fixed in c2d5645. Will be included in the next release.
