### ISSUE TITLE
Switching stations resets the volume to 100% 

### ISSUE THREAD

**Issue by Annunaki** [AlbrechtL/welle.io#664]
Output volume is reset to 100% when tuning to different stations, however, the Volume Slider remains at where it was set.

**Comment by AlbrechtL** [comment]
Thanks for reporting!

**Comment by AlbrechtL** [comment]
Is this bug is till occurring?

**Comment by SergeantSerk** [comment]
Interestingly, I stumbled on this issue right now and was about to start an issue. Yes it is still occurring.

Switching stations resets the volume to 100% but the slider remains in the same position.

**Comment by AlbrechtL** [comment]
Thanks for testing! Bug fix pull request are welcome!

**Comment by mdmitry** [comment]
Still not fixed in 2024

**Comment by AlbrechtL** [comment]
The described issue I can't reproduce. But I found another issue that the volume was always 100% after mute that is fixed here https://github.com/AlbrechtL/welle.io/commit/86a6fdad9b9eb44b47bf74564cacdec6a5d8ccd4.

Can you try it with this version (https://welle-io-nightlies.albrechtloh.de/20241008_86a6fdad_Windows_welle-io-setup_x64.exe), please?
