### ISSUE TITLE
fixed frequency offset correction 

### ISSUE THREAD

**Issue by julianwue** [AlbrechtL/welle.io#668]
Change of channels is very slow. I found out, welle always makes a new scan for the offset in Hz with every change in channel. Within all channels I see the same value about -3500Hz, so it would be more stable to have a fixed value for correction and skip the algorithms.

(Useage of welle.io_2.3_macOS.dmg)

**Comment by AlbrechtL** [comment]
Thanks for the idea! Unfortunately optimizations like that are not easy to implement as you think and we have much more important topics where we would like to spend our time. But pull request are welcome!

For now I'm closing it.
