### ISSUE TITLE
UI Improvement: Filter with ensemble in dropdown menu

### ISSUE THREAD

**Issue by julianwue** [AlbrechtL/welle.io#669]
UI Improvement:
Make for every Ensemble a list entry in dropdown - Based on Channel. Next to "Alle Sender" and "Favoriten".

![filter_ensemble](https://user-images.githubusercontent.com/1277493/126877120-75fce696-6959-447c-b8b3-f6d0418d1ee8.png)

**Comment by tenzap** [comment]
Would #487 and #419 fit your needs ?

**Comment by julianwue** [comment]
> Would #487 and #419 fit your needs ?

yes, same issue. One easy solution to use the channel as filter name.

**Comment by AlbrechtL** [comment]
FYI: I'm proposing a possible solution here: https://github.com/AlbrechtL/welle.io/issues/487#issuecomment-2563988969
