### ISSUE TITLE
Floating text for Credits (under Help) 

### ISSUE THREAD

**Issue by andimik** [AlbrechtL/welle.io#67]
It makes sense to have the text for the credits as floating text as there is an automatic word wrap, indeed.

**Comment by AlbrechtL** [comment]
You can do this and send me a pull request.  

You can find the text in [AUTHORS](https://github.com/AlbrechtL/welle.io/blob/0e258bb87957a0ec4ecc4be412529ac203fba488/AUTHORS) and [COPYING](https://github.com/AlbrechtL/welle.io/blob/0e258bb87957a0ec4ecc4be412529ac203fba488/COPYING). To enable or disable word wrap play with [line 20 in InfoPage.qml](https://github.com/AlbrechtL/welle.io/blob/0e258bb87957a0ec4ecc4be412529ac203fba488/src/gui/QML/InfoPage.qml#L20).

Official QT documentation for wrap mode: https://doc.qt.io/qt-5/qml-qtquick-text.html#wrapMode-prop.

**Comment by andimik** [comment]
See Pull request #84
