### ISSUE TITLE
Issue using welle.io through open auto

### ISSUE THREAD

**Issue by Danep82** [AlbrechtL/welle.io#672]
Hello I'm not sure if someone can help me, I'm running open auto on a raspberry pi4, the welle.io version was outdated and wouldn't see my dab dongle so I followed the guide to upgrade it, if I run the new version of welle.io directly from the file it opens perfectly and works with my dongle but if I try to open it via the applications in open auto it won't open at all, any ideas I've changed the path in open auto to the new version !

Many thanks

**Comment by AlbrechtL** [comment]
Some of the open auto developers should answer this question. I don't have open auto so I can't help you - sorry!
