### ISSUE TITLE
Alter frequency / Add channel in config or command line

### ISSUE THREAD

**Issue by mattaperkins** [AlbrechtL/welle.io#673]
Hi, 
 Is there a way to alter the centre frequency or add a new channel on the command line or in a config file.  Other then altering the source code. I have not found a way.  
 
 I would like to use another frequency in the Amateur Radio 70cm band.

**Comment by andimik** [comment]
https://github.com/AlbrechtL/welle.io/blob/f97165367458cc6b079dfe6b9113405fecfb28be/src/various/channels.cpp is the code.

Do you want to modify it for cable DAB radio?

**Comment by mattaperkins** [comment]
Yes I have modified that part of the code to do some experimentation to use welle.io on Amateur Radio  frequency's. However i could not find anything that would allow perhaps to set the frequency on the command line or type it in directly.  It appears to work however I have not setup my transmitter yet to test the decoding. 
Matt

**Comment by andimik** [comment]
Are you sure you will find DAB on amateur radio frequencies?

If you already modified this code you can select the new channel in the expert view.

**Comment by mattaperkins** [comment]
Yes im the one going to be broadcasting it. :)  I wanted an easy to use good piece of software for other amateurs to receive the DAB+ broadcast. 

Kind regards
Matt

**Comment by AlbrechtL** [comment]
Interesting application. How often is DAB broadcasted over HAM radio frequencies?

**Comment by AlbrechtL** [comment]
Closed because of inactivity.
