### ISSUE TITLE
Record button to welle.io

### ISSUE THREAD

**Issue by aerogus** [AlbrechtL/welle.io#677]
It's a feature request:
In the interface (maybe in the header next to play/stop and volume) would it be possible to add a record button to the stream we are listening ?

I know we can do it with `welle-cli` (ex: `welle-cli -c 11B -D`) but it records in .WAVs the whole ensemble. Maybe there is a trick to record only a service in the mux with a specific parameter ? (I did'nt find it after having read the source)

**Comment by AlbrechtL** [comment]
Please see here https://github.com/AlbrechtL/welle.io/issues/36.
