### ISSUE TITLE
[Windows] Installation under Windows in same directory not possible

### ISSUE THREAD

**Issue by andimik** [AlbrechtL/welle.io#680]
If I want to update the existing installation by downloading latest nightly build and start the setup, it fails as there is already a directory existing.

![grafik](https://user-images.githubusercontent.com/24510556/135351097-38751dd9-0ba3-40e2-8492-ac0cbf4a4288.png)

So, first I have to uninstall the old version, then it works.

No idea if this is a bug or feature ...

**Comment by AlbrechtL** [comment]
It is more an enhancement. It should be possible to update the existing installation. Most likely there are scripts missing inside the installer.

**Comment by AlbrechtL** [comment]
Fixed in 2.5.
