### ISSUE TITLE
[Android] support for Airspy

### ISSUE THREAD

**Issue by catch220** [AlbrechtL/welle.io#686]
I've found Android driver for Airspy https://github.com/demantz/airspy_android and managed to connect my Airspy R0 to smartphone. I've done some test records with .apk from that repo, and it seems to be ok. But I desperately need something to make the realtime spectrum.

Can you possibly add the Airspy support in Android app using that driver?

**Comment by AlbrechtL** [comment]
Great idea! Pull request are welcome!

**Comment by AlbrechtL** [comment]
Closed because of inactivity.
