### ISSUE TITLE
Dates in ISO8601

### ISSUE THREAD

**Issue by russel** [AlbrechtL/welle.io#69]
Should the date format be rendered in ISO8601 so as to avoid any confusion with the plethora of date formats around the world?

**Comment by AlbrechtL** [comment]
From my understanding QT is doing this [here](https://github.com/AlbrechtL/welle.io/blob/0e258bb87957a0ec4ecc4be412529ac203fba488/src/CRadioController.cpp#L184).
Documentation: https://doc.qt.io/qt-5/qlocale.html#FormatType-enum

**Comment by AlbrechtL** [comment]
I'm closing this issue because there is no discussion about this right now.  

If somebody would like to discuss this topic they can use this issue.
