### ISSUE TITLE
Enhancement - Node.js/Node-red implementation

### ISSUE THREAD

**Issue by hutje** [AlbrechtL/welle.io#694]
The option to get a music stream as a continuous mp3/aac would be perfect for streaming live radio to all speakers in your home.
Maybe an option to add a command to the welle-cli that sends the decoded audio as buffered parts as output or generate a tcp-port to connect to.
Then I can stream that output to Node-Red and from there the stream can be distributed to all the speakers with for example Castv2.

**Comment by AlbrechtL** [comment]
Thanks for the idea. At the moment such a interface is not on our roadmap - for that I'm closing this issue. But if anybody want to implement it - pull request are welcome!
