### ISSUE TITLE
Stuck at configuring qt5

### ISSUE THREAD

**Issue by AppLEaDaY** [AlbrechtL/welle.io#695]
Hello!

I'm using the guide at the URL below.

`https://github.com/AlbrechtL/welle.io/blob/master/RASPBERRY-PI.md`

Precisely I'm at the point where I have to issue the command reported below.
`
./configure -release -opengl es2 -device linux-rasp-pi3-g++ -device-option CROSS_COMPILE=~/raspi/gcc-linaro-5.5.0-2017.10-i686_arm-linux-gnueabihf/bin/arm-linux-gnueabihf- -sysroot ~/raspi/sysroot -opensource -confirm-license -no-use-gold-linker -make libs -prefix /usr/local/qt5pi -extprefix ~/raspi/qt5pi -hostprefix ~/raspi/qt5 -v`

I'm momentarily stuck at the error mentioned below.

```
/home/andrea/raspi/qt5/qtbase/src/corelib/global/qrandom.cpp:457:62: error: no matching function for call to ‘std::mersenne_twister_engine<unsigned int, 32, 624, 397, 31, 2567483615, 11, 4294967295, 7, 2636928640, 15, 4022730752, 18, 1812433253>::mersenne_twister_engine(QRandomGenerator::SystemGenerator&)’
  457 |         new (&rng->storage.engine()) RandomEngine(self()->sys);
      |                                                              ^
In file included from /usr/include/c++/9/random:49,
                 from /home/andrea/raspi/qt5/qtbase/src/corelib/global/qrandom.h:45,
                 from /home/andrea/raspi/qt5/qtbase/src/corelib/global/qrandom.cpp:43:
/usr/include/c++/9/bits/random.h:530:9: note: candidate: ‘template<class _Sseq, class> std::mersenne_twister_engine<_UIntType, __w, __n, __m, __r, __a, __u, __d, __s, __b, __t, __c, __l, __f>::mersenne_twister_engine(_Sseq&)’
  530 |         mersenne_twister_engine(_Sseq& __q)
      |         ^~~~~~~~~~~~~~~~~~~~~~~
```

There are other errors too, but I suspect it's worth mentioning just the first one that appears.

What am I missing?

Thanks in advance!

Andrea

**Comment by AlbrechtL** [comment]
Unfortunately `https://github.com/AlbrechtL/welle.io/blob/master/RASPBERRY-PI.md` is outdated. You can install welle.io at the latest raspeberry OS via `apt install welle.io` or by compiling it directly on the raspberry. I will update the `Readme.md` soon.
