### ISSUE TITLE
 [macOS] Travis build failed - again

### ISSUE THREAD

**Issue by AlbrechtL** [AlbrechtL/welle.io#697]
The travis macOS build is broken again. See here: https://app.travis-ci.com/github/AlbrechtL/welle.io/jobs/553714872#L2578

@orryverducci Can you have a look, please?

**Comment by orryverducci** [comment]
Looks like the build is timing out while Homebrew is updating the dependencies. The build is using an old macOS image, so we probably need to update it to a more recent one that doesn't need so many updated.

I'm working on it, but I can't get the new travis-ci.com site to sync with my GitHub repos at the moment, so you'll have to give me time to figure out why that doesn't work.

**Comment by AlbrechtL** [comment]
Thanks @orryverducci !
