### ISSUE TITLE
Add button to start initial station scan

### ISSUE THREAD

**Issue by dforsi** [AlbrechtL/welle.io#701]
Since the first thing after installing well-io is creating the station list, I would find it easier if a button or a link appeared in a prominent place, in addition to the menu item; it could appear also after the user cleared the station list, that is every time the station list is empty, and wouldn't clutter the interface when the list contains at least one station.

A mockup:
![image](https://user-images.githubusercontent.com/1055635/148430361-9558b1e4-9197-4fa8-a041-e24dcbbcba32.png)

Another mockup:
![image](https://user-images.githubusercontent.com/1055635/148431146-f79cfb3b-cc65-4e99-a263-c89c1c44ab18.png)

**Comment by AlbrechtL** [comment]
That's a pretty good point! Thanks!

Pull request are welcome!

**Comment by AlbrechtL** [comment]
Added in version 2.5.
