### ISSUE TITLE
Add compatibiliy to Qt 6.2

### ISSUE THREAD

**Issue by AlbrechtL** [AlbrechtL/welle.io#702]
At the moment welle.io is not Qt 6 compatible. Since in Qt 6.0 and Qt 6.1 modules are missing it is not possible run welle.io with it. But in Qt 6.2 all modules are available but especially the QMultimedia API changed which require changes in welle.io.

Pull requests are welcome!

**Comment by AlbrechtL** [comment]
I started the works here: https://github.com/AlbrechtL/welle.io/tree/qt_6_support

**Comment by gvanem** [comment]
The branch : https://github.com/AlbrechtL/welle.io/tree/qt_6_support is gone (?). Is it in `next`?

**Comment by AlbrechtL** [comment]
Oh yeah I already merge it into the next. Because Qt 6 support is there I will close this issue.
