### ISSUE TITLE
EPG support?

### ISSUE THREAD

**Issue by ubuntu-novize** [AlbrechtL/welle.io#704]
Some of my favorite radio stations transmit program data (like TV).
Do you plan to display this data? EPG = Electronic program guide.

**Comment by andimik** [comment]
We already have discussed this at https://github.com/AlbrechtL/welle.io/issues/558

The former EPG is called SPI.

Therefore, you might close this issue as this is a duplicate.

**Comment by ubuntu-novize** [comment]
Thank you for this info.
I read #558: to much techno speaking, to much english. Sorry, I don't understand what is discussed there...

**Comment by andimik** [comment]
Well, you could give Qt-DAB a try if you want to see what is transmitted in the mux.

Which Mux is it, and where do you live?

**Comment by AlbrechtL** [comment]
Duplicated with https://github.com/AlbrechtL/welle.io/issues/558.

Short answer. At the moment there is no EPG support available.
