### ISSUE TITLE
[Welle-gui] Spectrum waterfall frequency boundaries not consistently rounded

### ISSUE THREAD

**Issue by ggramaize** [AlbrechtL/welle.io#707]
Hi,

Tested version: welle.io version 2.3 (git rev 66675c9) QT 5.15.2

The spectrum waterfall frequency tags, which indicate the lower and upper frequencies aren't rounded consistently.
It is suggested to round those frequencies to 3 digits.

Example screen cap:
![Capture d’écran du 2022-01-19 14-41-26](https://user-images.githubusercontent.com/5450075/150144159-d346a897-1ec4-44c7-8aa1-e0236056d0ac.png)

Kind regards,

**Comment by AlbrechtL** [comment]
Thanks for your report.

Pull request are welcome!

**Comment by AlbrechtL** [comment]
Fixed in https://github.com/AlbrechtL/welle.io/commit/198eb2320d3280c976494cc48227aa28ba4726f4.
