### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by alexmyczko** [AlbrechtL/welle.io#711]
https://discourse.ubuntu.com/t/jammy-jellyfish-release-schedule/23906

before 24th feb?

**Comment by AlbrechtL** [comment]
Thanks for pointing this out! I will do my best. It would be great to have the latest version inside Ubuntu 22.04 LTS.

**Comment by AlbrechtL** [comment]
Job is done, see https://github.com/AlbrechtL/welle.io/commit/0aacf578d77d79212483cd6fce436fb66523f63f.

@alexmyczko  On Ubuntu 20.04 I had to install lib `qml-module-qt-labs-folderlistmodel` to make it fully working. Maybe it is necessary also for Debian packaging (https://sources.debian.org/data/main/w/welle.io/2.2-1/debian/control).
