### ISSUE TITLE
[Gui, Linux] 2.4, no more volume slider?

### ISSUE THREAD

**Issue by tenzap** [AlbrechtL/welle.io#714]
How to access the volume slider on 2.4? I have no more slider when I click on the speaker/volume button.

Linux: Debian bullseye (latest stable), with the released 2.4 AppImage, Qt 5.15.2

Oh... right click it seems. Is this supported on touch screens/phones? Or will it be a regression there?

**Comment by AlbrechtL** [comment]
I change the behavior.
* Left click or touch -> mute
* Right click, long left click or long touch -> open volume slider

**Comment by tenzap** [comment]
ok thanks
