### ISSUE TITLE
Consider adding AppStream metadata

### ISSUE THREAD

**Issue by AsciiWolf** [AlbrechtL/welle.io#718]
Thanks for creating this great DAB receiver, I love it! Welle.io does not seem to have any [AppStream metadata](https://freedesktop.org/software/appstream/docs/chap-Quickstart.html) on Linux. Because of this, the package cannot be found in GNOME Software, KDE Discover and other package manager UIs based on AppStream. Please, consider creating the AppStream metainfo file.

**Comment by AlbrechtL** [comment]
Thanks for the idea and the corresponding pull request!
