### ISSUE TITLE
Missing menu icons

### ISSUE THREAD

**Issue by dforsi** [AlbrechtL/welle.io#722]
Commit 1c1b7b8bcf8f7792adf5248c040dc2655c4d7e74 makes the menu icons disappear for me:
![image](https://user-images.githubusercontent.com/1055635/157735213-22f6aaee-e344-4995-be04-89cfefad7410.png)
if I revert it, in the current master 0aacf578d77d79212483cd6fce436fb66523f63f (tag: v2.4), they reappear:
![image](https://user-images.githubusercontent.com/1055635/157737601-b97006ce-3bde-40db-a317-23ee5cd12e14.png)

I'm showing only one corner, but this happens for all menus.

In both cases the icon in the tray is visible.

**Comment by AlbrechtL** [comment]
Thanks for reporting.

Duplicated with https://github.com/AlbrechtL/welle.io/issues/713
