### ISSUE TITLE
menu icons disappear

### ISSUE THREAD

**Issue by dwarning** [AlbrechtL/welle.io#725]
OS: Ubuntu 20.04 Mate, using actual git version
The 3 dots icon is not to see anymore. Clicking in the corner works - the menu pops up and is usable.
I think something went wrong with your commit 1c1b7b8bcf8f7792adf5248c040dc2655c4d7e74 from 9.9.21.
The icons are not installed in this path.
Only a assumption.

**Comment by AlbrechtL** [comment]
Duplicated with https://github.com/AlbrechtL/welle.io/issues/713
