### ISSUE TITLE
Use another form of input for rtl_tcp settings

### ISSUE THREAD

**Issue by SergeantSerk** [AlbrechtL/welle.io#727]
Using the current interface to select the IP address numbers and port is incredibly difficult. The rtl_tcp port that is currently running for me is 9999 and I'm having to scroll all the way from 1234 which is very time consuming and not user friendly.

Perhaps a simple text box to input and then do validation would be better?

**Comment by AlbrechtL** [comment]
You are right. The spinner for port setting is not really user friendly.

As a workaround you can lower you port number.

**Comment by stonedDiscord** [comment]
it works great on touch displays but with a mouse they are a real pain

ideally this should only be a spinner on android and a classic text box for all the other platforms

**Comment by andimik** [comment]
And what about splitting the 4 digits into 4 spinners?

**Comment by SergeantSerk** [comment]
Make that 5 digits since max port is 65535 :)

**Comment by AlbrechtL** [comment]
In https://github.com/AlbrechtL/welle.io/commit/466be3df9894ca9f2b4a075902f2b16f42d4ca62 I changed to rtltcp settings (see screenshot). Now you can easily use big port numbers.

![grafik](https://github.com/user-attachments/assets/00057e2c-781a-4531-a31f-814b48fd9f0b)

Feel free to test the latest unstable build: https://welle-io-nightlies.albrechtloh.de/20241009_466be3df_Windows_welle-io-setup_x64.exe
