### ISSUE TITLE
[Android ] Missing main window and expert window

### ISSUE THREAD

**Issue by andimik** [AlbrechtL/welle.io#73]
Today not even the main window and the expert window dissappeared (was grey), the exit button also was not visible. I had to rotate the mobile and then they appeared again.

![screenshot_2017-05-23-07-59-38](https://cloud.githubusercontent.com/assets/24510556/26346406/63bc168c-3fa6-11e7-946f-363a25cf4b1f.png)

**Comment by AlbrechtL** [comment]
Which mobile phone and Android version do you are using?

**Comment by andimik** [comment]
Sony Xperia Z1 Compact
Android 5.1.1 (latest version for this mobile) 

I tried to find out what caused the problem and then maybe this has to do with the graphics card 

The grey area right has the same size as the Home, back and switch buttons.

![screenshot_2017-05-23-12-33-14](https://cloud.githubusercontent.com/assets/24510556/26350735/a5fc6f0c-3fb4-11e7-9748-256d156857d0.png)

**Comment by andimik** [comment]
![screenshot_2017-05-23-12-40-00](https://cloud.githubusercontent.com/assets/24510556/26350812/fc03375a-3fb4-11e7-8a4f-ab46e2766a11.png)
At the bottom you see this grey area, same size as in the upper screenshot.

**Comment by AlbrechtL** [comment]
OK, now I understand your problem. This should be fixed in the next version. I already committed the fix (43e76be).
