### ISSUE TITLE
[Android] Reception when minimised. 

### ISSUE THREAD

**Issue by sierragls** [AlbrechtL/welle.io#733]
When i minimise the app to do something else and carry on listening to DAB the signal goes or is really weak so the app has to be constantly on screen for it to work, are there any settings to change this?

**Comment by orryverducci** [comment]
New versions of Android are very agressive when it comes to power saving and suspending/limiting background applications, so it wouldn't surprise me if welle.io is being suspended when put to the background.

To avoid being killed applications need to implement a [foreground service](https://developer.android.com/guide/components/foreground-services), which I don't believe welle.io does currently (but I've not looked deeply in to the code so correct me if I'm wrong).

**Comment by andimik** [comment]
FYI

I have Android 9

**Comment by AlbrechtL** [comment]
The Android version of welle.io is really more a technical demo with a lot of restrictions and bugs. To make it running smoothly tons of coding hours needs to be invested. At the moment nobody is spending that. But we are always open for pull request!

**Comment by AlbrechtL** [comment]
Closed because of inactivity.
