### ISSUE TITLE
[Android] RAW file not supported

### ISSUE THREAD

**Issue by andimik** [AlbrechtL/welle.io#734]
Using a raw file under Android is not supported. After selecting a raw file, the entry "Selected file:" just says the German text 'Derzeit unter Android angezeigt' which is 'Currently shown under Android' in English, that comes from this line:

https://github.com/AlbrechtL/welle.io/blob/0aacf578d77d79212483cd6fce436fb66523f63f/src/welle-gui/QML/settingpages/RawFileSettings.qml#L71
![Screenshot_20220519-194528](https://user-images.githubusercontent.com/24510556/169365264-b4e9d87e-bc70-4f4a-95fe-1e83d7b42f9c.png)
![Screenshot_20220519-194541](https://user-images.githubusercontent.com/24510556/169365282-ec3af900-f4c9-4cc4-897d-510dc1e243bb.png)

**Comment by AlbrechtL** [comment]
Thanks for reporting! I think the sentence was a quick hack to get it running under Android.

**Comment by AlbrechtL** [comment]
I'm closing this issue because support RAW files under Android is out of scope. If somebody sends a pull request I will review it.
