### ISSUE TITLE
[Android] Favorite list stays empty

### ISSUE THREAD

**Issue by andimik** [AlbrechtL/welle.io#735]
The favorite list stays empty on Android. Under Ubuntu it works.

![Screenshot_20220519-100807](https://user-images.githubusercontent.com/24510556/169245668-722ebbfc-bd69-4f5c-8580-fac838e0748a.png)
![Screenshot_20220519-100814](https://user-images.githubusercontent.com/24510556/169245688-3293c1a3-71c8-4757-94a5-4332b6cf0326.png)

Initially mentioned in #732

**Comment by AlbrechtL** [comment]
Can you check it again with the latest nightly https://welle-io-nightlies.albrechtloh.de/20221216_6b69a78c_Android_welle-io.apk?

**Comment by AlbrechtL** [comment]
Closed because of inactivity.
