### ISSUE TITLE
Don't hardcode MP2 support

### ISSUE THREAD

**Issue by bulvara** [AlbrechtL/welle.io#739]
Dear Albrecht,

I'm not interested in DAB (only DAB+), so I would like to get rid of the mpg123 dependency and its MP2 support.

Would this be possible?

**Comment by aerogus** [comment]
I made a (very) light fork of welle.io. It's CLI only and customised for my needs. I also want to be DAB+ only compatible, so no need for MP2 support.
Here is the project: https://github.com/aerogus/welle-cli

**Comment by AlbrechtL** [comment]
@bulvara What is your use case behind to get rid of mpg123? Do you want to safe some speace?

**Comment by AlbrechtL** [comment]
Closed because of inactivity.
