### ISSUE TITLE
Lubuntu Linux 22.04 LTS no stations found

### ISSUE THREAD

**Issue by ruppert-frederick** [AlbrechtL/welle.io#746]
Hello AlbrechtL,
Lubuntu Linux 22.04 LTS no stations found
Installed via apt install welle.io versus software store
Using a USB RTL2838U device that is detected in the service details.
When start station scan the percentages go to 100%. Channel LP frequencies are displayed in MHz during the scan on the service details window in expert mode. However no stations are found...

welle.io version: 2.2 
Git revision: 8fc5739
Built on: 2020-08-22T20:57:00
QT version: 5.15.3

Same USB RTL2838U device does work for DVB-T and plays fine.
Thank you and all the best,
Ruppert

![welle io_screen](https://user-images.githubusercontent.com/109545705/179570944-9884de72-72b3-4bd8-818f-d10003aadd50.jpg)

**Comment by AlbrechtL** [comment]
@ruppert-frederick I expect that you have a low reception. What you can do is to tune manually to a konwn channel e.g. 5C in Germany and to enable the spectrum. I you don't see a spectrum like @andimik then you don't have a good reception. Please improve our antenna in this case.
