### ISSUE TITLE
[Windows Setup] Installer hangs when UAC fails

### ISSUE THREAD

**Issue by stonedDiscord** [AlbrechtL/welle.io#760]
Steps to reproduce:
Run the installer as a regular user
Click next
When the UAC dialog pops up, click No

Result:
Installer throws an error and then hangs

Expected Result:
The installation fails and lets the user retry.

**Comment by AlbrechtL** [comment]
Which version did you try?

**Comment by stonedDiscord** [comment]
https://github.com/AlbrechtL/welle.io/releases/download/v2.4/welle.io_2.4_Windows_Setup.exe

**Comment by AlbrechtL** [comment]
Thanks for the report!

**Comment by AlbrechtL** [comment]
I'm closing this issue because I'm not sure if it is still relevant. If it still occurs in the latest version, we can reopen it.

**Comment by stonedDiscord** [comment]
The new installer doesn't have this issue anymore, setup will simply not start if denied the UAC
