### ISSUE TITLE
Compile next branch welle-cli requires qt6

### ISSUE THREAD

**Issue by SzymonZy** [AlbrechtL/welle.io#766]
Hello

I'm trying to compile welle-cli on "Ubuntu 22.04 LTS" but it reuqires qt6 libraries. Why do we need qt6 for cli at all?

**Comment by SzymonZy** [comment]
Ok, dependecis

**Comment by mpbraendli** [comment]
QT6 should not need to be installed if you only want to compile welle-cli. If `BUILD_WELLE_IO` is `OFF`, it should compile without QT installed.
