### ISSUE TITLE
RaspberryPI 3 läuft nicht

### ISSUE THREAD

**Issue by theMagicKnight** [AlbrechtL/welle.io#769]
Wie in der Readme vorgegangen, die Pakete installiert und dann mit git heruntergeladen.

die .pro datei geöffnet mit QT Creator aber es kommen nur Fehler beim Kompilieren.

Kann ich eine Fehlerlog Datei erstellen?

danke

**Comment by AlbrechtL** [comment]
You can install welle.io directly on Raspberry OS via apt install welle.io. There is no need for self compiling.
