### ISSUE TITLE
radiodns support

### ISSUE THREAD

**Issue by starman316uk** [AlbrechtL/welle.io#773]
Enhancement/Feature

Welle.io to display station logos like here

https://www.radiodns.uk/logos

**Comment by AlbrechtL** [comment]
We already have some discussions here https://github.com/AlbrechtL/welle.io/issues/558. 

Pull request are welcome!

**Comment by AlbrechtL** [comment]
I'm closing this issue because the DAB data services are not in the focus right now.

If somebody provides a PR, that would be fantastic!
