### ISSUE TITLE
Adding the 3D view from headunit-desktop

### ISSUE THREAD

**Issue by viktorgino** [AlbrechtL/welle.io#78]
![headunitdesktop2](https://cloud.githubusercontent.com/assets/11317234/26691199/29abc9a6-46f4-11e7-9ea7-e3b50052ddfa.png)
![headunitdesktop1](https://cloud.githubusercontent.com/assets/11317234/26691198/2975c662-46f4-11e7-80af-00a7b0717005.png)

**Comment by AlbrechtL** [comment]
This looks great! A totally different approach to select a station. It could be a fantastic addition to the existing once.
Inside the colored rectangle we can also put the station logo. But for this a small picture database is necessary.

**Comment by viktorgino** [comment]
Haven't implemented it yet, but I want to load the MOT slideshow in the current channels rectangle. As for the logo, there could be a folder where the user can put the logos and the app can look for the file looking its station name.

**Comment by viktorgino** [comment]
Would you like this GUI optional or have it as the only GUI?

**Comment by AlbrechtL** [comment]
> [...] but I want to load the MOT slideshow in the current channels rectangle

Also a great idea.

> Would you like this GUI optional or have it as the only GUI?

Difficult question. For now I think this could be optional. But lets see... If your 3D GUI is more sophisticated than the existing once why not to switch? To maintain one GUI is better then to maintain two GUIs.

**Comment by viktorgino** [comment]
Please see: https://github.com/AlbrechtL/welle.io/pull/80
What I haven't integrated yet is the MOT slideshow and the radio station art

**Comment by AlbrechtL** [comment]
I closed it because the 3D GUI is not ready yet. But we can use this issue to discuss the nice 3D GUI.

**Comment by viktorgino** [comment]
Created a new [pull request](https://github.com/AlbrechtL/welle.io/pull/99).

I might go ahead and make one settings page (I rewrote it for the 3D layout), just to remove redundancies and make code maintenance easier.
