### ISSUE TITLE
Building welle for Android

### ISSUE THREAD

**Issue by mesiramazani** [AlbrechtL/welle.io#784]
Hello,
I've been trying to build welle for Android with little success so far as I've been receiving the following error:

`17:01:46: Führe Schritte für Projekt welle.io aus...
17:01:46: Starte: "/home/upcadmin/Qt/6.5.0/android_armv7/bin/qmake" /home/upcadmin/welle-io/welle.io.pro -spec android-clang CONFIG+=debug CONFIG+=qml_debug
17:01:46: Der Prozess "/home/upcadmin/Qt/6.5.0/android_armv7/bin/qmake" wurde normal beendet.
17:01:46: Starte: "/home/upcadmin/Android/ndk/25.1.8937393/prebuilt/linux-x86_64/bin/make" -f /home/upcadmin/build-welle.io-Android_Qt_6_5_0_Clang_armeabi_v7a-Debug/Makefile qmake_all
cd src/welle-gui/ && /home/upcadmin/Qt/6.5.0/gcc_64/bin/qmake6 -o Makefile /home/upcadmin/welle-io/src/welle-gui/welle-gui.pro -qtconf /home/upcadmin/Qt/6.5.0/android_armv7/bin/target_qt.conf -spec android-clang CONFIG+=debug CONFIG+=qml_debug
Project MESSAGE: Current git hash = 5481d57e
Project MESSAGE: BUILD_DATE = 1661450706
**Project ERROR: Unknown module(s) in QT: androidextras**
make: *** [/home/upcadmin/build-welle.io-Android_Qt_6_5_0_Clang_armeabi_v7a-Debug/Makefile:40: sub-src-welle-gui-qmake_all] Fehler 3
17:01:46: Der Prozess "/home/upcadmin/Android/ndk/25.1.8937393/prebuilt/linux-x86_64/bin/make" wurde mit dem Rückgabewert 2 beendet.
Fehler beim Erstellen/Deployment des Projekts welle.io (Kit: Android Qt 6.5.0 Clang armeabi-v7a)
Bei der Ausführung von Schritt "qmake"
17:01:46: Verstrichene Zeit: 00:00.`

Apparently, the module qt.androidextras seems to be missing from my system. I can't seem to find this module anywhere in Qt Creator or the maintenance tool to install it.

These are my current system settings:
- Ubuntu 20.04 64 Bit
- Java version openjdk 17.0.6
- QtCreator 10.0.1 based on Qt 6.5
- Android SDK Version 9.0
- Android NDK Version 25.1.8937393

Running/Building other android APK files works without any problems.
Does someone have any ideas?

**Comment by AlbrechtL** [comment]
Please install the Qt androidextras modules.
See `Project ERROR: Unknown module(s) in QT: androidextras** `
