### ISSUE TITLE
[Raspberry Pi] RTL-SDR doesnt get reqognised by welle.io

### ISSUE THREAD

**Issue by TheHackerBoi-apk** [AlbrechtL/welle.io#790]
![grafik](https://github.com/AlbrechtL/welle.io/assets/70807223/fe5053d7-4b65-4e3e-8cd9-96585647da4e)

i have also installed the「 librtlsdr0 librtlsdr rtl-sdr」 packages and the application has been compiled from this GitHub repo directly i did use the cmake argument for rtl-sdr.
The adapter also works on my other amd64 Linux machine w/o issue (AUR install).

This is also the OpeanAuto Pro image (i have kept the original preinstalled welle.io V1.0 which suffers from the same issue).

**Comment by davidea72** [comment]
try to run from a shell with sudo, to get the root permission, if it's ok, then you must create the rtl-sdr.rules file to enable the standard user to gain access to the usb stick

**Comment by launacorp** [comment]
try https://github.com/osmocom/rtl-sdr/blob/master/rtl-sdr.rules

copy to /etc/udev/rules.d/98-rtl-sdr.rules

**Comment by andimik** [comment]
@TheHackerBoi-apk

Did this solve the problem? If yes, please close the issue.
