### ISSUE TITLE
Looses signal exactly on the hour

### ISSUE THREAD

**Issue by DavidGoodenough** [AlbrechtL/welle.io#792]
I use Welle.io to listen to BBC Radio 3, 4 and WorldService.  Normally these work perfectly (thank you), but occasionally, and it is always exactly on the hour, it looses sync and what you get sounds like rather spiky static.

I am using 2.4 as packaged by Debian Sid.

Pressing Stop and then Play works every time to fix the problem.

Is there any way to get any debug information?

**Comment by andimik** [comment]
BBC uses reconfiguration. This issue was described three years ago in https://github.com/AlbrechtL/welle.io/issues/587 but it is unsolved.

Therefore, please use another tool if possible, like https://github.com/KejPi/AbracaDABra

**Comment by DavidGoodenough** [comment]
I tried anbracadbra but it fails to.load any of the national BBC channels

**Comment by AlbrechtL** [comment]
Yes, duplicated with https://github.com/AlbrechtL/welle.io/issues/587.
