### ISSUE TITLE
Icons are missing (2.4 Appimage)

### ISSUE THREAD

**Issue by flux242** [AlbrechtL/welle.io#796]
Please put missing icons back

https://imgur.com/hUEuWgw.png

**Comment by AlbrechtL** [comment]
Duplicate with https://github.com/AlbrechtL/welle.io/issues/713. Can you try the latest nightly please? https://welle-io-nightlies.albrechtloh.de/

**Comment by flux242** [comment]
> Duplicate with #713. Can you try the latest nightly please? https://welle-io-nightlies.albrechtloh.de/

no, I can't. There's no AppImage available there
