### ISSUE TITLE
output device null

### ISSUE THREAD

**Issue by Ale268** [AlbrechtL/welle.io#799]
Hello everyone

Thanks for the great software, sadly i cannot get it to run properly on my Raspberry 4.

It does not detect an audio output. The used soundcard is a hifiberry dac+ dsp connected via I2S.

The OS is Raspberry OS with ALSA for Audio management. 

Info:
    RaspiOS: 11.9 Bullseye 64-bit
    Linux kernel: 6.1.21 64-bit
    Pi model: Pi-4B 1.5 4GB
    MPD version: 0.23.14

![grafik](https://github.com/AlbrechtL/welle.io/assets/46281437/0061108a-8174-4e6c-9201-15c7093d7035)
![grafik](https://github.com/AlbrechtL/welle.io/assets/46281437/c9a98036-9367-4e20-a184-14f9919589ed)

Any Idea on how to fix this?

**Comment by mpbraendli** [comment]
What's the output of `aplay -L` ?

**Comment by Ale268** [comment]
Hello there I found the issue, the installation of pulseaudio fixed it.
Though, depending on the user it does work or not. 

If I start welle io as sudo it won't output whilst if I start it as PI it works.
