### ISSUE TITLE
Does anyone know how to this program to work with new RTL V4 dongle

### ISSUE THREAD

**Issue by djpoole** [AlbrechtL/welle.io#804]
Does anyone know how to this program to work with new RTL V4 dongle 
![welle ioRTL Dongle not working](https://github.com/AlbrechtL/welle.io/assets/108032638/0b61ac2a-5a1a-420e-81d4-b531663639d6)

**Comment by sierra1964** [comment]
I have the same problem. He finds a lot of stations, but he only plays the respective station briefly and then there is silence. (interruption)

**Comment by mpbraendli** [comment]
Have you tried with a manual gain setting?

**Comment by sierra1964** [comment]
Unfortunately there is no setting option for this. At least I didn't find it. It finds a lot of channels (depending on the antenna) but no matter what you enter in the expert setting, it doesn't work correctly. As if the reception was too weak. I have at least 18 channels directly in my area. With SDR V3 or V5 it works for me.

**Comment by AlbrechtL** [comment]
It seems that the RTL V4 creates some trouble.

Here is another non-working report: https://github.com/AlbrechtL/welle.io/issues/797
But here is an working report: https://github.com/AlbrechtL/welle.io/issues/793

**Comment by rkarikari** [comment]
![BlogV4_](https://github.com/AlbrechtL/welle.io/assets/115777368/a587b897-1685-44ee-bee9-2ddc3a7e6bc9)
![welle-io_andriod1](https://github.com/AlbrechtL/welle.io/assets/115777368/cde6900f-95a7-413c-be38-38e456c113a4)
![welle-io_android2](https://github.com/AlbrechtL/welle.io/assets/115777368/e00a180a-c45b-47b2-a3d5-5239ad5c6413)
![welle-io_android3](https://github.com/AlbrechtL/welle.io/assets/115777368/bf4b7b87-7785-42cc-af65-4ab952b0e13f)


The snapshots above are from my android device.

Works perfectly for me.


The key is to go to .....
 "expert  settings"  and enable "expert mode". 

*** Make sure "Enable course corrector" is active. ***


I only have the Blog V4 dongles and they all work perfectly!
Have it working on all devices .... macbook, pc, android.

In sdrAngel, there's stuttering so I prefer to use welle.io

**Comment by AlbrechtL** [comment]
Thanks for reporting. I updated the rtlsdr library. Can you try that latest developer version https://github.com/AlbrechtL/welle.io/actions/runs/10662651268/artifacts/1881000078, please.

**Comment by rkarikari** [comment]
<img width="968" alt="wellle io_4" src="https://github.com/user-attachments/assets/401ca929-19aa-4eab-aa8b-c9a286a120ad">
<img width="923" alt="wellle io_2" src="https://github.com/user-attachments/assets/95fece6b-249b-4afb-b6b7-bfa83ee5cab8">

Deleted the old version I had and installed latest dev. version.
working well for me ..

**Comment by rkarikari** [comment]
fyi .. the android version dated 20240830 gives the following error on android13
![SmartSelect_20240902_103230_Package installer](https://github.com/user-attachments/assets/c39555cb-1155-49d4-b764-66bb1da1e7ca)

**Comment by andimik** [comment]
Strange, I even can't install this version on Android 9

**Comment by AlbrechtL** [comment]
> Deleted the old version I had and installed latest dev. version.
> working well for me ..

Thanks for the feedback

@rkarikari, @andimik Regarding the Android version open a new issue please.

**Comment by AlbrechtL** [comment]
The new RTLSDR Windows driver will be included in the upcoming 2.5 release.

**Comment by AlbrechtL** [comment]
Unfortunately, have had to replace the rtl-sdr driver again because of this issue https://github.com/rtlsdrblog/rtl-sdr-blog/issues/56.

In this https://welle-io-nightlies.albrechtloh.de/20241008_ee183ef7_Windows_welle-io-setup_x64.exe unstable build the latest original rtlsdr driver is included. Can you test again, please?
