### ISSUE TITLE
Buttons are missing in the GUI in Fedora 38

### ISSUE THREAD

**Issue by pierpaolo1** [AlbrechtL/welle.io#806]
I am attaching a screenshot.
Once you know where buttons are, all is fine.
B.R.
Pierpaolo
![Schermata del 2024-04-09 13-28-50](https://github.com/AlbrechtL/welle.io/assets/140967/fd7f2f3b-f95c-4fe6-92b5-1a0eff485d49)

**Comment by AlbrechtL** [comment]
Duplicate with https://github.com/AlbrechtL/welle.io/issues/713

Please try https://welle-io-nightlies.albrechtloh.de/20221214_96744b30_Linux_welle-io-x86_64.AppImage

**Comment by pierpaolo1** [comment]
Thank you Albrecht,
I moved your appimage to /usr/bin/welle-io and now it works.
Pierpaolo

Il giorno sab 20 apr 2024 alle ore 11:38 Albrecht Lohofener <
***@***.***> ha scritto:
