### ISSUE TITLE
Streaming to Sonos?

### ISSUE THREAD

**Issue by Ziltoidium** [AlbrechtL/welle.io#807]
Hello, i am interested in running welle.io remote on a raspberry, that would be located kind of remote at my garage, equipped with an external antenna at the wall.  The pi is connected by cable (LAN).

Would it be possible to play radio not only by the welle software on my laptop, but just to create a stream or m3u, so that i could use this for my sonos system?

Kind of custom stream
https://support-de.denon.com/app/answers/detail/a_id/6012/~/add-custom-radio-station-streaming-url-to-heos

The idea behind is, that i could listen to radio even if my internet connection would be down.  not on my laptop, but on any device, main at my sonos.

anyone ever did this?
Thanks!

**Comment by AlbrechtL** [comment]
Please try `welle-cli`. See here https://github.com/AlbrechtL/welle.io?tab=readme-ov-file#welle-cli
