### ISSUE TITLE
HE-AAC v2 stations shown as Mono

### ISSUE THREAD

**Issue by es5nhc** [AlbrechtL/welle.io#81]
Greetings. I am writing to bring your attention to something that I just observed on at least the Android version of welle.io. During a strong tropospheric ducting this morning I was able to pick up Latvian DAB+ test on my SDR dongle and I noticed that the services which are transmitted at 64 kbps with HE-AAC v2 were marked as Mono. Meanwhile, my Technisat Techniradio 1 as well as Wavesink app both said the channels were SBR+Parametric Stereo(indicating HE-AAC v2). Attached is a screenshot from the Android app. The version on the phone is 1.0-alpha, Build on: Sat May 20 2017 14:49:07. 
![screenshot_20170606-090034](https://cloud.githubusercontent.com/assets/4496818/26826973/c07db196-4ac3-11e7-8fb4-0deab89854dd.png)

If you have any further questions, feel free to let me know

**Comment by AlbrechtL** [comment]
If possible please record a [RAW file](https://www.welle.io/devices/rawfile#record-an-u8-raw-file) and provide it to use.

**Comment by es5nhc** [comment]
I will try to record an I/Q dump with SDRTouch (hard disk on the computer is too slow for anything good longer than a few seconds) next time there is a tropo opening. This might take time as I am 195 km from the transmitter and therefore have no regular reception.

**Comment by viktorgino** [comment]
@es5nhc How big of an antenna are you using? You can pick up some nice directional antennas online that should help you get a better reception.

**Comment by es5nhc** [comment]
In this case I was using my 4 element DK7ZB for 2m band. The multiplex is also only transmitting at 1.5 kW AFAIK.

**Comment by nottledim** [comment]
BBC3 (classical music) always shows mono too.  But qt-dab has same problem.

**Comment by andimik** [comment]
But this is old DAB. It is 192 kBit mp2 at PL 3

Can be tested via Satellite. http://www.fmlist.org/sendertabelle/dab-ww_more.php?inputLand=G&inputEn=CE15 and the stream is I guess also at http://tipok.org.ua/node/46

**Comment by AlbrechtL** [comment]
Can you provide a [RAW file](https://www.welle.io/devices/rawfile#record-an-raw-file) please?

**Comment by es5nhc** [comment]
Re: UK issue, I can confirm. I just found it on a WAV file that I recorded in the UK last month. Additionally I was unable to decode DLS while there, including on this multiplex.

https://drive.google.com/file/d/0Bz0aEk5iHH62T0VVYTBMeXRlck0/view?usp=sharing

Probably should be moved into its own issue.

Off topic note: If you use SDRTouch on to record raw files, ensure that the center frequency was in the dead center of the multiplex in order for it to play successfully.

**Comment by AlbrechtL** [comment]
Thanks for the RAW-file.
In 18e9a6d I reintroduced the PAD decoding for DAB including DLS.

![bbc_dl](https://user-images.githubusercontent.com/11171787/29731992-f5b436b6-89e6-11e7-9652-4296d93a8cfb.png)

The mono/stereo issue is still unsolved for both DAB and DAB+.

**Comment by es5nhc** [comment]
Regarding Latvia: Thanks to a megatropo that has just begun in the Baltics, I can finally contribute an I/Q recording. I can also confirm the issue outlined in the initial post still exists. It isn't perfect as the signal strength changes(probably a good test case for weak signal reception ;) ) but should be sufficient to replicate what I am experiencing. The affected channels are LR5 Atklājumi, LR5 Hiti, LR5 Latvieši, LR5 Rīti. Listening to the audio you can clearly hear stereo effects.

Here's the recording: https://drive.google.com/file/d/0Bz0aEk5iHH62VkFFYTZ2RDladTg/view?usp=sharing

**Comment by AlbrechtL** [comment]
Thanks for the file. It helps a lot to find the problem.

**Comment by AlbrechtL** [comment]
I found the issue.

It was not really a bug. [Parametric stereo](https://en.wikipedia.org/wiki/Parametric_Stereo) uses a mono audio signal and add some additional information to reconstruct the stereo signal. So the mono indication was actually correct.
In e8fe11a2d70c610ccb5ecb71133447767eccc992 I added some additional code to detect the parametric stereo signal and show the signal as stereo in the GUI.
![stereo_ps](https://user-images.githubusercontent.com/11171787/35480782-3f7960e2-0416-11e8-8a4a-3b411726e14a.png)

@JvanKatwijk If you like you can fix the same issue in your software.
