### ISSUE TITLE
Extreme badly Reception with DVB T stick and active antenna

### ISSUE THREAD

**Issue by Hammer20l** [AlbrechtL/welle.io#810]
Hallo Github,
I have a problem with my Welle.IO Setup. I use a DVB T Stick (MSI Digivox mini deluxe) which works on my notebook. I tryed 3 antennas, the one for all sv9323, a passive antenna from kabeldirekt and a no name mini antenna. With no antenna i get the channels in what i get with my mini radio, i only can hear a few seconds of sound with the kabeldirekt, no picture and only the channels what i get with full quality on my little radio.
Can anyone give me tips to solve the problem and get a normal antenne range?

**Comment by andimik** [comment]
You need an antenna covering the VHF III Band, which is 174 - 230 MHz.

**Comment by Hammer20l** [comment]
The Antennas are all compatible.

**Comment by andimik** [comment]
Then try to use manual gain settings.

**Comment by andimik** [comment]
@Hammer20l

Can you close this issue if solved?

**Comment by AlbrechtL** [comment]
Closed because of inactivity.
