### ISSUE TITLE
Windows welle.io has issues with sound breaking up

### ISSUE THREAD

**Issue by eth72419** [AlbrechtL/welle.io#817]
Hello,

I'm experiencing an issue with welle.io on Windows.

The sound keeps breaking up (eg. pauses and restarts) - not even the muddy bubbling sound. The antenna icon flashes on and off with constant RS errors and frequency correction. It's quite strange - this happens pretty much every 15-20 seconds, while there are no issues with this on the Android version.

It's not an issue with the signal - the RTL-SDR is connected straight to the a spare radio port using a coax cable and connector. I have also tried connecting an antenna straight to the port - with no avail.

This is likely not an issue with the RTL-SDR or computer itself, since Android works fine?

Thanks for your help - if there is any more info needed please reply!

**Comment by eth72419** [comment]
I have tried using manual gain with no change in the issue

**Comment by AlbrechtL** [comment]
Can you try the latest unstabled build please?
https://welle-io-nightlies.albrechtloh.de/20241008_ee183ef7_Windows_welle-io-setup_x64.exe

**Comment by AlbrechtL** [comment]
It would be very nice if you could post some screenshots.

**Comment by AlbrechtL** [comment]
Closed because of inactivity.
