### ISSUE TITLE
Suggested improvement for faster station scan

### ISSUE THREAD

**Issue by mickdick** [AlbrechtL/welle.io#87]
The station scanning takes very long (otherwise I am very happy with welle.io ...). In expert mode, the SNR very quickly shows values around 0 dB for "empty bouquets" during station scan. I suggest implementing a "fast scan" mode (maybe additional button) quickly jumping over apparently empty bouquets and thus accelerating the overall scan tremendously.

**Comment by AlbrechtL** [comment]
Thanks for the suggestion. I added it to the [open task list](https://github.com/AlbrechtL/welle.io/wiki/Open-Tasks). Everyone is invited to implement it and send me a pull request.

But as a first step the SNR calculation has to be repaired ["SNR calculation not working if strong neighbour channels available"](#52).
