### ISSUE TITLE
Open tasks

### ISSUE THREAD

**Issue by AlbrechtL** [AlbrechtL/welle.io#9]
A list with open tasks con be found here: https://github.com/AlbrechtL/welle.io/wiki/Open-Tasks

**Comment by mpbraendli** [comment]
Hi Albrecht,
a suggestion for the input devices: add support for SoapySDR!
https://github.com/pothosware/SoapySDR/wiki

**Comment by AlbrechtL** [comment]
Thanks for the hint. I will add it to the open task list.

**Comment by chrisdebian** [comment]
Hi, as per your aspiration, could you formally add 'Create Ubuntu Snap' (https://www.ubuntu.com/desktop/snappy) to the 'Open Task' list?

Thanks,

Chris
chris_debian
2E0FRU

**Comment by AlbrechtL** [comment]
Thanks for the idea! I tried it once to create a Snap but I fail to pack QT into the Snap.
I added it to the task list. I hope that somebody takes this job!

**Comment by andimik** [comment]
There is a nice github feature for formatting tasks:

https://help.github.com/articles/basic-writing-and-formatting-syntax/#task-lists

**Comment by AlbrechtL** [comment]
Thanks for the hint.

**Comment by AlbrechtL** [comment]
Closed to make cleanup the open issue list.

**Comment by AlbrechtL** [comment]
@joggele I don't know how to contact you so use this issue. We found your [rtl-dab](https://github.com/Joggele/rtl-dab) improvements and I invite you to collaborate with welle.io. We are highly looking for new developers that are improving the DAB SDR software and implement new features.
